### ISSUE TITLE
Id de ressource unique / Maintien de l'intégrité

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#10]
Lors de la génération d’un identifiant, les fiches de service associées sont également
mise à jour (si l’utilisateur à les droits d’édition sur les fiches correspondantes).

Processus de mise à jour des MDS à partir des MDD dans les operatesOn.

**Comment by taffoureau** [comment]
OK pour rester sur la solution suivante pour la ressource couplée, en attendant une règle claire:
<srv:operatesOn uuidref="439b7c25-f429-4066-9e3e-67c509efe83a" xlink:href="http://localhost:8080/geosource/1000/fre/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=439b7c25-f429-4066-9e3e-67c509efe83a#MD_DataIdentification"/>
