### ISSUE TITLE
Champ généalogie supprimé du formulaire

### ISSUE THREAD

**Issue by TERMEPhilippe** [geosource-catalogue/core-geonetwork#101]
A partir de la fiche modèle INSPIRE, j'ai supprimé la section Généalogie car l'outil me le permettait mais je ne retrouve pas le moyen de la rajouter

**Comment by fxprunayre** [comment]
Fixed https://github.com/geonetwork/core-geonetwork/commit/8af109b7839300b4155920484a79ce15e9173793 (le formulaire doit être recharger en cas de suppression)

Rappel: il est toujours possible de basculer dans la vue complète pour ajouter des champs.

**Comment by fxprunayre** [comment]
Options:
- ne pas permettre la suppression d'un élément 1..1 dans la vue INSPIRE
- reload
