### ISSUE TITLE
Formulaire de Saisie: Texte d'aide à la saisie coupé en haut

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#102]
L'affichage interactif de l'aide à la saisie est une vraie bonne idée.
Attention à son affichage: pour les premiers champs du formulaire, le haut du texte est coupé (voir pj pour les deux premiers champs - l'ascenseur vertical est bien tout en haut de la page)

testé sous Firefox 26.

![2 11_saisie_ergo_aide](https://f.cloud.github.com/assets/6794535/2310339/23d213c8-a2e2-11e3-934f-17f38c742fed.png)

**Comment by fxprunayre** [comment]
Benoit indique que c'est fait dans le commit ici https://github.com/geosource-catalogue/core-geonetwork/commit/1159ac78de9bf1cdf5f0f316a23a52c1f8595a16

**Comment by fxprunayre** [comment]
Report manuel dans GN https://github.com/geonetwork/core-geonetwork/issues/866

**Comment by fxprunayre** [comment]
Dispo pour test sur titellus.net.
