### ISSUE TITLE
Formulaire de Saisie: bouton "Ajout d'un localisateur" non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#103]
Cliquer sur le bouton   "Ajout d'un localisateur"  n'a aucune action.

Testé sous Firefox 26

![2 11_saisie_ajout_localisateur](https://f.cloud.github.com/assets/6794535/2310396/fad04520-a2e2-11e3-8833-8cdb70daf647.png)

**Comment by taffoureau** [comment]
Non reproduit dans la dernière version livrée.
