### ISSUE TITLE
Formulaire de Saisie: bouton "Générer un Identifiant" non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#104]
Cliquer sur le bouton "Générer un identifiant" ne remplit pas le champ d'identifiant ; il n'y a pas de retour écran. Testé sous Firefox 26.

![2 11_saisie_ajout_uri](https://f.cloud.github.com/assets/6794535/2310459/8c72dace-a2e3-11e3-9547-646cb48741b0.png)

**Comment by taffoureau** [comment]
BRGM : En cours d'implémentation.
