### ISSUE TITLE
Formulaire de Saisie: bouton "Ajout d'un Encodage" non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#105]
Cliquer sur le bouton "+" pour ajouter un type d'encodage n'ajoute pas de ligne supplémentaire. Aucun retour écran. Testé sous Firefox 26. 

![2 11_saisie_ajout_encodage](https://f.cloud.github.com/assets/6794535/2310479/04a962e2-a2e4-11e3-9ff5-d5d23a34c6d8.png)

**Comment by taffoureau** [comment]
BRGM : Non reproduit. Par contre, les deux champs (format, version) ajoutés ne peuvent être supprimés (aucun bouton X n'est affiché).
