### ISSUE TITLE
Formulaire de Saisie: Texte d'aide à la saisie des mots-clés

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#106]
(ERGONOMIE)
Est-il possible de modifier le texte d'aide à la saisie des mots clés? : 
Proposition 1: Enlever la phrase sur PT_Freetext, destinée à des développeurs et non à des utilisateurs. 
Proposition 2: Spécifier dans cette aide si l'utilisateur doit entrer un seul mot par boit, ou si l'utilisation d'un séparateur est possible (virgule?) pour entrer plusieurs mots dans une même boite (ex: par copié/collé).

![2 11_saisie_ergo_aide_motscls](https://f.cloud.github.com/assets/6794535/2310529/e92eb912-a2e4-11e3-9e2c-82699f21fde6.png)

**Comment by taffoureau** [comment]
cf. https://github.com/geosource-catalogue/core-geonetwork/issues/127
