### ISSUE TITLE
Formulaire de Saisie: bouton "Ajout d'un Mot Clé" non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#107]
Cliquer sur le bouton "+" pour ajouter un mot clé n'ajoute pas de boite supplémentaire pour saisir un mot clé. Aucun retour écran disponible. Testé sous Firefox 26.

![2 11_saisie_ajout_motcl](https://f.cloud.github.com/assets/6794535/2310560/75b2865c-a2e5-11e3-8a46-dd8e24f3860e.png)

**Comment by taffoureau** [comment]
BRGM : non reproduit
