### ISSUE TITLE
Formulaire de Saisie: Référence Spatiale du Rectangle d'emprise (mise à jour)

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#109]
Modifier les coordonnées du rectangle permet la mise à jour du graphique si l'utilisateur rafraichit la carte par zoom ou pan. S'il ne fait pas cette action, le graphique reste identique à ce qu'il était avant l'édition des coordonnées. 

Est-il possible de forcer la mise à jour de la carte au fur et à mesure de la saisie? 
Sinon, serait-il possible d'expliciter le comportement à l'utilisateur (soit pas un tooltip ou un texte d'aide, soit par une bouton "rafraichir la carte"?)  exemple en pj.

testé sous  Firefox 26.

![2 11_saisie_spatref_emprise_mise__jour](https://f.cloud.github.com/assets/6794535/2310746/508c6f66-a2e8-11e3-9564-d9fde421a4fa.png)

**Comment by fxprunayre** [comment]
De mon côté ça joue sous Chrome et FF lors de modif à la main ou utilisation des boutons (sous Chrome qui supporte le type number).
