### ISSUE TITLE
Id de ressource unique / Batch

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#11]
Un mécanisme de génération en batch réalise :
- pour les métadonnées de données : génération de l’identifiant
- pour les métadonnées de service : mise à jour des relations

2 phases : 
- MDD > Génération des identifiants
- MDS > Recherche et ajout des srv:operatesOn via l'UUID de la fiche

**Comment by taffoureau** [comment]
Suite aux récentes discussions du GT Métadonnées du CNIG : 
- Identificateur de ressource unique : [getRecordById vers la MDD]#MD_DataIdentification
- Ressource couplée (operatesOn) : xlink:href="[Identificateur de ressource unique]"

Exemple :
srv:operatesOn xlink:href="http://www.mongeosource.fr/geosource-1187/srv/fre/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&ID=7fb76211-991f-4907-953b-ede3d1a55a80&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full#MD_DataIdentification"

Attention, cet élément peut contenir un attribut uuid pointant vers l'identifiant de la MDD mais le lien se fera préférentiellement par l'attribut xlink:href (autrement dit, le lien doit être possible même s'il n'y a pas d'attribut uuidref).

**Comment by taffoureau** [comment]
Finalement, on revient sur la première solution pour l'écriture de l'identifiant, à savoir http://[adresse-du-catalogue]/[UUID de la fiche]

**Comment by taffoureau** [comment]
A améliorer dans une version 2.11.1.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geosource-catalogue/core-geonetwork/pull/200 & https://github.com/geosource-catalogue/core-geonetwork/pull/201

**Comment by fxprunayre** [comment]
Proposé côté GN https://github.com/geonetwork/core-geonetwork/pull/706
