### ISSUE TITLE
Editeur / Emprise / sélection des régions ou communes

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#110]
Le menu déroulant "DEP"  dans la zone de l'emprise du rectangle englobant est-il destiné à sélectionner un nom ou numéro de département pour assigner l'emprise de ce département à la ressource? Si oui - génial, excellent idée!!! Si non, il faudrait expliciter son action. 

Aujourd'hui, dans Firefox 26, le menu déroulant ne contient que la valeur "DEP", et entrer un numéro de département manuellement n'a aucune action. 

![2 11_saisie_spatref_emprise_dep](https://f.cloud.github.com/assets/6794535/2310803/2070a4d6-a2e9-11e3-8390-98aa077db641.png)

**Comment by taffoureau** [comment]
Préciser le fonctionnement.

**Comment by taffoureau** [comment]
A voir pour proposer les régions et communes.
