### ISSUE TITLE
Formulaire de Saisie: Recherche d'un référentiel de coordonnées

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#111]
Il est très commode de pouvoir chercher un référentiel de coordonnées dans le formulaire de saisie. Attention à l'affichage des résulats: il est en arrière-plan, derrière les éléments du formulaire, et partiellement caché (voir pj)

Testé sous Firefox 26.

![2 11_saisie_recherchereferntielcoordonnes](https://f.cloud.github.com/assets/6794535/2310866/db95ef46-a2e9-11e3-8fa8-12e29252d0d3.png)

**Comment by taffoureau** [comment]
Autocomplétion dans les autres vues uniquement.
cf. https://github.com/geosource-catalogue/core-geonetwork/issues/68
