### ISSUE TITLE
Formulaire de Saisie: Recherche d'un référentiel de coordonnées (tri des résultats)

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#112]
(Ergonomie) 

Pour la recherche d'un référentiel, il serait bon de trier les résultats, avec en premier les résultats qui commence par l'expression entrée par l'utilisateur (ex: si je tape  "RG", je devrai avoir les "RGF..." et les "RGM" en tête de liste). 

Ensuite, en second choix ("résultats approchants"), on peut ajouter les résultats qui contiennent l'expression (ref. pj, avec les sytèmes contenant "Argentina" ou "Georgia"). 

![2 11_saisie_recherchereferntielcoordonnes](https://f.cloud.github.com/assets/6794535/2310902/4a2c46ee-a2ea-11e3-9488-6bb6a277c181.png)

**Comment by taffoureau** [comment]
BRGM : proposer dans une liste déroulante uniquement les valeurs indiquées dans le cahier des charges dans la vue INSPIRE.

**Comment by taffoureau** [comment]
cf. https://github.com/geosource-catalogue/core-geonetwork/issues/68
