### ISSUE TITLE
Formulaire de Saisie: Recherche d'un référentiel de coordonnées (Utilisation des résultats)

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#113]
Dans la liste de résultats de la recherche d'un référentiel de coordonées, le bouton "+" est inactif dans Firefox 26: Auqnd on clique dessus, le référentiel sélectionné n'est pas ajouté à la boite, et aucun autre retour écran n'est disponible. ref pj.

![2 11_saisie_recherchereferntielcoordonnes_utilisation rsultats](https://f.cloud.github.com/assets/6794535/2310988/2aa5972a-a2eb-11e3-8dfa-882a36977760.png)

**Comment by taffoureau** [comment]
BRGM : non reproduit. Par contre, la liste de choix s'affiche en-dessous des autres champs sous Firefox. Par ailleurs, dans les spécifications, les valeurs de choix sont restreintes conformément au guide du CNIG.

**Comment by taffoureau** [comment]
cf. https://github.com/geosource-catalogue/core-geonetwork/issues/68
