### ISSUE TITLE
Formulaire de Saisie: Ajout d'un référentiel de coordonnées non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#114]
Cliquer sur le bouton "+" pour ajouter un référentiel n'a pas d'action. 

![2 11_saisie_ajoutreferntielcoordonnes](https://f.cloud.github.com/assets/6794535/2311020/a0c9612a-a2eb-11e3-9a66-7391e0890d12.png)

**Comment by taffoureau** [comment]
BRGM : non reproduit. Il s'agit d'autocomplétion.
