### ISSUE TITLE
Formulaire de Saisie: Texte d'aide à la résolution des erreurs

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#115]
(Ergonomie) 

Afficher les erreurs à droite de l'écran permet de savoir à tout moment où on en est et ce qu'il reste à faire - c'est très ergonomique. Attention aux textes en anglais et/ou en code, ref pj. 
Est-il possible de traiter les différents messages d'erreurs pour qu'ils puissent assister un utilisateur non-développeur (et/ou familier avec les concepts de métadonnées, mais pas les balises XML correspondantes?)

![2 11_messages](https://f.cloud.github.com/assets/6794535/2311096/71c65922-a2ec-11e3-84af-a182df3ed2a4.png)

**Comment by taffoureau** [comment]
BRGM : à discuter.

**Comment by fxprunayre** [comment]
Traductions des principales erreurs XSD et ajout des noms des éléments en plus de la balise https://github.com/geonetwork/core-geonetwork/commit/1b1fe0da24a5c8db9b408fb52fd039ae0306a4d9

**Comment by fxprunayre** [comment]
eg.
![image](https://cloud.githubusercontent.com/assets/1701393/2579381/a225e61c-b9a0-11e3-96ab-5c6dad74991b.png)
