### ISSUE TITLE
Formulaire de Saisie: Harmoniser le format des champs "Date"

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#116]
Certains champs "date" portent un bouton à icône de pendule, et permettent de sélectionner un format de date parmi 3 différents. 
Est-il possible d'harmoniser cette apparence et ce comportement à tous les champs "date"?

![2 11_dates_harmoniser](https://f.cloud.github.com/assets/6794535/2311152/25784d68-a2ed-11e3-9186-549328e6383b.png)

**Comment by taffoureau** [comment]
BRGM : Il manque les boutons pour les champs "étendue temporelle".

**Comment by taffoureau** [comment]
cf. https://github.com/geosource-catalogue/core-geonetwork/issues/117
