### ISSUE TITLE
Formulaire de Saisie: Format de saisie des champs "Date"

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#117]
La sélection d'un format de saisie dans un champ "date" semble n'avoir aucune action sur le format de date que l'utilisateur peut saisir. par exemple (ref pj),  je  choisis le format "Année", et je peux entrer une date pleine. 

En outre, est-il possible d'ajouter une aide sur le format des dates (20-12-2012? 20/12/2012? 20121220? 2012-12-20? utilisation de lettres?  etc.  ref pj aussi)

![2 11_dates_controleformats](https://f.cloud.github.com/assets/6794535/2311221/0c699baa-a2ee-11e3-8c51-e4569ed51990.png)

![2 11_dates_controleformat](https://f.cloud.github.com/assets/6794535/2311194/b3a508ba-a2ed-11e3-9280-b2a2ae963ad0.png)

**Comment by taffoureau** [comment]
BRGM : fonctionnalité modifiée dans la dernière version livrée : le choix du type de date n'est plus possible. Par ailleurs, les flèches permettant de changer de mois, année, ... dans le calendrier sont cassées sous Firefox.

**Comment by taffoureau** [comment]
Préciser le fonctionnement.

**Comment by fxprunayre** [comment]
> Préciser le fonctionnement.

Il y a 2 cas :
- Le navigateur supporte les types HTML5 date, month, time. Dans ce cas, il est possible de choisir un type de date et le navigateur utilise ses propres contrôles pour la saisie des dates, mois, heures (les contrôles peuvent avoir un look différent selon les navigateurs et les terminaux utilisés)

![image](https://cloud.githubusercontent.com/assets/1701393/2548904/ec9e5fb4-b66a-11e3-9315-075dca8eaec6.png)
- Le navigateur ne supporte pas les types HTML5 date, month, time (eg. Firefox). Dans ce cas, un champ texte contient la date (modifiable par l'utilisateur manuellement) et un calendrier permet le choix d'une date (le calendrier est généré en JS)

![image](https://cloud.githubusercontent.com/assets/1701393/2548914/186dee0c-b66b-11e3-94ef-6d00bc289907.png)
