### ISSUE TITLE
Formulaire de Saisie:  Harmoniser le comportement des boites "Valeurs recommndées"

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#118]
(ergonomie)

Toutes les boites "valeurs recommandées" n'ont pas le même comportement. Comparer par exemple celle relative à l'encodage des données et celle relative à l'échelle de référence de la résolution des données (voir pj). 

Proposition: Harmoniser le comportement sur l'exemple de la boite relative à l'encodage des données. 

(testé sur Firefox 26)

![2 11_boites_valeurs_recommandes](https://f.cloud.github.com/assets/6794535/2311303/0fbd8dba-a2ef-11e3-9533-2473b740efee.png)

**Comment by taffoureau** [comment]
BRGM : reproduit. Par ailleurs, le type de ce champ est "liste déroulante avec possibilité de saisir du texte".

**Comment by taffoureau** [comment]
cf. https://github.com/geosource-catalogue/core-geonetwork/issues/54
