### ISSUE TITLE
Formulaire de Saisie: bouton "Ajout d'une résolution" non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#119]
Cliquer sur le bouton "+" de  la ligne "Résolution spatiale" n'a aucune action - aucun retour écran dispo. (testé sous Firefox 26).

![2 11_ajout_rsolution](https://f.cloud.github.com/assets/6794535/2311446/e7d9610a-a2f0-11e3-8a53-b5b86dfdc8ef.png)

**Comment by taffoureau** [comment]
BRGM : non reproduit.
