### ISSUE TITLE
Formulaire de Saisie: Section Qualité sans titre

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#120]
Les champs relatifs à la qualité des données apparaissent sous le titre "Résolution Spatiale" (ref pj)
Observé sous Firefox 26.

![2 11_qualitsanstitre](https://f.cloud.github.com/assets/6794535/2311561/53ba52f2-a2f2-11e3-85c2-b92794e830f9.png)

Proposition de modification en ci dessous:.

![2 11_qualit](https://f.cloud.github.com/assets/6794535/2311507/9582f474-a2f1-11e3-9447-3476055d9b85.png)

**Comment by taffoureau** [comment]
cf. https://github.com/geosource-catalogue/core-geonetwork/issues/56
