### ISSUE TITLE
Formulaire de Saisie: Degré de conformité non explicite

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#121]
Dans les champs de qualité, rien n'explique à l'utilisateur ce qu'indique la boite à cocher "degré". Proposition de modification: renommer "degré" en "Conforme" ou "Non Conforme", et/ou ajouter un tooltip.

![2 11_qualit_degrconformit](https://f.cloud.github.com/assets/6794535/2311543/14ed36a2-a2f2-11e3-9848-8c036dd8c801.png)

**Comment by taffoureau** [comment]
BRGM : dans les spécifications, le champ est nommé "Degré" avec les valeurs "Conforme", "Non conforme", "Non évalué" dans une liste déroulante.
Un tooltip doit être associé à ce champ.

**Comment by taffoureau** [comment]
cf. https://github.com/geosource-catalogue/core-geonetwork/issues/56
