### ISSUE TITLE
Formulaire de Saisie:  Conditions d'utilisations/d'accès non fonctionnelles

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#122]
Cliquer les boutons "+" pour ajouter des conditions d'utilisation ou d'accès (les deux) n'a aucune action - aucun retour écran disponible.

Testé sous Firefox 26.

![2 11_cgu](https://f.cloud.github.com/assets/6794535/2311617/ee7bd6bc-a2f2-11e3-9d69-bb07bb28677f.png)

**Comment by taffoureau** [comment]
BRGM : non reproduit.
