### ISSUE TITLE
Formulaire de Saisie:  Aide non fonctionnelle

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#123]
Cliquer sur le lien "Besoin d'aide?" génère un message d'erreur, reporté ci-dessous.

Testé sous Firefox 26.

![2 11_saisie_aide](https://f.cloud.github.com/assets/6794535/2311652/4d45bdac-a2f3-11e3-84b3-b94bb9e689a5.png)

**Comment by taffoureau** [comment]
BRGM : Non encore implémenté. Doit pointer vers la documentation embarquée dans l'application.
