### ISSUE TITLE
Formulaire de Saisie: Recherche d'un point de contact à expliciter

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#124]
La recherche d'un point de contact semble non fonctionnelle (mais je ne suis pas sûre de l'avoir utilisé comme il faut... ?)
1- Les boutons de remplissage semi-auto (pj ci dessous) n'apparaissent que si l'on saisit une valeur, puis qu'on la supprimer avec la touche clavier "delete" (retour en arrière). 
BRGM : Reproduit.

1 bis - ces boutons n'apparaissent pas pour le premier contact, mais uniquement à partir du second.
BRGM : non reproduit.

![2 11_boutons_pointsdecontacts](https://f.cloud.github.com/assets/6794535/2312108/cbbfe1b8-a2f7-11e3-9511-d20c2f1ad2bd.png)

2- Les bouton de l'appli sur la copie et l'ajout à partir de l'annuaire ajoutent tous les deux des entrées vides (seul le rôle choisi est rempli). ref pj ci dessus
BRGM : reproduit mais uniquement dans le cas d'un ajout via xlink.

3- Comment ajouter un point de contact à l'annuaire? Est-ce un annuaire dans l'appli, ou le LDAP d'entreprise?
BRGM : L'ajout d'un contact se fait via la console d'administration (dans "thésaurus" dans la 2.11) en dupliquant un contact existant.

**Comment by fxprunayre** [comment]
> 1- Les boutons de remplissage semi-auto (pj ci dessous) n'apparaissent que si l'on saisit une valeur, puis qu'on la supprimer avec la touche clavier "delete" (retour en arrière). 
> BRGM : Reproduit.

Il est possible d'utiliser \* pour une recherche globale, ou "Eti*"

**Comment by fxprunayre** [comment]
> 3- Comment ajouter un point de contact à l'annuaire?

Interface de gestion : http://localhost:8080/geonetwork/srv/fre/catalog.edit#/directory
