### ISSUE TITLE
Moissonnage: bouton de sélection du type de noeud pas toujours fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#125]
Dans l'interface de moissonnage, les différents types de nœuds sont souvent reportés comme "non supportés" - il s'agit du menu déroulant issu du bouton " + Moissonner", voir ci-dessous. 

Observé sur Firefox 26, non systématique mais prédominant. 

![2 11_moissonner](https://f.cloud.github.com/assets/6794535/2384235/87bcfe70-a909-11e3-89e8-bb952f4ab3b7.png)

**Comment by fxprunayre** [comment]
Reproduit de temps en temps - difficile d'identifier le pb. 

Solution de contournement : recharger la page

**Comment by fxprunayre** [comment]
A priori corrigé grâce à https://github.com/geonetwork/core-geonetwork/commit/4c8aeeda8e28d2f75d06d9275e695702ee7bed87
