### ISSUE TITLE
Moissonnage: boutons "enregistrer" et "moissonner" non fonctionnels pour le protocole GeoNetwork (Ancienne version)

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#126]
Apres avoir entré des paramètres de moissonnage pour une nœud de type répertoire, il est possible de l'enregistrer (apparait à la gauche de l'écran dans la boite "nœuds distants"), et de le lancer (avec retour écran sur les erreurs éventuelles).  

Il est en revanche impossible d'enregistrer des paramètres de moissonnage pour un nœud de type "GeoNetwork (Ancienne version)", sans qu'aucun message d'erreur ne soit retourné à l'uilisateur. Lancer le moissonnage (bouton moissonner) a le même comportement: aucune action, ni aucun retour écran. 

Observé sur Firefox 26. 

![2 11_moissonner_gsc_ancien](https://f.cloud.github.com/assets/6794535/2384315/bbcc88c4-a90a-11e3-92b8-0d50b5d963d9.png)

**Comment by fxprunayre** [comment]
Il faudrait fournir la configuration du moissonnage pour pouvoir tester.

Avez vous renseigné le champ siteId (qui est obligatoire dans ce protocol) ?

Exemple d'erreur :

```
<error id="bad-parameter">
  <message>is not a valid value for: siteId</message>
  <class>BadParameterEx</class>
```
