### ISSUE TITLE
Tooltip ne fonctionne pas pour certains champs

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#127]
Dans la dernière version livrée, les tooltips fonctionnent uniquement pour les champs titre, résumé, type de ressource et mots-clés.

**Comment by fxprunayre** [comment]
Est-ce qu'il n'était pas prévu de définir de revoir le contenu des tooltips ? avec même des contenus différents dans vue INSPIRE et les autres vues ?

**Comment by fxprunayre** [comment]
Les champs de la vue INSPIRE configurés ici https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/layout/config-editor.xml#L203 utilisent les label https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/loc/fre/strings.xml#L34

**Comment by fxprunayre** [comment]
Indiquer pour chaque champ dans strings.xml l'élément correspondant dans labels.xml
eg.
https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/loc/fre/strings.xml#L49
https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/loc/fre/labels.xml#L1195

identifier correspond à name="gmd:code", context="gmd:MD_Identifier"

Ensuite on cable les tooltips si toutes sont dans labels.xml

**Comment by fxprunayre** [comment]
Fait cf. exemple https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/layout/config-editor.xml#L217

**Comment by taffoureau** [comment]
OK.
