### ISSUE TITLE
Ajout de contacts depuis un annuaire

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#128]
Deux remarques :
- traduction infobulles sur la signification des boutons :
  Ajout sans xlink : pourquoi "par défaut" si une action est nécessaire?
  Ajout avec xlink : il y a une faute dans "annuraire"
- rôle : la liste doit être restreinte aux valeurs indiquées dans le cahier des charges également lors de l'ajout depuis un annuaire.

**Comment by fxprunayre** [comment]
> il y a une faute dans "annuraire"

https://github.com/geonetwork/core-geonetwork/commit/8a1cf920e03732456a1932521f0c387fe5e01834

> pourquoi "par défaut"

https://github.com/geonetwork/core-geonetwork/commit/1ca8b2dd84d1f2ce93e5fdaa96f2be79c1fb17d6

> rôle : la liste doit être restreinte aux valeurs indiquées dans le cahier des charges également lors de l'ajout depuis un annuaire.

https://github.com/geonetwork/core-geonetwork/commit/c63ba1096067b6aeb2f14f1e85ea05dffe5c6d06
