### ISSUE TITLE
Formulaire : "Plus de détail"

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#129]
L'activation de cette option ne change rien dans la vue INSPIRE.

Je suis d'avis de la supprimer.

**Comment by fxprunayre** [comment]
On ne peut pas savoir s'il y a des attributs ou pas dans une vue. Les options tooltip et plus de détail ne sont pas spécifiques à la vue mais s'appliquent à tous les onglets. 

Dans le cas de GéoSource, tu as demandé à cacher les attributs de la vue INSPIRE justement
https://github.com/geosource-catalogue/core-geonetwork/commit/51f494cb3ccd7fe1e3af5cd73f03b45d27d10ebe

**Comment by taffoureau** [comment]
Déjà corrigé.
