### ISSUE TITLE
Position du curseur après rafraichissement de la page

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#130]
par exemple, après l'ajout/suppression d'un champ  (eg contact sur les métadonnées), le curseur se déplace au milieu du formulaire. Or, celui-ci devrait rester positionné au niveau du même champ.

**Comment by fxprunayre** [comment]
Si ca marche bien, préparer une PR pour GN

**Comment by fxprunayre** [comment]
Ca a également été fait dans GN3 par Florent je pense. A vérifier si ca convient.

**Comment by fxprunayre** [comment]
A tester par Etienne pour voir si ce qui a été fait côté GN est suffisant et si du coup nous n'avons rien à faire sur ce point. Je l'assigne à Etienne.

A tester sur le site de démo titellus.net.
