### ISSUE TITLE
Accès à la page catalog.signin

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#132]
L'accès à cette page se fait au moins à deux endroits:

1) Lorsque les identifiants de connexion renseignés sont incorrects --> OK pour renvoyer vers cette page mais plusieurs propositions:
- à quoi sert le bouton "s'identifier" à droite du nom du catalogue?
- renommer "Vous avez oublié vos données?" en "Vous avez oublié votre mot de passe?"
- Corriger "récupration"
- Renommer "Vous avez oublié votre mot de passe" en "Récupérer mon mot de passe" et ajouter la possibilité de renseigne le nom de l'utilisateur directement depuis cette page (une action de moins).
- Supprimer le choix de la langue

2) Par redirection de l'adresse http://metadatacarmen.brgm-rec.fr/geosource/1000/ --> N'est-ce pas plus logique de rediriger vers la page de recherche (http://metadatacarmen.brgm-rec.fr/geosource/1000/fre/find ?)

**Comment by taffoureau** [comment]
![catalog signin](https://f.cloud.github.com/assets/2026724/2448958/4fc91ec4-aeac-11e3-8102-0572efcb5a87.png)

**Comment by fxprunayre** [comment]
> à quoi sert le bouton "s'identifier" à droite du nom du catalogue?

C'est le titre de la page.

> renommer "Vous avez oublié vos données?" en "Vous avez oublié votre mot de passe?"

Je te laisse faire les modifs pour GéoSource https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web-ui/src/main/resources/catalog/locales/fr-core.json. Ce ne sera pas appliqué à GN.

> Corriger "récupration"

Appliquer à GN. https://github.com/geonetwork/core-geonetwork/commit/48b821a246257535aa05c2bd8621b38368635532

> Renommer "Vous avez oublié votre mot de passe" en "Récupérer mon mot de passe" et ajouter la possibilité de renseigne le nom de l'utilisateur directement depuis cette page (une action de moins).

Non.

> Supprimer le choix de la langue

https://github.com/geosource-catalogue/core-geonetwork/commit/70bff740aca5bfb3981569f0157a61326b5dad04

> 2) Par redirection de l'adresse http://metadatacarmen.brgm-rec.fr/geosource/1000/ --> N'est-ce pas plus logique de rediriger vers la page de recherche (http://metadatacarmen.brgm-rec.fr/geosource/1000/fre/find ?)

Peut être fait via les rewrites apache ?

**Comment by taffoureau** [comment]
Peut être fait via les rewrites apache ?
==> fait.

C'est le titre de la page.
==> OK, je m'interrogeais surtout du fait que le bouton était cliquable...

**Comment by fxprunayre** [comment]
> > 2) Par redirection de l'adresse http://metadatacarmen.brgm-rec.fr/geosource/1000/ --> N'est-ce pas plus logique de rediriger vers la page de recherche (http://metadatacarmen.brgm-rec.fr/geosource/1000/fre/find ?)
> 
> Peut être fait via les rewrites apache ? 

Fait dans GeoNetwork
https://github.com/geonetwork/core-geonetwork/pull/619
