### ISSUE TITLE
Fiches en consultation hors-cadre

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#133]
En consultation, les fiches peuvent être déplacées hors cadren mais il est ensuite impossible de les déplacer. cf copie d'écran.
![fiche_hors_cadre](https://f.cloud.github.com/assets/2026724/2449457/3e1ea54a-aeb1-11e3-8e2a-e4c5d1a71f33.png)

**Comment by fxprunayre** [comment]
Utiliser ESC pour fermer la popup.

**Comment by fxprunayre** [comment]
Activation de la contrainte sur la fenêtre pour le moment (elle ne peut sortir du viewport) cf. https://github.com/geosource-catalogue/core-geonetwork/commit/297662d953e145a06ec9840d0dd1959ce3d6a13f.

A améliorer pour uniquement la toolbar (même si je ne vois pas l'intérêt de passer 1.25j sur ce sujet).

A ne pas faire pour GN

**Comment by fxprunayre** [comment]
N'a plus d'intérêt dans GN/GS3. Je ferme.
