### ISSUE TITLE
Indication de chargement après action

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#137]
Par exemple, l'ajout d'un champ peut prendre quelques secondes ==> ajouter une icône permettant d'indiquer qu'un traitement est en cours et d'empêcher que d'autres actions soient réalisées par l'utilisateur avant la fin de ce traitement.

**Comment by fxprunayre** [comment]
A appliquer :
- Changement de vue/onglet
- ajout/suppression d'élément 
- ajout d'élément d'un annuaire (contact)
- ajout d'une section thésaurus
- ajout d'une projection
- ajout/suppression des actions ressources associées (imagette, fichier, ...)
- suggestion
- sauvegarde

Préparer une PR pour GN

**Comment by fxprunayre** [comment]
Pour info partiellement réalisé dans GN3, cf. https://github.com/geonetwork/core-geonetwork/blob/db2dfbc0c2d713a9dee76bb38e8777f71275ba7a/web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js#L354

**Comment by fxprunayre** [comment]
Complété par @fgravin ici https://github.com/geonetwork/core-geonetwork/commit/9694c9d3662c6a609e748045ae6845706415a8e4

A finaliser pour ce qui reste.

**Comment by fxprunayre** [comment]
Egalement fait pour la génration d'imagette https://github.com/geonetwork/core-geonetwork/issues/811. A compléter.

**Comment by fxprunayre** [comment]
J'ai ajouté les indicateurs sur les actions suivantes :
- sauvegarde : fait
- annuler : fait
- sauver et fermer : fait
- sauver en changeant de type (modèle/fiche) : fait
- valider : fait
- Changement de vue/onglet : fait
- ajout d'élément d'un annuaire (contact) : fait
- ajout d'une section thésaurus : fait
- ajout d'une projection : fait
- suggestion : fait
- ajout/suppression des actions ressources associées (imagette, fichier, ...) 
  - ajout d'imagette URL : fait
  - ajout d'imagette fichier : fait
  - ajout d'imagette impression : fait
  - suppression d'imagette : fait
  - suppression ressource en ligne : fait
- ajout/suppression d'élément simple : fait
- ajout/suppression d'attributs : fait
- ajout keyword : fait
- ajout thésaurus : fait
- process button (eg. compute extent from keywords)
- Ressources associées
  - ajout de ressource en ligne URL
  - ajout de ressource en ligne upload de fichier
  - associer une fiche parent
  - associer un service/dataset (y'a un bug ici https://github.com/geonetwork/core-geonetwork/issues/861)
  - associer une source
  - associer un catalogue d'attributs
  - associer une autre ressource
  - et le clic pour supprimer tous ces types de liens.
- \+ dans le moissonnage et un certain nombre d'autres actions dans l'admin.

**Comment by fxprunayre** [comment]
Ticket GN correspondant https://github.com/geonetwork/core-geonetwork/issues/925

**Comment by fxprunayre** [comment]
A tester et indiquer les actions manquantes s'il y en a.
