### ISSUE TITLE
Etendue temporelle - Eléments manquants

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#138]
Il manque le calendrier et la valeur "Maintenant".

**Comment by fxprunayre** [comment]
> Il manque la valeur "Maintenant".

Sans faire du spécifique GéoSource, je propose ça en ajoutant la possibilité de faire un champ basé sur une valeur de codelist (https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/config-editor.xsd#L492) : 

![image](https://cloud.githubusercontent.com/assets/1701393/2547393/5b259094-b650-11e3-930a-0fbb56c3c604.png)

**Comment by fxprunayre** [comment]
> Il manque le calendrier

Fixed https://github.com/geonetwork/core-geonetwork/commit/4ca28bfe7f5d63b460f1d008c285051f5f90d444

**Comment by fxprunayre** [comment]
"bouton radio calendrier + bouton radio maintenant"

**Comment by fxprunayre** [comment]
A discuter. Cf. https://github.com/geonetwork/core-geonetwork/issues/434

**Comment by fxprunayre** [comment]
Je propose l'approche suivante qui permet d'éditer de manière générique dans les différents cas l'attribut indeterminatePosition. Si la valeur maintenant ou inconnu est choisi, la date est mise à null.

La configuration est la suivante : https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/layout/config-editor.xml#L647

![image](https://cloud.githubusercontent.com/assets/1701393/2602811/88dad060-bb25-11e3-9dd1-3b9a68ed9538.png)

Le principal pb de l'approche du bouton radio est qu'il sera alors difficile de conserver les valeurs existantes qui ne seront pas "now". Elle se limite à une valeur possible alors que certains utilisateurs (eg. ifremer) utilisent également les autres.
