### ISSUE TITLE
Ajout d'un identificateur de ressource unique non supprimable

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#141]
L'ajout d'un champ "localisateur de la ressource" entraîne systématiquement l'ajout d'un champ "identificateur de ressource unique" (!) non supprimable.

**Comment by fxprunayre** [comment]
Non reproductible. Peux tu préciser le scénario ?

**Comment by fxprunayre** [comment]
Uniquement si pas de champ identifiant de ressource unique (interaction avec cardinalité 1 probable)

**Comment by fxprunayre** [comment]
A tester

**Comment by taffoureau** [comment]
Corrigé.
