### ISSUE TITLE
Mode d'affichage des catégories

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#143]
catégorie = regroupement de champs

La taille et la position du libellé de la catégorie doit être similaire aux autres champs. Les sous-champs de cette catégorie doivent être décalés vers la droite conformément aux maquettes.

Catégories non conformes : date de référence, résolution spatiale, rectangle de délimitation géo
catégories conformes: organisation responsable de la ressource, conformité, ...

**Comment by fxprunayre** [comment]
Quelques changements fait (sachant qu'ils vont probablement "casser" en partie l'aspect "responsive" apporté par bootstrap). Non appliqué à GeoNetwork.

**Comment by fxprunayre** [comment]
A améliorer:
- titre date de référence, résolution
- étendue : une seule section

**Comment by taffoureau** [comment]
OK.
