### ISSUE TITLE
Problèmes liés à la résolution spatiale

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#144]
A l'ajout d'une nouvelle résolution, seule l'échelle est proposée (pas la distance).

Les valeurs recommandées pour l'échelle ne sont pas ajoutées dans le champ texte.

**Comment by fxprunayre** [comment]
> A l'ajout d'une nouvelle résolution, seule l'échelle est proposée (pas la distance).

Ajout des 2 options avec 2 boutons et libéllé explicite

![image](https://cloud.githubusercontent.com/assets/1701393/2547339/4117f9b8-b64f-11e3-9fb2-4d6983fb8cdc.png)

Note: du fait de #75, les attributs sont cachés dans la vue INSPIRE. L'unité est un attribut et n'est donc pas visible. Elle est cependant bien mise à jour en fonction des valeurs recommandées (https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/loc/fre/labels.xml#L1780) qui ne contiennent que des mètres.

> Les valeurs recommandées pour l'échelle ne sont pas ajoutées dans le champ texte.

Non reproductible. Peux tu préciser ?

**Comment by fxprunayre** [comment]
A tester avec un bouton avec flêche (cf. vue avancée)

**Comment by taffoureau** [comment]
> Les valeurs recommandées pour l'échelle ne sont pas ajoutées dans le champ texte.

Uniquement sous firefox. fonctionne sous Chrome.

**Comment by fxprunayre** [comment]
Non reproductible (peut être que la correction de #158 est en lien).

**Comment by taffoureau** [comment]
Corrigé.
