### ISSUE TITLE
Conditions applicables à l'accès et à l'utilisation

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#145]
Clic sur + --> ajout d'un champ "limitation d'utilisation" ==> conserver l'intitulé du champ
Valeurs de suggestion : "utilisation libre sous réserve …"  ==> sort du cadre + supprimer la valeur "données ouvertes" (dans le nouveau guide du CNIG cette valeur est ajoutée dans les mots-clés).

**Comment by fxprunayre** [comment]
> Clic sur + --> ajout d'un champ "limitation d'utilisation" ==> conserver l'intitulé du champ

C'est le cas ?

![image](https://cloud.githubusercontent.com/assets/1701393/2547136/9ba76792-b64a-11e3-9bb8-310b2ef2584e.png)

> Valeurs de suggestion : "utilisation libre sous réserve …" ==> sort du cadre + supprimer la valeur "données ouvertes" (dans le nouveau guide du CNIG cette valeur est ajoutée dans les mots-clés).

La notion de retour à la ligne dans un élément HTML select > option ne semble pas être disponible (http://stackoverflow.com/questions/2864238/line-break-in-html-select-option). Options:

1) réduire la taille du libellé (pas la valeur)
2) passer en mode radio

**Comment by fxprunayre** [comment]
> 1) réduire la taille du libellé (pas la valeur)
> supprimer la valeur "données ouvertes"

Option 1 appliquée
https://github.com/geosource-catalogue/core-geonetwork/commit/1ff738a1a5a821c3fbe71736756ffb8a23305379

**Comment by fxprunayre** [comment]
Remplacer libellé  "limitation d'utilisation"  par "Condition ...."

**Comment by fxprunayre** [comment]
A tester
