### ISSUE TITLE
Limitations d'accès public

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#146]
Clic sur + --> ajout de deux champs "Contraintes d'accès" et "autres contraintes" ==> seul le libellé "Limitations d'accès public" doit apparaître. Seules les valeurs contenues dans "Autres contraintes" doivent être affichées.
Dans le cdc, la description des valeurs devait être affichées dans des infobulles, au survol de la souris

**Comment by fxprunayre** [comment]
Also depend on de0581415cc948868c8dda7345dfd17a05cde8df

**Comment by fxprunayre** [comment]
![image](https://cloud.githubusercontent.com/assets/1701393/2578860/ecd2e3de-b998-11e3-9146-6c89a43bd671.png)
