### ISSUE TITLE
Meilleure séparation des éléments dans le formulaire

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#147]
Il doit y avoir des lignes séparatrices entre chaque champ (doivent être peu accentuées)
es informations sur la ressource ou les métadonnées doivent être davantage séparées (dans le cdc, il s'agit de deux blocs de couleur différente, avec un décalage vertical)

**Comment by fxprunayre** [comment]
Comme ça  ?

![image](https://cloud.githubusercontent.com/assets/1701393/2579610/3edd8850-b9a3-11e3-9fd1-79046b1f5f8e.png)

**Comment by taffoureau** [comment]
Dans mon idée il ne fallait pas mettre de séparateur entre deux mêmes champs, par exemple entre deux localisateurs de la ressource... Surtout dans l'optique de ne conserver q'un seul libellé pour deux champs identiques..

**Comment by fxprunayre** [comment]
![image](https://cloud.githubusercontent.com/assets/1701393/2602903/2b219092-bb27-11e3-8336-d63e7b0071dc.png)

**Comment by taffoureau** [comment]
OK!
