### ISSUE TITLE
Problème moissonnage OAI

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#148]
La moisson OIA ne se fait pas. Il y a bien la requete ListIdentifiers qui passe, mais ensuite visiblement cela plante au premier traitement de GetRecord. Quand tu vas sur le nœud de moisson défini, on voit le message suivant : 
Executing an update/delete query; nested exception is javax.persistence.TransactionRequiredException: Executing an update/delete query
Un probleme Java mais pas d’OAI.

**Comment by fxprunayre** [comment]
Peux tu mettre la config du moissonnage pour pouvoir reproduire ? Merci

**Comment by fxprunayre** [comment]
![image](https://f.cloud.github.com/assets/1701393/2522946/f69a9048-b4c9-11e3-865c-16b505c29ad5.png)

**Comment by fxprunayre** [comment]
Ca me semble ok (en lien avec des corrections moissonnages faites il y a 2 semaines probablement)

![image](https://cloud.githubusercontent.com/assets/1701393/2547266/8a966086-b64d-11e3-81fc-dbeda15a9961.png)

A retester. J'ai ajouter la possibilité de ne pas définir de set (ie. série) cf. d71879700f082aede022bbe7a302f76d21e9f9c9

**Comment by taffoureau** [comment]
Impossible d'interroger un serveur OAI:
http://oai.brgm.fr/entries/sigescen/
ou
http://cris.uns.ac.rs/OAIHandler/
Aucun préfixe n'est proposé.
Erreur => Impossible de retrouver les séries et les préfixes. Vérifier l'URL

Testé sur serveur de recette et sur geosourcedemo.

**Comment by fxprunayre** [comment]
De mon côté ca joue pour siges :
![image](https://cloud.githubusercontent.com/assets/1701393/3272896/df2c605c-f31d-11e3-8449-8551dcb14838.png)

par contre l'autre 
![image](https://cloud.githubusercontent.com/assets/1701393/3272928/36cda26c-f31e-11e3-9dcf-a9320aace9ed.png)

Tu fais quoi comme manip pour la configuration ?

**Comment by fxprunayre** [comment]
Se connecter au catalogue dans FF.
Tester dans POSTER :
- URL : http://localhost:8080/geonetwork/srv/fre/admin.harvester.info@json
- Content type : application/xml
- Content :

```
<request><type url="http://oai.brgm.fr/entries/sigescen/">oaiPmhServer</type></request>
```

La réponse devrait être du genre :

```
[{
  "formats": ["oai_dc"],
  "sets":   [
        {
      "name": "GEO:FRANCE:CENTRE",
      "label": "CENTRE"
    },
        {
      "name": "GEO:FRANCE:CENTRE:CHER",
      "label": "CHER"
    },
        {
      "name": "GEO:FRANCE:CENTRE:CHER:ACHERES",
      "label": "ACHERES"
    },
```

**Comment by taffoureau** [comment]
Ca marche en configurant un proxy dans l'admin.
