### ISSUE TITLE
Gestion du rôle pour les contacts

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#149]
Lors de l'ajout d'un contact depuis un annuaire, la liste proposée est la liste ISO complète. Or, il faudrait restreindre ces valeurs conformément au cahier des charges.

A noter que lorsqu'on ajoute une valeur qui ne fait pas partie de la liste restreinte (par exemple, "exécutant") il s'affiche une valeur vide même dans la vue complète.

**Comment by fxprunayre** [comment]
> Lors de l'ajout d'un contact depuis un annuaire, la liste proposée est la liste ISO complète. Or, il faudrait restreindre ces valeurs conformément au cahier des charges.

A priori non : 

![image](https://cloud.githubusercontent.com/assets/1701393/2547004/cd1278f6-b647-11e3-8533-3334e370a2f3.png)

> A noter que lorsqu'on ajoute une valeur qui ne fait pas partie de la liste restreinte (par exemple, "exécutant") il s'affiche une valeur vide même dans la vue complète.

A priori non : 

eg. 

```
<gmd:contact>
      <gmd:CI_ResponsibleParty>
         <gmd:organisationName gco:nilReason="missing">
            <gco:CharacterString/>
         </gmd:organisationName>
         <gmd:role>
            <gmd:CI_RoleCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_RoleCode"
                             codeListValue="exécutant"/>
         </gmd:role>
      </gmd:CI_ResponsibleParty>
  </gmd:contact>
```

![image](https://cloud.githubusercontent.com/assets/1701393/2547008/fe4851a2-b647-11e3-93de-c6cfeda3e21a.png)
