### ISSUE TITLE
Longueur de champ pour les identifiants

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#15]
Mettre tous les champs où sont stockés des identifiants (fileIdentifier ou MD_Identifier) en type text. Par exemple, le champ uuid dans la table metadata.

Car certains fichiers peuvent avoir des identifiants "à rallonge".

**Comment by fxprunayre** [comment]
> Mettre tous les champs où sont stockés des identifiants (fileIdentifier ou MD_Identifier) en type text. Par exemple, le champ uuid dans la table metadata.

C'est déjà un champ texte.

> Car certains fichiers peuvent avoir des identifiants "à rallonge".

Ca veut dire 10, 100, 1000 ? Tu as eu des erreurs ?

**Comment by fxprunayre** [comment]
Certains utilisateurs considèrent que ce type d'identifiant doit être supporté !:

```
"<gco:CharacterString>
/selection_series_popup.do?calcul=yes&reset=&serieCode=EA36&geoCode=11175&geoCode=11177&geoCode=11178&geoCode=11191&ge
oCode=11192&geoCode=11193&geoCode=11194&geoCode=11195&geoCode=12108&geoCode=12110&geoCo
de=12151&geoCode=12152&geoCode=12202&geoCode=12260&geoCode=12280&geoCode=12327&geoCode=1
2376&geoCode=12418&geoCode=12428&geoCode=12436&geoCode=12437&geoCode=12441&geoCode=12445
&geoCode=12514&geoCode=12550&geoCode=12561&geoCode=12621&geoCode=12658&geoCode=12671&ge
oCode=12689&geoCode=13159&geoCode=13162&geoCode=14154&geoCode=14155&geoCode=14157&geoCo
de=14188&geoCode=14267&geoCode=14268&geoCode=14325&geoCode=14339&geoCode=14370&geoCode=1
4390&geoCode=15244&geoCode=15249&geoCode=15253&geoCode=15272&geoCode=15285&geoCode=15322
&geoCode=15329&geoCode=15335&geoCode=15356&geoCode=15416&geoCode=15417&geoCode=15479&ge
oCode=15486&geoCode=17224&geoCode=17233&geoCode=17240&geoCode=17247&geoCode=17264&geoCo
de=17309&geoCode=17312&geoCode=17331&geoCode=17332&geoCode=17346&geoCode=17365&geoCode=1
7381&geoCode=17382&geoCode=17419&geoCode=17423&geoCode=17487&geoCode=18201&geoCode=18207
&geoCode=18226&geoCode=18238&geoCode=18242&geoCode=18269&geoCode=18273&geoCode=18274&ge
oCode=18303&geoCode=18315&geoCode=18343&geoCode=18363&geoCode=19111&geoCode=19130&geoCo
de=19134&geoCode=19148&geoCode=19166&geoCode=19304&geoCode=19305&geoCode=19306&geoCode=1
9313&geoCode=19383&geoCode=19384&geoCode=1942A&geoCode=1942B&geoCode=111&geoCode=121&geoCode=122&geoCode=123&geoCode=124&geoCode=125&geoCode=126&geoCode=131&geoCode=141&geoCode=142&geoCode=143&geoCode=152&geoCode=153&geoCode=154&geoCode=172&geoCode=173&geoCode=
174&geoCode=182&geoCode=183&geoCode=191&geoCode=193&geoCode=194&geoCode=197
</gco:CharacterString>"
```

**Comment by fxprunayre** [comment]
Testé l'import de http://www.geocatalogue.fr/Detail.do?id=155902 sans problème dans la base du compte 1045.

**Comment by taffoureau** [comment]
Pour ma part j'ai une erreur à l'import, y compris sur le compte 1045.

Ce genre d'identifiant (2163 caractères) est sensé passer d'un champ de type character varying(255)?

Résultat de l'import de métadonnées :

Erreur lors de l'insertion de la métadonnée :

could not execute batch; SQL [insert into Metadata (data, changeDate, createDate, displayorder, doctype, popularity, rating, root, schemaId, title, isTemplate, isHarvested, harvestUri, harvestUuid, groupOwner, owner, source, uuid, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not execute batch DataIntegrityViolationException ... ... ... ... ... ... ... ... ... fre xml.mef.import.ui

**Comment by taffoureau** [comment]
A modifier en base directement si besoin.
