### ISSUE TITLE
Ajout favicon ne fonctionne pas

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#150]
L'ajout d'un logo pour le catalogue fonctionne.

Pour le favicon, un message affiche que la mise à jour a bien été effectuée mais l'image n'apparaît pas (message logs : WARN  [geonetwork.resources] - Resource not found, default resource returned: /images/logos/favicon.ico)

Non testé en mode monosite.

Par ailleurs, il y a un problème d'encodage dans les infobulles "l'utiliser pour le no&#339;ud"

**Comment by fxprunayre** [comment]
Fix pour ajout d'un favicon.
2a4b44e8cc9be6d4716a6570f2636320291d1ad2

> Par ailleurs, il y a un problème d'encodage dans les infobulles "l'utiliser pour le noœud"

5a73181f5f04ccd640bcd164c1fe6506c17bdb74

> Non testé en mode monosite.

idem

**Comment by taffoureau** [comment]
Corrigé.
