### ISSUE TITLE
Gestion des ressources partagées (favicon) en mode multisite

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#151]
Potentiellement, certaines ressources ajoutée par des utilisateurs peuvent être supprimées par d'autres (par exemple, les logos).

Par ailleurs il n'a qu'un seul favicon pour l'ensemble des sites.

**Comment by fxprunayre** [comment]
C'était le cas sous Jeevlet également : des ressources sont partagées, eg. thésaurus, logos

> Par ailleurs il n'a qu'un seul favicon pour l'ensemble des sites.

Supprimer cette notion qui est en générale gérée au niveau du site web principal ?

**Comment by fxprunayre** [comment]
Suppression de la configuration de la favicon du site (cf. head de la page HTML)
