### ISSUE TITLE
Valeurs incorrectes dans la liste du type de ressource

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#153]
La valeur "jeu de données non géographique" ne devrait pas apparaître dans la vue INSPIRE

**Comment by fxprunayre** [comment]
Il ne peut y avoir de distinction par vue. Valeur de codelist cachée pour toutes les vues.

**Comment by fxprunayre** [comment]
Configuration des codelists (éventuellement en fonction des informations de la fiche) https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/loc/fre/codelists.xml#L1464
