### ISSUE TITLE
(admin) Gestion des utilisateurs / modification de l'adresse

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#156]
Scénario:

*création d'un utilisateur en mode éditeur --> enregistrer --> OK

*Modification du même utilisateur en modifiant un des champs de l'adresse (par exemple, région) --> erreur:

userUpdateError
DataIntegrityViolationException

```
could not execute batch; SQL [insert into UserAddress (userid, addressid) values (?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
```

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/issues/481

**Comment by fxprunayre** [comment]
Corrigé dans GN et aligné dans GS

**Comment by taffoureau** [comment]
corrigé.
