### ISSUE TITLE
Distance de résolution / unité

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#158]
L'unité de distance n'est pas proposée dans la vue INSPIRE.

Par ailleurs, une erreur apparaît lorsque le couple valeur/unité est renseigné:

cvc-complex-type.3.2.2: Attribute 'uom' is not allowed to appear in element 'gmd:distance'. (Element: gmd:distance with parent element: gmd:MD_Resolution)

Voici ce qui est stocké dans le XML:

```
<gmd:distance uom="m">
            <gco:Integer>100</gco:Integer>
</gmd:distance>
```

**Comment by fxprunayre** [comment]
Should be 

```
               <gmd:distance>
                  <gco:Distance uom="m">1</gco:Distance>
               </gmd:distance>
```

**Comment by fxprunayre** [comment]
Corrigé https://github.com/geonetwork/core-geonetwork/commit/07df93c54b9c95b0f1f9965f1e264259368f2a26

**Comment by taffoureau** [comment]
Corrigé.
