### ISSUE TITLE
Intégration contenu de l'onglet "Contraintes" dans "Infos Métadonnées"

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#16]
dans les vues avancées...

**Comment by fxprunayre** [comment]
Plutôt contre car dans certains cas, l'onglet métadonnée peut contenir bcp d'information

Je propose plutôt la possibilité d'avoir un 2nd niveau d'onglets (groupés dans un bouton) moins visible (configurable au niveau de la config des vues de l'éditeur) :
![menu](https://drive.google.com/uc?export=download&id=0BwyvNKYgG4ZWTHNwd3N3MWpSdkk)

**Comment by fxprunayre** [comment]
A fermer ?
