### ISSUE TITLE
Valeurs vide dans liste indeterminatePosition

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#160]
cf. copie d'écran. Cela semble se produire lorsqu'on passe en vue complète puis en vue INSPIRE.
![nouvelle image 3](https://cloud.githubusercontent.com/assets/2026724/2818013/1f123d20-cee0-11e3-89cc-68f982ac4bec.png)

**Comment by fxprunayre** [comment]
Corrigé dans https://github.com/geonetwork/core-geonetwork/commit/6e0f54da6e2cc5016a6a00f5a40d7ddbf3b0df34

**Comment by taffoureau** [comment]
Corrigé.
