### ISSUE TITLE
Fixer la valeur de IndeterminatePosition (date de fin) à "maintenant"

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#161]
Fixer la valeur de IndeterminatePosition (date de fin) à "maintenant" dans la liste déroulante proposée : dans la vue INSPIRE, cacher les valeurs après, avant, inconnue.

**Comment by fxprunayre** [comment]
A ne pas faire pour GN.

**Comment by ghost** [comment]
A tester et fermer

**Comment by fxprunayre** [comment]
Il aurait peut être été plus simple d'utiliser l'attribut hideInEditMode pour les 3 options à cacher
https://github.com/geosource-catalogue/core-geonetwork/blob/geosource-3.x/schemas/iso19139/src/main/plugin/iso19139/loc/eng/codelists.xml#L4

Mais bon ça fonctionne.

**Comment by ghost** [comment]
Oui, j'ai vu cela aujourd'hui, ce nouvel attribut. Si j'ai un peu de temps, je vais essayer de revenir dessus dans la journée.

**Comment by taffoureau** [comment]
Je te l'assigne @bmaire ?
