### ISSUE TITLE
Champs date de référence /Boutons supprimer non proposés

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#162]
valable pour toutes les dates proposées dans la catégorie "date de référence".

**Comment by taffoureau** [comment]
As-tu pu regarder? C'est embêtant car des erreurs sont remontées lors de la validation si une des dates n'est pas remplie:
Valeur manquante ou invalide. '' n'est pas une valeur valide pour Date (gco:Date) dont le parent est Date (gmd:date).

**Comment by fxprunayre** [comment]
Qu'est ce que tu fais comme manip exactement ? De mon côté ça fonctionne. Par contre, il ne faudrait pas avoir des éléments avec des dates vides dans le modèle de départ, car si l'éditeur ne la saisie elle va pas être supprimée - il peut la laisser vide et dans ce cas j'ai bien l'erreur.

**Comment by taffoureau** [comment]
OK, j'ai compris. Balises XML à supprimer du modèle donc.
