### ISSUE TITLE
Supprimer le bouton "besoin d'aide" dans le formulaire

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#163]

**Comment by fxprunayre** [comment]
Mettre l'adresse mongeosource.fr

**Comment by fxprunayre** [comment]
Fait https://github.com/geosource-catalogue/core-geonetwork/commit/2d6ae553c3b7d1117c006fa57ed5076a71ad407e

Il faudra mettre à jour la version de la doc sur mon geosource car des sections de la doc ne sont pas les dernières eg. http://geonetwork-opensource.org/manuals/trunk/fra/users/editor/metadata_link/linking.html

**Comment by taffoureau** [comment]
L'adresse est incorrecte : 
http://www.mongeosource.fr/docs/editor/index.html
au lieu de 
http://www.geosource.fr/docs/editor/index.html

Pour info, la doc a été mise à jour.

**Comment by fxprunayre** [comment]
Ce serait bien quelle soit commitée dans GeoNetwork avec une Pull Request https://github.com/geonetwork/core-geonetwork/tree/develop/docs sinon ca va être perdu d'autant plus qu'il y a des travaux en cours sur le sujet (par @jeanpommier et @hardmountain aka Patrizia).

**Comment by fxprunayre** [comment]
Commits reportés dans GN https://github.com/geonetwork/core-geonetwork/commits/stable-develop puis alignement de la branche develop de GS sur la branche stable-develop de GN pour rapatriement des commits.

**Comment by jeanpommier** [comment]
Salut François,

Merci pour les infos.
Ca s'est bien passé le retour ?
@+

Jean

2014-06-09 15:51 GMT+02:00 François Prunayre notifications@github.com:

**Comment by hardmountain** [comment]
Many thanks François!

Il 09/06/2014 15:51, François Prunayre ha scritto:

**Comment by taffoureau** [comment]
Lien corrigé.
