### ISSUE TITLE
Conformité non évaluée / Valeur du gmd:pass

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#166]
Actuellement, une conformité INSPIRE est considérée comme non évaluée lorsqu'aucun élément dataquality/report n'est présent dans le fichier XML.

Dans la dernière version du Technical Guideline, il est demandé d'ajouter un attribut nilReason="Unknown" au niveau de l'élément gmd:pass.
Voir http://inspire.ign.fr/sites/all/files/inspire/md_ir_and_iso_20131029.pdf#page=48

**Comment by fxprunayre** [comment]
Je vais sans doute reprendre ce ticket.

Donc l'interface actuelle ressemble à
- Si non évaluée pas d'information dans le XML

![image](https://cloud.githubusercontent.com/assets/1701393/7235228/0f9a8156-e78d-11e4-8c06-491672784803.png)
- Sinon 

![image](https://cloud.githubusercontent.com/assets/1701393/7234847/6a750536-e78a-11e4-88fd-bcb0d1d0c391.png)

Dans la vue avancée, on peut définir missing de la manière suivante:

![image](https://cloud.githubusercontent.com/assets/1701393/7236539/e5c306c4-e795-11e4-8e98-3664df2a9ee2.png)

@taffoureau : Que faisons nous ?

**Comment by fxprunayre** [comment]
Ajouter un bouton "Ajouter une conformité" avec un rapport de conformité avec missing par défaut.

L'utilisateur ensuite peut définir la conformité à True / False.

Il faut indiquer le cas non évalué.

**Comment by fxprunayre** [comment]
@taffoureau 

Est-ce que ca convient comme rapport par défaut ?

```
                <gmd:report>
                  <gmd:DQ_DomainConsistency>
                    <gmd:result>
                      <gmd:DQ_ConformanceResult>
                        <gmd:specification>
                          <gmd:CI_Citation>
                            <gmd:title>
                              <gco:CharacterString/>
                            </gmd:title>
                            <gmd:date>
                              <gmd:CI_Date>
                                <gmd:date>
                                  <gco:Date/>
                                </gmd:date>
                                <gmd:dateType>
                                  <gmd:CI_DateTypeCode
                                    codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/ML_gmxCodelists.xml#CI_DateTypeCode"
                                    codeListValue="publication"/>
                                </gmd:dateType>
                              </gmd:CI_Date>
                            </gmd:date>
                          </gmd:CI_Citation>
                        </gmd:specification>
                        <gmd:explanation>
                          <gco:CharacterString/>
                        </gmd:explanation>
                        <gmd:pass gco:nilReason="unknown">
                          <gco:Boolean/>
                        </gmd:pass>
                      </gmd:DQ_ConformanceResult>
                    </gmd:result>
                  </gmd:DQ_DomainConsistency>
                </gmd:report>
```

Ou faut-il remplir d'autres champs avec des valeurs par défaut ?

**Comment by fxprunayre** [comment]
Appliqué à GN Cf. https://github.com/geonetwork/core-geonetwork/pull/961

A tester.

**Comment by taffoureau** [comment]
C'est OK pour la proposition, c'est bien conforme à http://cnig.gouv.fr/wp-content/uploads/2015/01/MD_IR_and_ISO_20131029.pdf#page=48

Mais je ne vois pas de différence après redéploiement.

**Comment by fxprunayre** [comment]
> Mais je ne vois pas de différence après redéploiement.

C'est à dire ? tu n'as pas 
![image](https://cloud.githubusercontent.com/assets/1701393/7353450/f118c03a-ed13-11e4-9ea8-9c2189d503ac.png)

**Comment by taffoureau** [comment]
Ben non...

**Comment by fxprunayre** [comment]
Tu utilises un datadir spécifique ? si oui et que les schémas sont dedans, mettre à jour les schémas.

**Comment by taffoureau** [comment]
OK après redéploiement ce matin
