### ISSUE TITLE
Gestion des Annuaires

### ISSUE THREAD

**Issue by TERMEPhilippe** [geosource-catalogue/core-geonetwork#167]
Actuellement, impossible de créer un nouveau Element de contact sauf par ajout d'un fragment xml.
Il faudrait que l'ajout d'un contact s'appuie sur le contact modèle Organisation : Nom mais NE LE REMPLACE PAS !
ps( en version 9.2 possiblité de dupliquer le contact que l'on ne retrouve pas ici)

**Comment by taffoureau** [comment]
Il est possible de créer un nouveau contact dans l'annuaire en cliquant sur dupliquer.

**Comment by TERMEPhilippe** [comment]
Vu, l'ergonomie pourrait être revue pour être cohérente avec les autres fonctions d'ajouts d'items de Geosource 
- une icône [+] ajoute un nouvel élément avec sections : exemple Nouveau contact 
  ![nouveau contact](https://cloud.githubusercontent.com/assets/6795250/3270271/fc4877a4-f2fd-11e3-80ce-5e18e0b70c7b.jpeg)

**Comment by fxprunayre** [comment]
Côté ergonomie, demande d'évol similaire https://github.com/geonetwork/core-geonetwork/issues/404

Si le ticket concerne "dupliquer le contact que l'on ne retrouve pas ici", on peut fermer ?
