### ISSUE TITLE
Logo Organisation par upload d'image dans l'éditeur

### ISSUE THREAD

**Issue by TERMEPhilippe** [geosource-catalogue/core-geonetwork#168]
Pourrait-on offrir la possibilité d'ajouter un logo "Producteur" dans la gestion des Annuaires par import d'un fichier image.
La balise
 gmd:contactInstructions
<gmx:FileName src="URL du logo">Logo/gmx:FileName
/gmd:contactInstructions 

permet cela il me semble

**Comment by taffoureau** [comment]
Un logo peut être ajouté dans l'annuaire, mais il faut d'abord l'importer dans la partie "gestion des logos" dans l'admin.

**Comment by TERMEPhilippe** [comment]
bonjour;
j'ai eu beau explorer la gestion des annuaires, je n'ai pas trouvé 
l'endroit pour associer un logo (disponible dans la banque de logo de 
Geosource) à un producteur.
Pourriez-vous m'apporter les précisions de cheminement nécessaires ?

Merci

*Philippe TERME
*Administrateur des données
Administrateur général de Sigloire

*DREAL Pays de la Loire
*Service Connaissance des Territoires
Division Systèmes d'Information sur les Territoires
02 72 74 74 83
/5 rue Françoise Giroud
CS 16326
44263 NANTES Cedex 2
/

Le 09/06/2014 12:12, "> taffoureau (par Internet, dépôt 
bounces+848413-dba8-philippe.terme=developpement-durable.gouv.fr@sgmail.github.com)" 
a écrit :

**Comment by taffoureau** [comment]
Il faut procéder de la sorte:
1) importer un logo dans Paramètres>logo
2) Aller dans Thésaurus>Annuaires
puis modifier un contact, au niveau de l'élément "instructions sur le contact", sélectionner "nom du fichier", puis sélectionner le logo importé en 1)

**Comment by TERMEPhilippe** [comment]
ok ça marche en V2.11.
Petit problème d'affichage du champ Texte en V2.9.2 selon les navigateurs (ok avec Chrome 35, nok avec Firefox 24)
