### ISSUE TITLE
Ajout d'un contact dans la fiche de métadonnées

### ISSUE THREAD

**Issue by TERMEPhilippe** [geosource-catalogue/core-geonetwork#169]
Suite à l'ajout d'un contact de l'annuaire, seuls les champs organisation, email et Role sont visibles dans la fiche de métadonnées (vue INSPIRE) alors que d'autres champs existent, par exemple nom ou adresse :
![contact](https://cloud.githubusercontent.com/assets/6795250/3162681/b5962676-eb37-11e3-95de-a71183befe3d.jpeg)

Il faudrait que tous les champs apparaissent

**Comment by taffoureau** [comment]
C'est normal, les autres champs ne sont pas des champs INSPIRE, ils ne sont donc pas disponibles dans cette vue.
