### ISSUE TITLE
Batch replacer

### ISSUE THREAD

**Issue by TERMEPhilippe** [geosource-catalogue/core-geonetwork#170]
La tentative d'utilisation du batch Replacer s'est soldé par un echec (Process Error)
![batcht](https://cloud.githubusercontent.com/assets/6795250/3162752/81901eda-eb38-11e3-9425-bf90b9eca455.jpeg)

**Comment by taffoureau** [comment]
Pouvez-vous svp indiquer votre configuration et envoyer le contenu de votre catalogue (export zip)?

**Comment by taffoureau** [comment]
Attention, il y a deux éléments "contact" dans DataIdentification:
CI_Citation>...
et
PointofContact>... ==> responsable de la ressource INSPIRE
