### ISSUE TITLE
Pb d'accès à la page d'import de mtds en mode multisite

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#171]
Lorsque je clique dans administration sur Importer/exporter j'ai une erreur 404. Il semble qu'il essaie de basculer sur le noeud par défaut (srv).

http://geosourcemulti.brgm-rec.fr/geosource/srv/fre/node-change-warning?oldUserName=admin&redirectedFrom=%2Fgeosource%2Fsrv%2Ffre%2Ffind&oldNodeId=1000

**Comment by fxprunayre** [comment]
Corrigé dans le nouvel installer.
