### ISSUE TITLE
Génération d'un identifiant de la ressource / pb d'accès aux fiches XML

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#172]
Suite à la génération d'un identifiant de la ressource, l'URL générée ne permet pas d'accéder à la fiche XML :
Exemple : http://geosourcedemo.brgm.fr/geosource/b7d1218c-f9e8-40a0-a6fc-021f9905c756
renvoie :You do not have the correct permissions to access the following service "/geosource/b7d1218c-f9e8-40a0-a6fc-021f9905c756"

Pourtant la fiche est bien publiée.

**Comment by fxprunayre** [comment]
On va peut être mettre l'URL du GetRecordById si l'identifiant doit être une URL ;)

**Comment by fxprunayre** [comment]
Du coup, en mode multinode, l'identifiant n'est pas valide avec la règle actuelle
http://geosourcedemo.brgm.fr/geosource/b7d1218c-f9e8-40a0-a6fc-021f9905c756
devrait être 
http://geosourcedemo.brgm.fr/geosource/{{nodeid}}/b7d1218c-f9e8-40a0-a6fc-021f9905c756
?

Est-ce que cela doit renvoyer la fiche en HTML ou en XML ?

Pour info en ISO19115-1, l'élément metadata contient une balise metadatalinkage qui permet dans la fiche de faire un lien vers la fiche dans le catalogue d'origine (si c'est l'objectif).

**Comment by fxprunayre** [comment]
Règle de redirection corrigée https://github.com/geonetwork/core-geonetwork/issues/551 mais ne fonctionnera qu'en mode node unique et redirige vers une page HTML (comportement par défaut dans GeoNetwork).

**Comment by taffoureau** [comment]
OK, prévoir une évolution pour une version prochaine...

**Comment by fxprunayre** [comment]
> OK, prévoir une évolution pour une version prochaine...

Ok, mais du coup, comment faire en module multinode ? Si l'URL ne contient pas l'info sur le noeud, il faudra l'identifier ? c'est à dire indexer pour chaque noeud la liste des UUIDS des fiches ?

**Comment by taffoureau** [comment]
Il me semble que c’était ce qui était prévu au départ : https://github.com/geosource-catalogue/core-geonetwork/issues/5 ?

Par contre, il faudra bien pointer vers la fiche XML.
