### ISSUE TITLE
processus en batch / batch replacer

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#173]
Dans Géosource démo (geosourcedemo.brgm.fr/geosource/) j'ai une option qui est disponible dans la partie "processus en batch" : "batch replacer"

N'apparaît pas dans la version du war datant du 12/06...

**Comment by fxprunayre** [comment]
A priori l'installer du 12 repose sur
https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web-ui/src/main/resources/catalog/config/batch-process-cfg.json
qui est le même que 
http://geosourcedemo.brgm.fr/geosource/catalog/config/batch-process-cfg.json

Je ne reproduis pas en local.

**Comment by taffoureau** [comment]
Problème lié au multinode ?

**Comment by fxprunayre** [comment]
> Problème lié au multinode ?

De mon côté ça fonctionne en multinode sans pb. Des erreurs JS ?

**Comment by taffoureau** [comment]
Corrigé. J'avais donc un seul noeud de configuré : 1000.xml avec <property value="false" name="defaultNode"/>

**Comment by taffoureau** [comment]
Corrigé.
