### ISSUE TITLE
Pb déconnexion en multinode

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#174]
Renvoie avec une erreur 404, vers le noeud par défaut:
http://geosourcemulti.brgm-rec.fr/geosource/srv/fre/find?node=srv

**Comment by fxprunayre** [comment]
Et donc aucun noeud n'est lancé ? y a-t-il des noeuds configurés dans WEB-INF/config-node/*.xml ?

**Comment by taffoureau** [comment]
Les tests sont effectués sur le 1000. C’est le seul configuré.

**Comment by fxprunayre** [comment]
> Les tests sont effectués sur le 1000. C’est le seul configuré.

Donc c'est normal que le noeud "srv" ne réponde pas s'il n'est pas configuré.

**Comment by taffoureau** [comment]
D’accord pour l’erreur 404 mais ne devrait-il pas rester sur le nœud de départ (1000) ?

**Comment by fxprunayre** [comment]
> D’accord pour l’erreur 404 mais ne devrait-il pas rester sur le nœud de départ (1000) ?

Je sais pas quel est le scénario ?

Si on accède à http://geosourcemulti.brgm-rec.fr/geosource/srv/fre/find?node=srv et que l'adresse n'existe pas il retourne 404. il va pas rediriger vers le noeud 1000.

**Comment by fxprunayre** [comment]
> Je sais pas quel est le scénario ?

Sur logout donc.

**Comment by taffoureau** [comment]
Corrigé.
