### ISSUE TITLE
Calcul automatique de topicCategory à partir du thème INSPIRE saisi

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#175]
Ne fonctionne pas. N'est même pas proposé dans l'outil de suggestions.

**Comment by fxprunayre** [comment]
Par ailleurs, le fait de maintenant contraindre les thèmes INSPIRE à un seul, lors du mapping un seul thème est ajouté (un peu en contradiction avec http://georezo.net/wiki/main/donnees/inspire/aide_a_la_saisie_des_metadonnees_inspire#categorie_thematique).

**Comment by taffoureau** [comment]
Corrigé.
