### ISSUE TITLE
Publication d'une ressource en ligne en WMS, ...

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#176]
Action en édition: Ajouter une ressource en ligne, puis clic sur ajouter un lien ou un fichier --> l'option publier en WMS, WFS ou WCS est proposé.

Par défaut, ne devrait pas être proposé dans Géosource.

**Comment by fxprunayre** [comment]
> Par défaut, ne devrait pas être proposé dans Géosource.

Pourquoi ? Des utilisateurs comme le GrandLyon l'utilisent.

De plus l'option est proposée, mais tant qu'il n'y a pas de serveurs cartographiques configurés dans l'admin aucune action particulière ne peut être réalisée (cf. http://localhost:8080/geonetwork/srv/fre/admin.console#/settings/mapservers).

Une amélioration possible serait d'indiquer par un message qu'aucun serveur n'est configuré et que donc la géopublication est impossible.

**Comment by taffoureau** [comment]
en effet il faudrait l'indiquer dans ce cas.

**Comment by fxprunayre** [comment]
Fait dans le cadre de #186 - même si c'était assigné à Benoit (sur github il m'était assigné !).
Si aucun serveur configuré, le geopublisher ne s'affiche pas.
