### ISSUE TITLE
Nom de la table attributaire non modifiable

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#177]
En édition d'un catalogue attributaire, le champ n'est pas modifiable. Apparaît pourtant lorsqu'il existe dans le fichier XML (cf modèle ISO 19110).

```
 <gfc:featureType>
      <gfc:FC_FeatureType>
         <gfc:typeName>
            <gco:LocalName>-- Nom de la table attributaire --</gco:LocalName>
         </gfc:typeName>
```

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/issues/555

**Comment by fxprunayre** [comment]
Corrigé
