### ISSUE TITLE
Présence d'un groupe "undefined" dans la recherche

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#178]
Dans la recherche avancée, critère "groupe", j'ai:
undefined
Invité
Public
Privé

Testé sur un catalogue vierge (base vide).

**Comment by fxprunayre** [comment]
Que retourne http://localhost:8080/geonetwork/srv/fre/xml.info?type=groups ?

Devrait être :

```
<info>
<group>
<group id="-1">
<name>GUEST</name>
<description>self-registered users</description>
<label>
<fre>Invité</fre>
<eng>Guest</eng>
</label>
</group>
<group id="1">
<name>all</name>
<label>
<fre>Public</fre>
<eng>All</eng>
</label>
</group>
<group id="2">
<name>private</name>
<label>
<fre>Privé</fre>
<eng>Internal</eng>
</label>
</group>
</group>
<env>
<baseURL>/geonetwork</baseURL>
<node>srv</node>
</env>
</info>
```

**Comment by taffoureau** [comment]
http://geosourcemulti.brgm-rec.fr/geosource/1000/srv/fre/xml.info?type=groups renvoie une erreur : You do not have the correct permissions to access the following service "/geosource/1000/srv/fre/xml.info?type=groups"

**Comment by fxprunayre** [comment]
Ok plus visible sous FF. GeoNetwork ref https://github.com/geonetwork/core-geonetwork/issues/556

**Comment by fxprunayre** [comment]
Corrigé dans GN et GS.

**Comment by taffoureau** [comment]
Corrigé après redéploiement du war.
