### ISSUE TITLE
Encodage de la fonctionnalité Batch replace

### ISSUE THREAD

**Issue by TERMEPhilippe** [geosource-catalogue/core-geonetwork#179]
Petit problème d'encodage des  accents : ce qui est demandé 
![batch_replace_organisation](https://cloud.githubusercontent.com/assets/6795250/3270428/e05d1516-f2ff-11e3-9aa9-09a3ebe342fa.jpeg)

Le résultat 
![rsultat_batch](https://cloud.githubusercontent.com/assets/6795250/3270419/cea5a1ee-f2ff-11e3-8884-98273fd4af78.jpeg)

**Comment by fxprunayre** [comment]
Fonctionne sur une version standard 

![image](https://cloud.githubusercontent.com/assets/1701393/3270649/b2b28d64-f302-11e3-83cd-92a59714d542.png)

Sans doute problème d'install sous tomcat ?

**Comment by TERMEPhilippe** [comment]
Testé sous version demo de geousource.fr

**Comment by fxprunayre** [comment]
Cf. http://tomcat.apache.org/tomcat-7.0-doc/config/ajp.html valable pour AJP et HTTP:

```
URIEncoding 
This specifies the character encoding used to decode the URI bytes, 
after %xx decoding the URL. If not specified, ISO-8859-1 will be used.
```

**Comment by taffoureau** [comment]
Ca fonctionne sur geosource démo après ajout du paramètre file.encoding.
