### ISSUE TITLE
Génération d'un identifiant de la ressource / pb d'accès aux fiches

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#180]
cf. discussion https://github.com/geosource-catalogue/core-geonetwork/issues/172

Le lien suivant devrait permettre d'accéder à la fiche HTML correspondante, ce qui n'est pas le cas:
http://geosourcedemo.brgm.fr/geosource/d052237a-9fca-4590-926a-72b268be194e

![fireshot screen capture 045 - gosource de dmo - geosourcedemo_brgm_fr_geosource_srv_eng_service-not-allowed_referer _geosource_d052237a-9fca-4590-926a-72b268be194e](https://cloud.githubusercontent.com/assets/2026724/3270868/d76aff0e-f304-11e3-928b-283ec4fad899.png)

**Comment by fxprunayre** [comment]
Doublon cf #5
