### ISSUE TITLE
Autres actions/ massive replacements

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#181]
Suite au déploiement du war datant du 13/06 14:06

J'ai un "massive replacements" qui apparaît dans la page de résultats, dans autres actions sur la sélection. Cela renvoie vers une page en anglais correspondant au "batch replacer" disponible en admin (dans "outils").

**Comment by fxprunayre** [comment]
Corrigé à tester

**Comment by taffoureau** [comment]
Corrigé.
