### ISSUE TITLE
autocomplétion contacts sous windows

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#182]
Testé sur une installation windows:
autocomplétion au niveau du champ "nom de l'organisation" avec une seule entrée dans l'annuaire : "Organisation responsable"
On tape "org" --> l'autocomplétion remonte deux résultats vides
Puis on efface les caractères --> c'est le titre des fiches de métadonnées contenues dans le catalogue qui remontent!

**Comment by fxprunayre** [comment]
A priori corrigé, installer le nouvel installer de ce matin
https://github.com/geosource-catalogue/core-geonetwork/commit/ed9b6794bc1040345ef3e5e5e8617804d2af9950

**Comment by taffoureau** [comment]
OK.
