### ISSUE TITLE
Lien vers la doc non mis à jour dans l'installation windows.

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#183]
lien "besoin d'aide" dans l'édition

**Comment by fxprunayre** [comment]
Le lien pointe vers quoi sous windows ?

Cf. https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js#L46

En lien avec #163

**Comment by taffoureau** [comment]
Ah ben si c'est bon finalement (probleme possible de cache?)
