### ISSUE TITLE
icône crayon dans l'admin/retour au catalogue

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#185]
Lorsque j'accède à l'interface d'édition depuis la page d'administration (icône représentant un crayon) il est impossible ensuite de revenir à la page de recherche

**Comment by fxprunayre** [comment]
Ouvrir dans un nouvel onglet

**Comment by fxprunayre** [comment]
https://github.com/geonetwork/core-geonetwork/commit/91eb17da0134a6dc45ff8ce7fe002fb3d4f9d07b

**Comment by taffoureau** [comment]
OK.
