### ISSUE TITLE
[2.11] Bug IE 11 sur MapExtent

### ISSUE THREAD

**Issue by pchevallot** [geosource-catalogue/core-geonetwork#186]
Impossible de dessiner une emprise sous IE (testé uniquement sous IE 11).

**Comment by fxprunayre** [comment]
Reproductible sous IE10. Ok quand on sélectionne une région.

**Comment by fxprunayre** [comment]
GeoNetwork ref: https://github.com/geonetwork/core-geonetwork/issues/662
Mise à jour de OL à la version 3.0.0 + corrections diverses :
- liés au changement d'API
- Display geopublisher action only if mapservers configured
- Thumbnail generation:
  - report error (grabbed from HTML error page)
  - zoom to layer extent
  - reload properly online source and extent changes
  - add loading indicator while generating thumbnail
