### ISSUE TITLE
Liens xlinks erronés

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#19]
Dans le cas de l'utilisation de thésaurus de type "place", les xlinks générés sont de cette forme et ne peuvent pas être résolus : 

http://geosourcetest.brgm-rec.fr:80/geosource/srv/fre/xml.keyword.get?thesaurus=external.place.CommunesFR&amp;amp;id=http://geonetwork-opensource.org/adminstrativeAreaFr%23COM_73065&amp;amp;multiple=false

par ailleurs, les informations retournées ne sont pas sous la forme XML.

Dans le cas d'autres thésaurus (inspire-theme, GEMET), les xlinks sont résolus. Par contre, ceux stockés dans la balise "identifier" ne le sont pas (le host est incorrect) : http://localhost:8080/geosource/srv/en/thesaurus.download?ref=external.theme.gemet

**Comment by fxprunayre** [comment]
> Par contre, ceux stockés dans la balise "identifier" ne le sont pas (le host est incorrect) 

Les settings sont configurées dans administration > config du système ?

En remplaçant localhost par 127.0.0.1 ca marche de mon côté:

![image](https://f.cloud.github.com/assets/1701393/1973082/9161d882-8353-11e3-9c41-f39dae894c1f.png)

> par ailleurs, les informations retournées ne sont pas sous la forme XML.

Elles sont sous quelle forme ?
Des erreurs dans les logs ?
Dans l'URL il faut remplacer les "&amp;amp;" par "&" si tu veux tester le lien qui est dans une fiche XML.

![image](https://f.cloud.github.com/assets/1701393/1973102/e509afb4-8353-11e3-81fb-be3fca312fa4.png)

**Comment by fxprunayre** [comment]
Tester: 
- http://geosourcetest.brgm-rec.fr:80/geosource/srv/fre/xml.keyword.get?thesaurus=external.place.CommunesFR&amp;amp;id=http://geonetwork-opensource.org/adminstrativeAreaFr%23COM_73065&amp;amp;multiple=false = page d'erreur
- http://geosourcetest.brgm-rec.fr:80/geosource/srv/fre/xml.keyword.get?thesaurus=external.place.CommunesFR&id=http://geonetwork-opensource.org/adminstrativeAreaFr%23COM_73065&multiple=false = XML

**Comment by fxprunayre** [comment]
@taffoureau Peux-tu fournir une fiche Prodige posant le pb ? merci

**Comment by fxprunayre** [comment]
Test ok avec https://gist.github.com/fxprunayre/8662272

**Comment by taffoureau** [comment]
OK en version 2.9.2.
