### ISSUE TITLE
Impression : correction

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#190]
Le menu imprimer pour les fiches en HTML ne fonctionne plus.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/commit/440f44c4f6e978f354223b8a91b8e9ca9c0dd470 + https://github.com/geonetwork/core-geonetwork/commit/823ba146923d58fb09cb9e40b0841a5a33820282

**Comment by taffoureau** [comment]
Testé sur un noeud autre sur srv.

L'application essaie de se connecter à http://geosourcetest.brgm-rec.fr/geosource/apps/search/print.html?uuid=ee3ee015-6a97-438f-8a56-7d2007487566&currTab=view-simple&hl=fre puis me redirige vers la page n ode-change-warning.

**Comment by fxprunayre** [comment]
Reproduit. En cours de correction https://github.com/geonetwork/core-geonetwork/issues/705

**Comment by fxprunayre** [comment]
Corrigé. A redéployer & tester
