### ISSUE TITLE
MonGeoSource / Correction erreur de build

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#193]
Cf. 
https://github.com/geosource-catalogue/core-geonetwork/commit/072eaf7e2e5724ca59296d075ed5c35ca610147e#diff-eef89535a29b4a95a42d9de83cb53681R863

**Comment by fxprunayre** [comment]
Fixed https://github.com/geosource-catalogue/core-geonetwork/commit/9e6cc3be6322108c733869c50dbc4f829cd3409b. En cours de test avec @UlrichBrgm

**Comment by UlrichBrgm** [comment]
Ok now. thx u
