### ISSUE TITLE
Administration / Configuration du niveau de log

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#195]
Dans l'administration, ajouter un onglet de configuration et consultation des logs.

3 fichiers de configuration de log4j sont créés :
- PROD : Niveau WARNING
- TEST : Niveau DEBUG sur jeeves
- DEV : Niveau DEBUG sur ... 

Il serait souhaitable que n fichiers de configuration puissent être pris en compte : log4j_prod.xml, log4j_test.xml, log4j_dev.xml (voire log4j_dev_search.xml, ...).

La page permet :
- Choix du niveau de log (liste de choix en fonction des fichiers log4j*.xml)
- Consulter les dernières mise à jour du fichier de log
- Télécharger le fichier de log.

A réaliser dans une branche spécifique admin-config-logger dans l'organisation geosource-catalogue afin de faire un proposal (https://github.com/geonetwork/core-geonetwork/wiki/Geonetwork-Change-Proposals) et un PR côté GeoNetwork.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/854

**Comment by fxprunayre** [comment]
Une PR faite mais :
- introduction de bugs bloquant dans GN (corrigés)
- commentaire dans la PR sans réponse https://github.com/geonetwork/core-geonetwork/pull/854 - cf description dans le ticket
  - renommer log4j-jeeves (car Jeeves va être supprimé) - on avait dit PROD/TEST/DEV ?
  - "Il serait souhaitable que n fichiers de configuration puissent être pris en compte"
  - on a pas "Consulter les dernières mise à jour du fichier de log", "Télécharger le fichier de log." à partir de la page http://apps.titellus.net/geonetwork/srv/eng/admin.console#/dashboard/information

Donc à compléter je pense.

**Comment by fxprunayre** [comment]
Après tests complémentaires avec Benoit, le changement est bien pris en compte mais plus ou moins visible selon ce qui est choisi. En consoleAppender, mettre le seuil sur ALL https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/classes/log4j-dev.xml#L9

Pour les fichiers par défaut, je propose:
- log4j.xml: tout à WARN comme actuellement
- log4j-dev.xml: pour le moment on peut garder l'actuel
- log4j-jeeves.xml à remplacer par log4j-index.xml: avec geonetwork.index geonetwork.lucene & geonetwork.lucene.tracking à DEBUG
- log4j-search.xml : avec geonetwork.search à DEBUG

**Comment by ghost** [comment]
CF https://github.com/geonetwork/core-geonetwork/pull/951

**Comment by fxprunayre** [comment]
PR appliquée à GN avec quelques adaptations.

Il reste un problème sur http://localhost:8080/geosource/srv/eng/log/activity et l'export ZIP qui retourne un NPE

```
2015-04-20 15:58:23,410 DEBUG [jeeves.config.springutil.JeevesDispatcherServlet] - Could not complete request
java.lang.NullPointerException
    at java.io.File.<init>(File.java:277)
    at org.fao.geonet.monitor.service.LogConfig.activity(LogConfig.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
```

J'ai l'impression que ca se produit quand on démarre une première fois l'appli - eg. install GS depuis l'installer, mvn clean install - peut être car il n'y pas encore de fichier de log ?

**Comment by fxprunayre** [comment]
Ce serait bien de le corriger avant la sortie de GN (prévue mardi) et celle de GS (également mardi ?).

**Comment by taffoureau** [comment]
Après redéploiement ce matin, j'obtiens une errreur lorsque je tente de modifier la configuration (dans paramètre > désactiver la carte) : file log4J not found ....

**Comment by fxprunayre** [comment]
> Also admin.logfile.list?_content_type=json return empty list when started from Intellij (looking in target/webapp/WEB-INF/classes instead of target/geonetwork) but is fine when starting it with jetty:run. Probably a configuration issue on the IDE.

Fait dans https://github.com/geonetwork/core-geonetwork/issues/965. Il reste le pb de NPE.

**Comment by fxprunayre** [comment]
> Il reste un problème sur http://localhost:8080/geosource/srv/eng/log/activity et l'export ZIP qui retourne un NPE

GN ref https://github.com/geonetwork/core-geonetwork/issues/966. En cours de correction de mon côté.

**Comment by fxprunayre** [comment]
A tester. Installer mis à jour.

**Comment by taffoureau** [comment]
La page permet :

```
Choix du niveau de log (liste de choix en fonction des fichiers log4j*.xml) => OK
Consulter les dernières mise à jour du fichier de log => c'est où dans l'interface?
Télécharger le fichier de log. => c'est où dans l'interface?
```

**Comment by fxprunayre** [comment]
Voir les captures d'écran https://github.com/geonetwork/core-geonetwork/pull/951

http://localhost:8080/geonetwork/srv/fre/admin.console#/dashboard

**Comment by taffoureau** [comment]
C'est OK pour moi.

Juste une question: à quoi sert la liste déroulante dans la page "paramètres" qui contient les valeurs production, développement, intégration ?
![niv_logs](https://cloud.githubusercontent.com/assets/2026724/7370846/1f4b4e06-edbd-11e4-9aee-cbe12ed9860c.png)

**Comment by fxprunayre** [comment]
Si en dev, il ne va pas utiliser certain cache dans l'application (eg. pour les formatters, les translators).
