### ISSUE TITLE
Moissonnage / Statistique et rapport

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#196]
Dans la console d’administration, dans la partie Admin > Moissonnage, un onglet "rapport" est ajouté :
- Nom
- Date de dernier moissonnage
- Type de moissonneur (+ version (ex : WMS 1.3.0) pour Service OGC)
- Url du service
- Nombre de fiches moissonnées

Mettre en place un export CSV (à voir si les mécanismes présents dans les rapports peuvent être réutilisés http://localhost:8080/geonetwork/srv/eng/admin.console#/reports).

A faire dans une branche spécifique pour PR et intégration dans GeoNetwork.

**Comment by fxprunayre** [comment]
Fait. A tester.

**Comment by taffoureau** [comment]
OK pour la liste dans l'IHM, à ceci près qu'il y a un léger décalage entre le titre des colonnes et le contenu du tableau (eg dernier lancement).

Lorsque je clique sur le bouton "exporter en CSV", il s'affiche "undefined" et rien ne se passe.
![nouvelle image](https://cloud.githubusercontent.com/assets/2026724/7158864/49253d2a-e37e-11e4-989d-63abee02aa2b.png)

**Comment by fxprunayre** [comment]
Les libellés des onglets ne sont pas tip top
https://github.com/geonetwork/core-geonetwork/blob/develop/web-ui/src/main/resources/catalog/js/admin/HarvestController.js#L32
- "report" devrait être "Rapport" - et la clé report devrait peut être être spécifique à cette page car on peut imaginer utiliser "report" ailleurs dans l'admin sans lien avec le moissonnage.
- Majuscule pour noeuds distant - voire renommer en "Configuration" 

@taffoureau  un avis ?

**Comment by ghost** [comment]
@taffoureau, j'attends ton avis pour la correction des libellés.

**Comment by fxprunayre** [comment]
Mettre l'icône du bouton harvesting pour le premier onglet:
![image](https://cloud.githubusercontent.com/assets/1701393/7255001/c4ba127c-e846-11e4-809f-37d8e478bccf.png)

**Comment by fxprunayre** [comment]
Les onglets ne marchent plus https://github.com/geonetwork/core-geonetwork/pull/959/files#r29037907. En cours de correction.

**Comment by fxprunayre** [comment]
A tester, installer mis à jour.

**Comment by atellezarenas** [comment]
Test de la fonctionnalité sur BD 1GG (liste longue).
- performances OK
- je ne vois pas par quoi les lignes sont triées? Cela devrait être triées, par ordre alphabétique ou par "dernier lancement".
- le bouton "export CSV" ne fonctionne pas (comme dit précédemment, "undefined").
  => Sachant que cet export ne me semble pas "bloquant" si ça ne marche pas. Je préfèrerais avoir le choix sur les tris du tableaux, tant pis pour l'export (ce tableau peut se copier coller en excel, ça rend inutile l'export CSV).

**Comment by taffoureau** [comment]
le bouton "export CSV" ne fonctionne pas (comme dit précédemment, "undefined") => @fxprunayre, @bmaire avez-vous reproduit cette anomalie ?

**Comment by taffoureau** [comment]
le "undefined" apparaît sous FFX.

Sous Chrome on a ça:
![harvest_report](https://cloud.githubusercontent.com/assets/2026724/7372170/a3e6d60a-edc5-11e4-80a9-10720b363220.png)

**Comment by ghost** [comment]
Corrigé sous firefox eee6fc096fe5685b804679023964dbf2f35da0b6
