### ISSUE TITLE
Moissonnage / Amélioration des performances

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#197]
Avec OneGeology, le chargement de la liste des points de moissonnages est longue (1min~ avec 160 configs).

2 options :
1) Gérer la configuration en 2 temps :
- récupération de la liste des configs
- récupération de la config d'un noeud

2) Option 1 mais avec modification de la structure de la table HarvesterSettings.
- Changer la structure arborescente par une structure simple du genre :
  - name
  - type
  - url
  - config (XML)
- Dans ce cas, prévoir migration de l'ancienne table vers la nouvelle

HarvesterManagerImpl abuse d'XSLT ici
https://github.com/geonetwork/core-geonetwork/blob/develop/harvesters/src/main/java/org/fao/geonet/kernel/harvest/HarvestManagerImpl.java#L109 et là https://github.com/geonetwork/core-geonetwork/blob/develop/harvesters/src/main/java/org/fao/geonet/kernel/harvest/HarvestManagerImpl.java#L130 : supprimer ces étapes amélioreraient les perfs (tout en java ou une seule transfo XSL) mais pas une par noeuds + une pour le trie !

Faire option 1 avec simplification XSLT

A faire dans une branche spécifique pour PR et intégration dans GeoNetwork (peut être la même PR que #196).

**Comment by fxprunayre** [comment]
GN PR https://github.com/geonetwork/core-geonetwork/pull/838

**Comment by fxprunayre** [comment]
PR appliquée à GN. A tester une fois l'alignement GN/GS fait.

**Comment by fxprunayre** [comment]
Fix en lien avec la PR https://github.com/geonetwork/core-geonetwork/commit/d10fa3320b042896cb16a6effb3eb33923d22e05

**Comment by fxprunayre** [comment]
Fait par @bmaire  pour l'option 1 sans modif au niveau XSLT (dommage - ca aurait fait un peu de ménage). Il y a eu un bug repéré dans la PR - corrigé par Maria.

Dispo dans GS3 (et site de démo sur titellus.net). A tester pour @taffoureau

**Comment by atellezarenas** [comment]
Testé sur la base de données 1GG. Performances OK. Recherche fonctionne. Affichage aussi. Fonctionne très bien lorsque l'on créé un nouveau point de moissonnage, la liste est bien remise à jour. C'est ok pour moi.
