### ISSUE TITLE
Authentification / Corriger utilisation du LDAP

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#199]
Cf. https://github.com/geonetwork/core-geonetwork/issues/440

**Comment by taffoureau** [comment]
A tester dans la 2.11.2

**Comment by fxprunayre** [comment]
Pour info, testé avec succès par Landry sur GN (https://github.com/geonetwork/core-geonetwork/issues/440#issuecomment-68256894)
