### ISSUE TITLE
Saisie des emprises - sélection par région

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#20]
Impossible d'accéder aux régions dans la liste déroulante pour la sélection des emprises géo.

Testé sous Firefox et Chrome.

**Comment by fxprunayre** [comment]
Fixed in https://github.com/geonetwork/core-geonetwork/commit/476bad2e4d3562384d3dd953457c2149218a3c97

**Comment by taffoureau** [comment]
Je ne constate pas d'amélioration suite à la livraison du 24/01.

**Comment by fxprunayre** [comment]
Donc, en 2.9.1 ca ne fonctionne pas (http://geosourcedemo.brgm.fr/geosource/apps/search/?)

En 2.9.2, ca fonctionne si on a le thésaurus des régions (pays du monde de GN) installé. Je vais tenter la config pour **un** thésaurus. @taffoureau  Lequel ? département ?

En 2.11.0, on analysera si c'est simple de permettre le choix du thésaurus (region, dep, commune).

**Comment by taffoureau** [comment]
Plutôt région ?

De : François Prunayre [mailto:notifications@github.com]
Envoyé : mercredi 29 janvier 2014 10:27
À : geosource-catalogue/core-geonetwork
Cc : Taffoureau Etienne
Objet : Re: [core-geonetwork] Saisie des emprises - sélection par région (#20)

Donc, en 2.9.1 ca ne fonctionne pas (http://geosourcedemo.brgm.fr/geosource/apps/search/?)

En 2.9.2, ca fonctionne si on a le thésaurus des régions (pays du monde de GN) installé. Je vais tenter la config pour un thésaurus. @taffoureauhttps://github.com/taffoureau Lequel ? département ?

En 2.11.0, on analysera si c'est simple de permettre le choix du thésaurus (region, dep, commune).

—
Reply to this email directly or view it on GitHubhttps://github.com/geosource-catalogue/core-geonetwork/issues/20#issuecomment-33568288.
P Pensez à l'environnement avant d'imprimer ce message
       Think Environment before printing

Le contenu de ce mél et de ses pièces jointes est destiné à l'usage exclusif du (des) destinataire(s) désigné(s) comme tel(s).
En cas de réception par erreur, le signaler à son expéditeur et ne pas en divulguer le contenu.
L'absence de virus a été vérifiée à l'émission, il convient néanmoins de s'assurer de l'absence de contamination à sa réception.

The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only.
If you have received this email in error please notify the system manager or  the sender immediately and do not disclose the contents to
anyone or make copies.
This email was scanned for viruses, vandals and malicious content.

**Comment by fxprunayre** [comment]
Utilisation des departements dans la liste https://github.com/geosource-catalogue/core-geonetwork/commit/a28546803cec772a2c789168bd17d8314576c024

Je passe en version 2.11 pour la sélection du type d'étendue.
