### ISSUE TITLE
Alignement GN3

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#205]
- Merge PR GS2.11.2 > GN3
- Migration de la config facettes, schémas dont iso19139.fra (geosource + mongeosource)
- Migration base de données (geosource + mongeosource)
- Création et publication des versions de tests & finales sur sourceforge
- Adaptation interface de recherche (a minima: Text accueil, branding GS, Carte, Configuration des projections, Emprises)

**Comment by fxprunayre** [comment]
La branche de développement pour GS3 est https://github.com/geosource-catalogue/core-geonetwork/tree/geosource-3.x

**Comment by fxprunayre** [comment]
Jenkins mis à jour http://ci.titellus.net/jenkins/job/GeoSource-3.0.x/ et téléchargement en continu dispo http://file.titellus.net/geosource/3.0.x/

Aligné sur GN3.0.0RC0 sortie le 17 mars.

Reste à faire:
- tester build / vérifier config
- migration db

**Comment by MaelREBOUX** [comment]
Bonjour, 

Un commentaire à propos de la migration DB : merci de porter attention à la migration MySQL. La migration 2.9 vers 2.11 a été laborieuse.
cf mes posts visibles ici :  http://osgeo-org.1560.x6.nabble.com/Migration-GeoSource-2-9-vers-2-11-probleme-migration-de-la-base-de-donnees-tt5156147.html 

bon courage.
cdt,

**Comment by fxprunayre** [comment]
Après discussion avec le BRGM, nous n'envisageons pas de passer plus de temps sur MySQL (cependant une PR reste bienvennue).

**Comment by fxprunayre** [comment]
Migration de base : penser à https://github.com/geonetwork/core-geonetwork/issues/809#issuecomment-92340737

**Comment by fxprunayre** [comment]
On conserve l'interface ExtJS pour le moment.
