### ISSUE TITLE
Partage vers les réseaux sociaux -> nouvelle fenêtre

### ISSUE THREAD

**Issue by MaelREBOUX** [geosource-catalogue/core-geonetwork#208]
Pour les fonctions de partage vers les réseaux sociaux : ouvrir une nouvelle fenêtre plutôt que de continuer dans la même. C'est le comportement le plus souvent rencontré sur les sites d'actus, etc.
Ca évite de perdre la ressource consultée.

mettre label : enhancement

**Comment by fxprunayre** [comment]
Corrigé par https://github.com/geonetwork/core-geonetwork/commit/b629700ebfadf32e1b40fa42134e9534c1f1e826

A tester et fermer

**Comment by taffoureau** [comment]
Fonction non proposée dans Géosource ?

**Comment by fxprunayre** [comment]
Si c'est là
![image](https://cloud.githubusercontent.com/assets/1701393/7175367/07529ece-e414-11e4-9150-e51aa09be50f.png)

**Comment by MaelREBOUX** [comment]
tant qu'on y est : est-ce qu'il serait possible de pouvoir afficher / masquer ces boutons en fonction d'un paramètre dans l'administration ?
Je m'explique : j'ai pas envie que des agents balancent sur FaceBook ou Twitter des url internes à mon réseau informatique -> vulnérabilité...

**Comment by taffoureau** [comment]
Ah si les boutons sont bien présents... une configuration via un fichier de conf suffirait ?

**Comment by fxprunayre** [comment]
Si vous souhaitez modifier, voir le template HTML https://github.com/geonetwork/core-geonetwork/blob/develop/web-ui/src/main/resources/catalog/views/default/templates/recordView.html#L393

Une des idées de la v3 est de simplifier la personnalisation des vues avec ce mode HTML (basé sur AngularJS) et les formatters (Groovy & XSL) - sans mélange avec la partie édition comme en v2.x. Je propose pour le moment de ne pas introduire de nouvelle option de configuration précise de cette vue (potentiellement le nombre d'options possibles pourrait être sans fin - il semble préférable de personnaliser le template).

Au niveau des modes de consultation, un besoin prioritaire en ce moment porte sur la config des vues par schéma / par type de fiche.

**Comment by MaelREBOUX** [comment]
Donc, en gros : je commente simplement les lignes 390 -> 404 dans le template.
Ca me va aussi.
Il va falloir trouver un endroit pour documenter tout ceci. Une idée ?

Pas de mélange avec le mode édition : gros gros progrès !

**Comment by fxprunayre** [comment]
> Il va falloir trouver un endroit pour documenter tout ceci. Une idée ?

On travaille sur la future doc avec Etienne. Plus de nouvelle en début de semaine prochaine.

**Comment by MaelREBOUX** [comment]
sous forme de wiki ce serait idéal.
bon we.
