### ISSUE TITLE
Accepter les cookies : traduire message en -> fr

### ISSUE THREAD

**Issue by MaelREBOUX** [geosource-catalogue/core-geonetwork#209]
Le message demande à l'internaute d'autoriser l'utilisation des cookies pour ce site est en anglais.
Prévoir traduction + mécanisme de prise en charge de la langue du navigateur client

enhancement

**Comment by fxprunayre** [comment]
Corrigé https://github.com/geonetwork/core-geonetwork/issues/894

La traduction en français sera à faire sur transifex (https://www.transifex.com/projects/p/core-geonetwork/language/fr/) - il va se mettre à jour dans la journée. @MaelREBOUX, Je t'ai invité au groupe  si tu veux participer.

Reste à faire : traduction en fr sur transifex

**Comment by MaelREBOUX** [comment]
Peux-tu relancer l'invitation mais à ma nouvelle adresse m.reboux@rennesmetropole.fr ?
Merci d'avance.

**Comment by fxprunayre** [comment]
C'est fait normalement.

**Comment by MaelREBOUX** [comment]
fait merci.
Bon et maintenant : où est la ressource à traduire ? J'ai cherché "cookie" dans le dépôt mais j'ai rien trouvé. Normal ?

**Comment by fxprunayre** [comment]
> Bon et maintenant : où est la ressource à traduire ? J'ai cherché "cookie" dans le dépôt mais j'ai rien trouvé. Normal ?

Oui transifex récupére la langue principale une fois par jour. Donc demain plus probablement. Je vais regarder pour voir si on peut forcer la récupération.

**Comment by MaelREBOUX** [comment]
ha ok : j'avais bien compris alors. A demain.

**Comment by fxprunayre** [comment]
Traduit côté transifex.

**Comment by fxprunayre** [comment]
Traduction mise à jour. A tester.
