### ISSUE TITLE
Vue complète - onglet "associé"

### ISSUE THREAD

**Issue by bchartier** [geosource-catalogue/core-geonetwork#210]
La vue complète d'une fiche de métadonnées de GN3 contient un onglet "Associé". Ce libellé n'est pas clair. A quoi cela correspond-t-il. Sur les quelques fiches que j'ai ouvertes, cet onglet est grisé : 
![image](https://cloud.githubusercontent.com/assets/2361255/6781793/86935a36-d170-11e4-84a7-c07b52aa3055.png)
Est-ce normal ?

**Comment by MaelREBOUX** [comment]
@bchartier 
changer le titre de l'issue en "onglet 'associé'"

Grisé chez moi également.
En fait : moi je suis embêté : j'aurais préféré retrouver les onglets supplémentaires que j'utilise tout le temps en mode édition.
![screenshot469](https://cloud.githubusercontent.com/assets/6370443/6848390/29504136-d3cd-11e4-9a50-e0b7d06cd0bb.png)

**Comment by bchartier** [comment]
@MaelREBOUX  : non du ticket modifié

**Comment by lecault** [comment]
Pas grisé chez moi : il s'agit des métadonnées associées. Chez moi par exemple les métadonnées de services.

**Comment by bchartier** [comment]
Ok. C'est juste que l'IHM n'est pas très explicite alors.

**Comment by fxprunayre** [comment]
Une suggestion de libellé pour cet onglet ?

**Comment by bchartier** [comment]
Je proposerais bien "Ressources associées" ou "Ressources liées" mais c'est peut-être trop long.

**Comment by taffoureau** [comment]
OK pour "Ressources associées" pour être en cohérence avec à l'édition.

**Comment by fxprunayre** [comment]
Traduit dans transifex https://www.transifex.com/projects/p/core-geonetwork/translate/#fr/webwebapplocformatterjson/39611140

**Comment by fxprunayre** [comment]
A tester.

**Comment by taffoureau** [comment]
OK, mais le texte est aligné à gauche alors que pour les autres onglets le texte est centré. Du coup, ça crée un décalage.
![fireshot screen capture 098 - mon geosource - mon organisation - geosourcetest_brgm-rec_fr_geosource_srv_fre_catalog_search _metadata_9dd5cbae-1b84-4c7d-998d-3e335f6ea986test](https://cloud.githubusercontent.com/assets/2026724/7316817/8b3f18cc-ea7a-11e4-95a2-7c1b4c8e6339.png)

**Comment by fxprunayre** [comment]
Non, ils sont tous en text-align:left, mais celui-ci est long donc ca se voit.

![image](https://cloud.githubusercontent.com/assets/1701393/7317100/1bbcc316-ea7d-11e4-9872-38f898ff6c89.png)

Versions futures ?

**Comment by bchartier** [comment]
Le word-wrap fait que l'onglet prend la largeur définie par max-width.
Pour éviter cela, une solution de contournement serait que le texte de l'onglet soit un truc du genre : 

``` html
<span>Ressources</span><br><span>associées</span>
```

Pas facile à gérer dans le contexte d'une appli multilingue, à moins que les caractères de retour chariot soient directement insérés à la source des libellés...
