### ISSUE TITLE
Libellés

### ISSUE THREAD

**Issue by bchartier** [geosource-catalogue/core-geonetwork#211]
Quelques remarques sur les libellés du formulaire de recherche avancé : 
- pour les filtres des dates : mettre tout le temps une majuscule ou une minuscule pour la première lettre.
- pour les filtres sur les catégories, les mots-clés et les contacts, mettre tous les libellés au pluriel pour plus de cohérence.
- traduire "Contact for the resource" en "Contacts pour la ressource" (j'ai vu #209 mais je ne vais pas pouvoir contribuer au projet Transiflex dans l'immédiat)

Quelques remarques sur les termes utilisés dans le filtre "Type de ressource" : 
- il faudra peut-être utiliser les termes officiels français de la directive INSPIRE : série de données, ensemble de séries de données à la place de "jeu(x) de données" et "Collection de données" ?
- ajouter une majuscule à "application"

Quelques remarques sur les libellés de champs dans la fiche complète de métadonnées de GN3 : 
- ajouter un "s" à "jeu de caractère" -> "jeu de caractères"
- ajouter un "s" à "domaine de valeur" -> "domaine de valeurs"
- pour les points de contact, remplacer "fonction" par "rôle" ?
- remplacer "Progrès" par "Statut" ou "État d'avancement" ?
- remplacer "Maintenance Fréquence" par "Fréquence de mise à jour" ?

**Comment by fxprunayre** [comment]
> pour les filtres des dates : mettre tout le temps une majuscule ou une minuscule pour la première lettre.

Fait via CSS dans GN

> pour les filtres sur les catégories, les mots-clés et les contacts, mettre tous les libellés au pluriel pour plus de cohérence.

Cf. transifex

> traduire "Contact for the resource" en "Contacts pour la ressource" (j'ai vu #209 mais je ne vais pas pouvoir contribuer au projet Transiflex dans l'immédiat)

Cf. transifex

> Quelques remarques sur les libellés de champs dans la fiche complète de métadonnées de GN3 :

Fait via CSS dans GN

**Comment by fxprunayre** [comment]
> il faudra peut-être utiliser les termes officiels français de la directive INSPIRE : série de données, ensemble de séries de données à la place de "jeu(x) de données" et "Collection de données" ?

Fait dans GéoSource uniquement pour le schéma ISO19139 et ISO19139.fra.
