### ISSUE TITLE
Recherche par facettes : résultat vide anormal

### ISSUE THREAD

**Issue by bchartier** [geosource-catalogue/core-geonetwork#212]
Lorsque j'utilise la recherche par facettes je me retrouve régulièrement avec un résultat vide alors que les badges avec les numéros dans la colonne de gauche indiquaient un nombre non nul d'enregistrements.

Exemple avec un seul filtre : 
![image](https://cloud.githubusercontent.com/assets/2361255/6782820/b494e7a0-d176-11e4-948d-fb7fa2b5745c.png)

J'aurais dû avoir 144 fiches : 
![image](https://cloud.githubusercontent.com/assets/2361255/6782839/c9ca89ea-d176-11e4-8842-5c9afda6c014.png)

**Comment by fxprunayre** [comment]
En cours de correction côté ifremer

**Comment by taffoureau** [comment]
C'est en cours de correction? corrigé ?

**Comment by fxprunayre** [comment]
Est-ce que tu as un cas pour illustrer le pb ?

**Comment by taffoureau** [comment]
Non reproduit sur Géosource, ni sur le site de démo de titellus avec a priori le même mot-clé.
