### ISSUE TITLE
Retour en arrière dans l'historique du navigateur

### ISSUE THREAD

**Issue by bchartier** [geosource-catalogue/core-geonetwork#213]
Quand j'utilise les flèches du navigateur pour revenir dans l'historique de ma navigation, l'IHM de GN3 perd les pédales.

Exemple : 
- j'applique un seul filtre avec le mot-clé "Transport" dans les facettes -> j'obtiens la liste des fiches associés à ce mot-clé. Parfait.
- j'utilise la flèche de retour en arrière une fois. La navigateur ne recharge pas la page web mais ce contente de recentrer la page verticalement. Je ne vois pas pourquoi mais en tout cas c'est bof.
- j'insiste en appuyant de nouveau sur la flèche arrière du navigateur. Cette fois c'est différent, il affiche un résultat de recherche vide qui ne correspond pas à la réalité : 

![image](https://cloud.githubusercontent.com/assets/2361255/6783052/fea30100-d177-11e4-88f1-034c58c19f16.png)

Surtout, j'aurais aimé que GN3 revienne à la recherche précédente.

**Comment by fxprunayre** [comment]
Ca devrait être mieux avec https://github.com/geonetwork/core-geonetwork/commit/b991966c6c48ac8c394dd3f546a558b83611e28d. A suivre.

**Comment by fxprunayre** [comment]
En cours de correction côté ifremer

**Comment by fxprunayre** [comment]
A priori c'est bon. @taffoureau je te laisse tester et ajouter un scénario s'il y a problème.
