### ISSUE TITLE
ergonomie : bouton de choix des vues

### ISSUE THREAD

**Issue by MaelREBOUX** [geosource-catalogue/core-geonetwork#215]
en mode consultation : c'est à droite
en mode maj : c'est à gauche

-> harmoniser SVP car c'est déroutant

**Comment by fxprunayre** [comment]
Proposition : en édition bouton à droite.

**Comment by fxprunayre** [comment]
Corrigé avec https://github.com/geonetwork/core-geonetwork/commit/eba502841253580bb8c5297a81d0c573596e9344

A tester et fermer.
