### ISSUE TITLE
caractère joker pour la recherche avancée / indexation

### ISSUE THREAD

**Issue by MaelREBOUX** [geosource-catalogue/core-geonetwork#216]
En titre secondaire + dans les modalités de diffusion je stocke le nom schema.table des ressources.
Exemple :  Titre alternatif :  foncier.grand_proprio_plg  / ressource en ligne :      postgis-bdu:bdu:foncier:grand_proprio_plg

Dans GéoSource 2.9 je peux ainsi trouver toutes les tables du schema foncier en tapant « foncier.\* ».
Je n’ai pas trouvé le caractère joker sous GN 3.0 et j’ai l’impression que l’indexation ne prend pas en compte les titres alternatifs ou le texte pour la ressource en ligne.

**Comment by fxprunayre** [comment]
A priori, ca fonctionne.

eg. http://apps.titellus.net/geonetwork/srv/eng/catalog.search#/search?from=1&to=20&sortBy=relevance&fast=index&_content_type=json&any=foncier.* retourne CHU river basin qui contient foncier.grand_proprio_plg en titre alternatif

**Comment by fxprunayre** [comment]
A tester.

**Comment by taffoureau** [comment]
Fonctionne également de mon côté.
