### ISSUE TITLE
Activation vue INSPIRE

### ISSUE THREAD

**Issue by MaelREBOUX** [geosource-catalogue/core-geonetwork#218]
Je n'ai pas pu l'activer.
D'autres personnes dans ce cas ?

**Comment by fxprunayre** [comment]
Dans l'éditeur, supprimer l'attribut disabled ici (pas besoin de relancer l'application)
https://github.com/geonetwork/core-geonetwork/blob/develop/schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml#L231

 En consultation, elle n'existe pas.

Les options dans l'administration sont en lien avec l'ancienne interface et seront supprimées prochainement.

**Comment by fxprunayre** [comment]
La vue INSPIRE est dispo dans GS3 (préconfiguré avec cette option à la différence de GN3). A tester.
