### ISSUE TITLE
Page d’accueil avec les thèmes ISO

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#219]
"Je ne supporte pas cette vue avec les thèmes ISO dont tout le monde se fiche.
J’aimerai avoir la nomenclature GéoBretagne à la place : comment on change ou customise cela ?"

**Comment by fxprunayre** [comment]
Ca fait partie des points discutés semaine dernière à la réunion des utilisateurs GeoNetwork. Nous avons évoqués:
1) avoir un jeu d'icônes pour les thèmes INSPIRE
2) pouvoir configurer les champs à utiliser pour la classifications sur la page d'accueil (eg. catégories, thèmes INSPIRE, type de données, autre champ de l'index)

A priori ce ne sera pas fait en 3.0.0

**Comment by MaelREBOUX** [comment]
Grillé : je venais ici pour créer cette requête justement.

L'idéal : taper un thesaurus. Comme ça on sait qu'on peut avoir des catégories de données vides.
