### ISSUE TITLE
Lien "Gestion de moissonnage" depuis le menu principal

### ISSUE THREAD

**Issue by delobelle** [geosource-catalogue/core-geonetwork#22]
Sous Firefox le lien : 
http://geosourcetest.brgm-rec.fr/geonetwork/srv/fre/service-not-allowed?referer=/geosource/srv/fre/harvesting

amène à une page blanche

Sous IE8 a un message d'erreur Page Web introuvable

**Comment by fxprunayre** [comment]
Non reproductible en 2.11. A fermer ?
