### ISSUE TITLE
Exports de rapports

### ISSUE THREAD

**Issue by Fonaine** [geosource-catalogue/core-geonetwork#223]
L'export de rapports ne fonctionne pas. Le service semble systématiquement rejeté.
![exports_rapports](https://cloud.githubusercontent.com/assets/238629/7140329/f59bada0-e2ca-11e4-94b0-1568c21378e4.png)

Problème reproduit sur une installation sous windows7 et sous tomcat/postgresql

**Comment by fxprunayre** [comment]
Non reproductible en v3 de mon côté
![image](https://cloud.githubusercontent.com/assets/1701393/7175439/e8c88a8a-e414-11e4-83e3-271a206d6350.png)

A retester ou préciser le cas problématique.

(et des Pull Requests avec des corrections sont toujours les bienvenues !)

**Comment by fxprunayre** [comment]
Cf. https://github.com/geosource-catalogue/core-geonetwork/commit/4d2b28328e427c7a6bca0e8380237d78aa203d67

**Comment by taffoureau** [comment]
Testé sous Windows 7.

OK sous Chrome.

Par contre, sous Firefox rien ne s'affiche. Pourtant d'après Firebug le traitement à l'air de bien se faire (cf. copie d'écran).

**Comment by taffoureau** [comment]
![nouvelle image 5](https://cloud.githubusercontent.com/assets/2026724/7856823/485984ee-052c-11e5-9f88-274940de077e.png)

**Comment by fxprunayre** [comment]
Fixed
