### ISSUE TITLE
Renvoi vers l'ancienne interface au login

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#226]
Depuis http://geosourcetest.brgm-rec.fr/geosource/srv/fre/catalog.search#/home

=> s'identifier => http://geosourcetest.brgm-rec.fr/geosource/srv/fre/catalog.signin

=> admin/admin => http://geosourcetest.brgm-rec.fr/geosource/srv/fre/find

**Comment by fxprunayre** [comment]
A priori je ne reproduis pas. Préciser le cas de test.

**Comment by taffoureau** [comment]
Je ne reproduit plus.
