### ISSUE TITLE
Supprimer le bouton visualiser dans la barre de menus

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#227]

**Comment by fxprunayre** [comment]
Ca se fait dans l'admin
![image](https://cloud.githubusercontent.com/assets/1701393/7156209/f23f5fb8-e364-11e4-9ef3-f32f67a6243c.png)

Que faisons nous par défaut ? +1 pour conserver la carte par défaut de mon côté.

**Comment by taffoureau** [comment]
décocher par défaut

**Comment by fxprunayre** [comment]
A tester
