### ISSUE TITLE
Désativation de la vue simple par défaut

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#228]
Désactiver la vue simple par défaut.

Par ailleurs, lorsque je désactive cette vue dans admin>paramètres elle est toujours active en édition.

**Comment by fxprunayre** [comment]
> Désactiver la vue simple par défaut.

C'est à dire ? en consultation ? on a que la vue avancée ?

> Par ailleurs, lorsque je désactive cette vue dans admin>paramètres elle est toujours active en édition.

Dans l'admin la configuration des vues ne concerne que l'ancienne interface. - Ca sera supprimé dans GN 3.0.1.
