### ISSUE TITLE
Lien vers une fiche importée est manquant

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#229]
Contrairement à la v2.11, après import d'un fichier de métadonnées, il n'est pas possible d'accéder directement à la fiche. C'est dommage, car cela oblige à faire une recherche pour la retrouver.

Par ailleurs, dans le message l'uuid est vide:

Téléchargement réussi

Couche importée avec succès:
id: 4268
uuid:

**Comment by fxprunayre** [comment]
- Ajout d'un lien vers l'éditeur (via l'ID).
- Suppression de l'UUID

Remarque (pour info) : en mode mise à jour, l'id interne change car il y a suppression puis insertion. L'UUID reste le même. Ca veut dire qu'il y a suppression des catégories, privilèges, ...

L'information sur le UUID est disponible que sur certain type d'import (eg. copy/paste). Il faudrait l'UUID pour ouvrir le mode consultation (sans modification majeure des imports ou de la consultation). Je propose de faire ça en version future ?
