### ISSUE TITLE
Import d'une fiche / remplacer MEF par ZIP

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#230]

**Comment by fxprunayre** [comment]
Je propose https://www.transifex.com/projects/p/core-geonetwork/translate/#fr/editor/26029602?q=MEF

Je te laisse remplacer par ZIP tout court si ça semble mieux.

**Comment by fxprunayre** [comment]
Mettre à jour les traductions depuis transifex

**Comment by fxprunayre** [comment]
Mis à jour. A tester.
