### ISSUE TITLE
Import/écraser les fiches de même identifiant ne fonctionne pas

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#231]
could not execute batch; SQL [insert into Metadata (data, changeDate, createDate, displayorder, doctype, extra, popularity, rating, root, schemaId, title, isTemplate, isHarvested, harvestUri, harvestUuid, groupOwner, owner, source, uuid, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch

**Comment by fxprunayre** [comment]
Je ne reproduis pas ni en MEF ni en XML. Preneur du fichier importé.

**Comment by MaelREBOUX** [comment]
J'ai eu la même chose (ou à peu près) mais sur une base MySQL. Quel est le SGBD sous-jacent @taffoureau ?

**Comment by taffoureau** [comment]
Je suis sous postgres.

**Comment by fxprunayre** [comment]
Toujours preneur d'un fichier exemple pour reproduire.

**Comment by taffoureau** [comment]
Envoyé par mail.

**Comment by fxprunayre** [comment]
J'ai pas de pb ni sur mise à jour ou nouvel identifiant. Quelle est la manip faite à l'import ?

![image](https://cloud.githubusercontent.com/assets/1701393/7352581/e06a1c72-ed0c-11e4-95df-99705074fb1f.png)

**Comment by taffoureau** [comment]
On est d'accord que c'est quand je coche "ecraser les mtds de même identifiant"

**Comment by fxprunayre** [comment]
> On est d'accord que c'est quand je coche "ecraser les mtds de même identifiant"

Oui. J'ai pas l'erreur ni avec copier/coller ou upload et la fiche est bien mise à jour.

D'autres options choisies ? Si non, il me faudra la base pour tenter de reproduire si le pb vient pas de la fiche, c'est sans doute en lien avec ce qu'il y a dans la base.

Une petite vérification, dans la base, qu'indique START pour la séquence hibernate_sequence

```
CREATE SEQUENCE hibernate_sequence
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 3227
```

et combien retourne

```
SELECT count(*) FROM params;
```

?

Si le count > START, modifier la séquence en conséquence.

**Comment by taffoureau** [comment]
START 4081
et
count : 3228
Je t'envoie un dump de la base par mail.

**Comment by fxprunayre** [comment]
Je reproduis avec le dump

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/issues/968

A tester.
