### ISSUE TITLE
Page admin>paramètres : pb affichage du plan

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#234]
Dans la page paramètres en admin le plan situé à droite permettant de naviguer rapidement dans les différentes sections s'affiche au-dessus du contenu de la page, et il n'est pas possible de le réduire.

voir image jointe.
![nouvelle image 1](https://cloud.githubusercontent.com/assets/2026724/7159070/cd4b8d24-e37f-11e4-8017-ff84d2a8d6e3.png)

**Comment by fxprunayre** [comment]
Corrigé - du coup il y a double scrollbar dans ce cas.

![image](https://cloud.githubusercontent.com/assets/1701393/7172271/0d4ffc9c-e3e5-11e4-871a-ff8a48501d2b.png)
