### ISSUE TITLE
Consultation de fiches / débordement des champs

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#238]
cf. copie d'écran
![fireshot screen capture 099 - mon geosource - mon organisation - geosourcetest_brgm-rec_fr_geosource_srv_fre_catalog_search _metadata_ae33482c-39e3-4870-aa5c-3e777faf6020](https://cloud.githubusercontent.com/assets/2026724/7317001/1ed3bc90-ea7c-11e4-9489-b2cf0ebfe367.png)

**Comment by fxprunayre** [comment]
A tester.

**Comment by taffoureau** [comment]
J'ai toujours le problème suite à un redéploiement cet après-midi.
![fireshot screen capture 100 - mon geosource - mon organisation - geosourcetest_brgm-rec_fr_geosource_srv_fre_catalog_search _metadata_5a4c6333-2751-425e-a003-59517d56c285](https://cloud.githubusercontent.com/assets/2026724/7352044/6596c3ea-ed09-11e4-8bfc-f6948c9966ce.png)

Question subsidiaire : à quoi correspond le logo du catalogue qui apparaît sur la copie d'écran ?

**Comment by fxprunayre** [comment]
Cache du navigateur ?

testé sous chrome et FF avec https://gist.github.com/fxprunayre/13c930048ce56167d2f4

![image](https://cloud.githubusercontent.com/assets/1701393/7352630/35d39e04-ed0d-11e4-87eb-63b8026ca40f.png)

**Comment by fxprunayre** [comment]
> Question subsidiaire : à quoi correspond le logo du catalogue qui apparaît sur la copie d'écran ?

J'aurai plutôt fait un autre ticket plutôt que de hacker celui-là :)
Le logo du catalogue (cf admin > logo) voire le logo du groupe si l'option est activée.

**Comment by taffoureau** [comment]
Pas de pb de cache, j'ai essayé avec FFX (37.x) et Chrome (42.x) et je reproduis:
![nouvelle image](https://cloud.githubusercontent.com/assets/2026724/7352745/7cff05e2-ed0e-11e4-936d-3caf317a5cc9.png)

**Comment by ghost** [comment]
Je pense que l’erreur vient de là :
https://github.com/geonetwork/core-geonetwork/blob/9da87b82c04874ef3846cf1822ca6af073b71d40/web-ui/src/main/resources/catalog/tmp/metadata.css#L5050

Il faudrait rajouter également un 
text-align:left

**Comment by taffoureau** [comment]
OK, pas critique car les formats sont généralement courts.

**Comment by fxprunayre** [comment]
J'avais bien committé un truc https://github.com/geonetwork/core-geonetwork/commit/b5fce309c96d7b0400e45bb277179e0460c6afc3 pour ça, à voir pourquoi ce n'est pas suffisant
