### ISSUE TITLE
Logo du catalogue par défaut

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#239]
Le logo du catalogue a changé ?

Voir:
![fireshot screen capture 100 - mon geosource - mon organisation - geosourcetest_brgm-rec_fr_geosource_srv_fre_catalog_search _metadata_5a4c6333-2751-425e-a003-59517d56c285](https://cloud.githubusercontent.com/assets/2026724/7352849/3eaa6402-ed0f-11e4-9aae-97696ebe8b29.png)

**Comment by fxprunayre** [comment]
Problème en 2.11 également.

**Comment by fxprunayre** [comment]
A tester
