### ISSUE TITLE
[2.9.2] Accents non supportés dans l'autosuggestion

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#24]
Dans la recherche "full text", lorsqu'on saisit un mot-clé avec accent 'par exemple "géologie", rien n'est remonté en suggestion. Alors que "geologie" fonctionne.

Dans la liste des mots-clés dans la suggestion les accents n'apparaissent pas.

**Comment by fxprunayre** [comment]
See https://github.com/geonetwork/core-geonetwork/issues/357 corrigé dans GN 2.10.x & develop

**Comment by taffoureau** [comment]
OK pour le 1er point.
Est-ce normal que les accents n'apparaissent pas dans les valeurs de la liste?

**Comment by fxprunayre** [comment]
Oui pour les champs comme full text qui est un champ analysé et non stocké. Ce sont les valeurs de l'index qui sont retournées (et qui ont été analysées dans ce cas). Pour les mots clés, le champ est stocké (car on en a besoin pour afficher les résultats) et ce sont donc les valeurs non analysées.

**Comment by taffoureau** [comment]
OK.
