### ISSUE TITLE
Date de la spécification INSPIRE/calendrier non proposé

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#240]
Il est proposé un simple champ texte, voir:
![fireshot screen capture 101 - mon geosource - mon organisation - geosourcetest_brgm-rec_fr_geosource_srv_fre_catalog_edit _metadata_5758](https://cloud.githubusercontent.com/assets/2026724/7353240/7aaf0220-ed12-11e4-8605-6cf381759ba0.png)

**Comment by fxprunayre** [comment]
Pb présent dans la version précédente sous FF uniquement a priori qui n'implémente pas le type HTML5 date.

Eg. sous chrome
![image](https://cloud.githubusercontent.com/assets/1701393/7353427/bcab4b6a-ed13-11e4-9e4b-3e32cdf362b5.png)

Version future ?
