### ISSUE TITLE
Pb affichage "paramètres" dans la console d'admin

### ISSUE THREAD

**Issue by atellezarenas** [geosource-catalogue/core-geonetwork#241]
Dans la console d'admin, affichage des paramètres (http://(...)/geonetwork/srv/fre/admin.console#/settings), s'affichent des champs avant le formulaire "normal". De plus; le petit menu à droite à presque disparu. Il est possible que ce soit un pb venant de la BD, qui a été migrée en suivant les différents scripts. Pour reproduire, utiliser le dump que j'envoye par mail. 

![pbparamgeo3](https://cloud.githubusercontent.com/assets/7068336/7366226/f4e22cd2-ed96-11e4-9348-c23b61d19063.png)

**Comment by fxprunayre** [comment]
Hum, que retourne http://localhost:8080/geosource/srv/fre/admin.config.list?asTree=false ?

**Comment by atellezarenas** [comment]
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;settings&gt;
  &lt;setting name=&quot;abstract&quot; position=&quot;1280&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;accessConstraints&quot; position=&quot;1300&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;address&quot; position=&quot;1610&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;administrativeArea&quot; position=&quot;1520&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;city&quot; position=&quot;1510&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;contactInfo&quot; position=&quot;1250&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;contactInstructions&quot; position=&quot;1630&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;country&quot; position=&quot;1540&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;deliveryPoint&quot; position=&quot;1500&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;email&quot; position=&quot;1550&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;facsimile&quot; position=&quot;1410&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;fees&quot; position=&quot;1290&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;harvesting&quot; position=&quot;20&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;hoursOfService&quot; position=&quot;1620&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;ignored&quot; position=&quot;9550&quot; datatype=&quot;null&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;individualName&quot; position=&quot;1230&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;map/config&quot; position=&quot;9590&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;{&quot;useOSM&quot;:false,&quot;context&quot;:&quot;&quot;,&quot;layer&quot;:{&quot;url&quot;:&quot;http://www2.demis.nl/mapserver/wms.asp?&quot;,&quot;layers&quot;:&quot;Countries&quot;,&quot;version&quot;:&quot;1.1.1&quot;},&quot;projection&quot;:&quot;EPSG:4326&quot;,&quot;projectionList&quot;:[&quot;EPSG:4326&quot;,&quot;EPSG:2154&quot;,&quot;EPSG:3857&quot;]}&lt;/setting&gt;
  &lt;setting name=&quot;map/isMapViewerEnabled&quot; position=&quot;9592&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;map/proj4js&quot; position=&quot;9591&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;[{&quot;code&quot;:&quot;EPSG:2154&quot;,&quot;value&quot;:&quot;+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs&quot;}]&lt;/setting&gt;
  &lt;setting name=&quot;metadata/editor/schemaConfig&quot; position=&quot;10000&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;{&quot;iso19110&quot;:{&quot;defaultTab&quot;:&quot;default&quot;,&quot;displayToolTip&quot;:false,&quot;related&quot;:{&quot;display&quot;:true,&quot;readonly&quot;:true,&quot;categories&quot;:[&quot;dataset&quot;]},&quot;validation&quot;:{&quot;display&quot;:true}},&quot;iso19139&quot;:{&quot;defaultTab&quot;:&quot;inspire&quot;,&quot;displayToolTip&quot;:false,&quot;related&quot;:{&quot;display&quot;:true,&quot;categories&quot;:[]},&quot;suggestion&quot;:{&quot;display&quot;:true},&quot;validation&quot;:{&quot;display&quot;:true}},&quot;dublin-core&quot;:{&quot;defaultTab&quot;:&quot;default&quot;,&quot;related&quot;:{&quot;display&quot;:true,&quot;readonly&quot;:false,&quot;categories&quot;:[&quot;parent&quot;,&quot;onlinesrc&quot;]}}}&lt;/setting&gt;
  &lt;setting name=&quot;metadata/resourceIdentifierPrefix&quot; position=&quot;10001&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;http://localhost:8080/geonetwork/&lt;/setting&gt;
  &lt;setting name=&quot;phone&quot; position=&quot;1600&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;positionName&quot; position=&quot;1240&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;postalCode&quot; position=&quot;1530&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;region/getmap/background&quot; position=&quot;9590&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;osm&lt;/setting&gt;
  &lt;setting name=&quot;region/getmap/mapproj&quot; position=&quot;9590&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;EPSG:3857&lt;/setting&gt;
  &lt;setting name=&quot;region/getmap/summaryWidth&quot; position=&quot;9590&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;500&lt;/setting&gt;
  &lt;setting name=&quot;region/getmap/width&quot; position=&quot;9590&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;500&lt;/setting&gt;
  &lt;setting name=&quot;role&quot; position=&quot;1260&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/autodetect/enable&quot; position=&quot;9510&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/autofixing/enable&quot; position=&quot;2410&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/clickablehyperlinks/enable&quot; position=&quot;2010&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/csw/contactId&quot; position=&quot;1220&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/csw/enable&quot; position=&quot;1210&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/csw/metadataPublic&quot; position=&quot;1310&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/csw/transactionUpdateCreateXPath&quot; position=&quot;1320&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/downloadservice/leave&quot; position=&quot;2210&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/downloadservice/simple&quot; position=&quot;2220&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/downloadservice/withdisclaimer&quot; position=&quot;2230&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/feedback/email&quot; position=&quot;610&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/feedback/mailServer/host&quot; position=&quot;630&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/feedback/mailServer/password&quot; position=&quot;643&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/feedback/mailServer/port&quot; position=&quot;640&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;25&lt;/setting&gt;
  &lt;setting name=&quot;system/feedback/mailServer/ssl&quot; position=&quot;641&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/feedback/mailServer/username&quot; position=&quot;642&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/harvester/enableEditing&quot; position=&quot;9010&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/harvesting/mail/enabled&quot; position=&quot;9025&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/harvesting/mail/level1&quot; position=&quot;9026&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/harvesting/mail/level2&quot; position=&quot;9027&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/harvesting/mail/level3&quot; position=&quot;9028&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/harvesting/mail/recipient&quot; position=&quot;9020&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/harvesting/mail/subject&quot; position=&quot;9024&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;[$$harvesterType$$] $$harvesterName$$ finished harvesting&lt;/setting&gt;
  &lt;setting name=&quot;system/harvesting/mail/template&quot; position=&quot;9021&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/harvesting/mail/templateError&quot; position=&quot;9022&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;There was an error on the harvesting: $$errorMsg$$&lt;/setting&gt;
  &lt;setting name=&quot;system/harvesting/mail/templateWarning&quot; position=&quot;9023&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/indexoptimizer/at/hour&quot; position=&quot;6030&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;0&lt;/setting&gt;
  &lt;setting name=&quot;system/indexoptimizer/at/min&quot; position=&quot;6040&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;0&lt;/setting&gt;
  &lt;setting name=&quot;system/indexoptimizer/at/sec&quot; position=&quot;6050&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;0&lt;/setting&gt;
  &lt;setting name=&quot;system/indexoptimizer/enable&quot; position=&quot;6010&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/indexoptimizer/interval&quot; position=&quot;6060&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/indexoptimizer/interval/day&quot; position=&quot;6070&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;0&lt;/setting&gt;
  &lt;setting name=&quot;system/indexoptimizer/interval/hour&quot; position=&quot;6080&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;24&lt;/setting&gt;
  &lt;setting name=&quot;system/indexoptimizer/interval/min&quot; position=&quot;6090&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;0&lt;/setting&gt;
  &lt;setting name=&quot;system/inspire/atom&quot; position=&quot;7230&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;disabled&lt;/setting&gt;
  &lt;setting name=&quot;system/inspire/atomProtocol&quot; position=&quot;7250&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;INSPIRE-ATOM&lt;/setting&gt;
  &lt;setting name=&quot;system/inspire/atomSchedule&quot; position=&quot;7240&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;0 0 0/24 ? \* *&lt;/setting&gt;
  &lt;setting name=&quot;system/inspire/enable&quot; position=&quot;7210&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/inspire/enableSearchPanel&quot; position=&quot;7220&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/intranet/netmask&quot; position=&quot;320&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;255.0.0.0&lt;/setting&gt;
  &lt;setting name=&quot;system/intranet/network&quot; position=&quot;310&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;127.0.0.1&lt;/setting&gt;
  &lt;setting name=&quot;system/localrating/enable&quot; position=&quot;2110&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/metadata/allThesaurus&quot; position=&quot;9160&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/metadata/defaultView&quot; position=&quot;9150&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;simple&lt;/setting&gt;
  &lt;setting name=&quot;system/metadata/enableInspireView&quot; position=&quot;9130&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/metadata/enableIsoView&quot; position=&quot;9120&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/metadata/enableSimpleView&quot; position=&quot;9110&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/metadata/enableXmlView&quot; position=&quot;9140&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/metadata/prefergrouplogo&quot; position=&quot;9111&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/metadataprivs/usergrouponly&quot; position=&quot;9180&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/oai/cachesize&quot; position=&quot;7030&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;60&lt;/setting&gt;
  &lt;setting name=&quot;system/oai/mdmode&quot; position=&quot;7010&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;1&lt;/setting&gt;
  &lt;setting name=&quot;system/oai/tokentimeout&quot; position=&quot;7020&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;3600&lt;/setting&gt;
  &lt;setting name=&quot;system/platform/subVersion&quot; position=&quot;160&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;SNAPSHOT&lt;/setting&gt;
  &lt;setting name=&quot;system/platform/version&quot; position=&quot;150&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;3.0.0&lt;/setting&gt;
  &lt;setting name=&quot;system/proxy/host&quot; position=&quot;520&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;proxysquid.brgm.fr&lt;/setting&gt;
  &lt;setting name=&quot;system/proxy/ignorehostlist&quot; position=&quot;560&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/proxy/password&quot; position=&quot;550&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/proxy/port&quot; position=&quot;530&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;80&lt;/setting&gt;
  &lt;setting name=&quot;system/proxy/use&quot; position=&quot;510&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/proxy/username&quot; position=&quot;540&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/removedMetadata/dir&quot; position=&quot;710&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;../../data/removed&lt;/setting&gt;
  &lt;setting name=&quot;system/requestedLanguage/ignorechars&quot; position=&quot;9590&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;system/requestedLanguage/only&quot; position=&quot;9530&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;prefer_locale&lt;/setting&gt;
  &lt;setting name=&quot;system/requestedLanguage/preferUiLanguage&quot; position=&quot;9595&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/requestedLanguage/sorted&quot; position=&quot;9540&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/searchStats/enable&quot; position=&quot;2510&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/selectionmanager/maxrecords&quot; position=&quot;910&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;1000&lt;/setting&gt;
  &lt;setting name=&quot;system/server/host&quot; position=&quot;210&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;trueegeology-catalog.brgm.fr&lt;/setting&gt;
  &lt;setting name=&quot;system/server/log&quot; position=&quot;250&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;log4j.xml&lt;/setting&gt;
  &lt;setting name=&quot;system/server/port&quot; position=&quot;220&quot; datatype=&quot;INT&quot; internal=&quot;false&quot;&gt;80&lt;/setting&gt;
  &lt;setting name=&quot;system/server/securePort&quot; position=&quot;240&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;8443&lt;/setting&gt;
  &lt;setting name=&quot;system/shib/firstname&quot; position=&quot;1760&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;Shib-InetOrgPerson-givenName&lt;/setting&gt;
  &lt;setting name=&quot;system/shib/path&quot; position=&quot;1720&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;/geonetwork/srv/en/shib.user.login&lt;/setting&gt;
  &lt;setting name=&quot;system/shib/profile&quot; position=&quot;1770&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;Shib-EP-Entitlement&lt;/setting&gt;
  &lt;setting name=&quot;system/shib/surname&quot; position=&quot;1750&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;Shib-Person-surname&lt;/setting&gt;
  &lt;setting name=&quot;system/shib/use&quot; position=&quot;1710&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/shib/username&quot; position=&quot;1740&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;REMOTE_USER&lt;/setting&gt;
  &lt;setting name=&quot;system/site/name&quot; position=&quot;110&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;BRGM&lt;/setting&gt;
  &lt;setting name=&quot;system/site/organization&quot; position=&quot;130&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;BRGM&lt;/setting&gt;
  &lt;setting name=&quot;system/site/siteId&quot; position=&quot;120&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;207e9569-9027-487f-922c-652dd3039a9a&lt;/setting&gt;
  &lt;setting name=&quot;system/site/svnUuid&quot; position=&quot;170&quot; datatype=&quot;STRING&quot; internal=&quot;true&quot;&gt;e1b5d5e0-ebdf-43b5-9e08-b8c9c52136e6&lt;/setting&gt;
  &lt;setting name=&quot;system/threadedindexing/maxthreads&quot; position=&quot;9210&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;1&lt;/setting&gt;
  &lt;setting name=&quot;system/ui/defaultView&quot; position=&quot;10100&quot; datatype=&quot;STRING&quot; internal=&quot;false&quot;&gt;default&lt;/setting&gt;
  &lt;setting name=&quot;system/userFeedback/enable&quot; position=&quot;1911&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/userSelfRegistration/enable&quot; position=&quot;1910&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/xlinkResolver/enable&quot; position=&quot;2310&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/xlinkResolver/localXlinkEnable&quot; position=&quot;2311&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;false&quot;&gt;true&lt;/setting&gt;
  &lt;setting name=&quot;system/z3950/enable&quot; position=&quot;410&quot; datatype=&quot;BOOLEAN&quot; internal=&quot;true&quot;&gt;false&lt;/setting&gt;
  &lt;setting name=&quot;system/z3950/port&quot; position=&quot;420&quot; datatype=&quot;INT&quot; internal=&quot;true&quot;&gt;2100&lt;/setting&gt;
  &lt;setting name=&quot;title&quot; position=&quot;1270&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
  &lt;setting name=&quot;voice&quot; position=&quot;1400&quot; datatype=&quot;null&quot; internal=&quot;true&quot; /&gt;
&lt;/settings&gt;

**Comment by atellezarenas** [comment]
Ca correspond principalement à 
select \* from settings where datatype is null

Manquerait-il qlqchose dans WEB-INF/classes/setup/sql/migrate/v2110/2-miograte-default.sql ??
A noter qu'il y a toujours une erreur dedans; (false au lieu de 'false').

INSERT INTO Settings (name, value, datatype, position, internal) VALUES ('system/feedback/mailServer/ssl', false, 2, 641, 'y');

**Comment by fxprunayre** [comment]
Ok, ca devrait ressembler à ça 

```
internal="false">http://localhost:8080/geonetwork/srv/metadata/</setting>
<setting name="region/getmap/background" position="9590" datatype="STRING" internal="false">osm</setting>
<setting name="region/getmap/mapproj" position="9590" datatype="STRING" internal="false">EPSG:3857</setting>
<setting name="region/getmap/summaryWidth" position="9590" datatype="STRING" internal="false">500</setting>
<setting name="region/getmap/width" position="9590" datatype="STRING" internal="false">500</setting>
<setting name="system/autodetect/enable" position="9510" datatype="BOOLEAN" internal="true">false</setting>

```

Donc c'est un problème de migration de la table settings.

Je proposerai bien un TRUNCATE Settings
et réinjecter les valeurs par défaut https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql#L554 ?

**Comment by atellezarenas** [comment]
OK, ça fonctionne bien. Vous allez corriger le script de migration (pour ma future re-migration, savoir si je pourrai l'utiliser ou si je referai la manip)? Merci!

**Comment by fxprunayre** [comment]
> Vous allez corriger le script de migration (pour ma future re-migration, savoir si je pourrai l'utiliser ou si je referai la manip)? 

Je crois pas tu as une base entre-deux. Donc c'est un peu galère - ca me semble plus simple de faire un reset des settings non ?

**Comment by atellezarenas** [comment]
Oui ok pas de soucis, c'est juste pour savoir. J'ai noté la manip donc pas de pb. Je ferme le ticket.
