### ISSUE TITLE
Moissonnage / libellé

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#242]
- Manque un espace
- every

**Comment by fxprunayre** [comment]
A tester.

**Comment by taffoureau** [comment]
De mon côté, pas de différence après redéploiement (à l'instant) et vidage du cache...

**Comment by ghost** [comment]
Pour moi c'est bon, mais j'ai un double espace
![image](https://cloud.githubusercontent.com/assets/6907261/7395827/e5e5ebd6-ee9c-11e4-9124-d090eb91a7f8.png)

**Comment by fxprunayre** [comment]
Ici aussi
![image](https://cloud.githubusercontent.com/assets/1701393/7395878/5c1a3488-ee9d-11e4-9d8d-569a5b03388f.png)

je viens de re-télécharger l'installer  http://file.titellus.net/geosource/3.0.x/geosource-install-3.0.0-0.jar

**Comment by fxprunayre** [comment]
Double espace à corriger en 3.0.1

**Comment by fxprunayre** [comment]
Fait dans GeoNetwork https://github.com/geonetwork/core-geonetwork/commit/a0f3a7e55ba83ab7bf2f02118934a1a5eb161906.

Ce sera dispo en 3.0.2.
