### ISSUE TITLE
détecter les modèles existants avant import

### ISSUE THREAD

**Issue by Claire1000** [geosource-catalogue/core-geonetwork#246]
actuellement on peut importer des modèles de fiches déjà existants ce qui génère des doublons.
évolution : détecter les modèles existants avant import

**Comment by fxprunayre** [comment]
A l'origine, les modèles n'ont pas d'uuid (eg. https://github.com/geonetwork/core-geonetwork/blob/develop/schemas/iso19139/src/main/plugin/iso19139/templates/vector.xml#L9) et à l'import, on ne peut pas vérifier s'il existe ou pas (c'était volontaire je pense). 

Après nous pourrions appliquer la même règle que pour les fiches.
