### ISSUE TITLE
suggestions de l'index sensibles aux accents

### ISSUE THREAD

**Issue by Claire1000** [geosource-catalogue/core-geonetwork#249]
les suggestions du champ de recherche simple sont sensibles aux accents.
par ex. : 
- je tape "reseau" > on me suggère : "reseau" et "reseau"
- je tape "réseau" > on me suggère : "Inspections télévisées pour réseaux d'assainissement" et "Rapports d'inspection télévisée réseaux d'assainissement sur l'agglomération de Chambéry métropole"

**Comment by fxprunayre** [comment]
Doublon https://github.com/geosource-catalogue/core-geonetwork/issues/236

Je ferme.
