### ISSUE TITLE
Correspondance thème INSPIRE/ISO ne fonctionne pas 

### ISSUE THREAD

**Issue by delobelle** [geosource-catalogue/core-geonetwork#25]
La saisie de "Occupation des terres " en mot clé INSPIRE n'engendre pas la mise à jour des catégories ISO dans les suggestions
Idem, la saisie du thème météorologie dans la catégorie ISO n'engendre pas les thèmes Inspire équivalent dans Suggestion

**Comment by fxprunayre** [comment]
Je ne reproduis pas il faudrait préciser - quelle fiche ? les thésaurus sont-ils bien installés ?

Cas de test:
1) créer une fiche en français
2) ajouter thème INSPIRE Altitude
3) suggestion 

```
Thèmes INSPIRE et/ou des catégories ont été trouvés avec des correspondances manquantes. Lancer ce processus pour ajouter les correspondances.
```

4) appliquer la suggestion
5) Altimétrie ajoutée dans le thème ISO

La réciproque est fonctionnelle également.

Ca marche également pour occupation des terres et caractéristiques géographiques météorologiques

**Comment by taffoureau** [comment]
OK. Lié à une mauvaise configuration du data.directory.
