### ISSUE TITLE
liste des groupes d'utilisateurs : intitulés invisibles

### ISSUE THREAD

**Issue by Claire1000** [geosource-catalogue/core-geonetwork#250]
dans la liste des groupes utilisateurs, les intitulés sont invisibles. 
(copie d'écran
![capture](https://cloud.githubusercontent.com/assets/13366230/8778720/af9af320-2eff-11e5-8af7-86fa6efecae4.PNG)
 en pièce-jointe)

**Comment by fxprunayre** [comment]
@Claire1000 , il faudrait indiquer le noeud mongeosource sur lequel c'est observé si ce n'est pas une installation geosource classique ? Sans doute en lien avec le contenu de la base de données. Merci

**Comment by Claire1000** [comment]
Bonjour, c'est observé sur les nodes 1243 et 1211.

**Comment by Claire1000** [comment]
intitulés des groupes insivibles également dans le formulaire de paramétrage de moisson d'un catalogue csw
