### ISSUE TITLE
Problème client CSW [GéoSource 2.11.1]

### ISSUE THREAD

**Issue by Guts** [geosource-catalogue/core-geonetwork#258]
Je sais qu'il s'agit d'une vielle version mais c'est celle-ci qui a été poussée en production dans la version 3.4 de Prodige, déployée cet été.

Certains organismes ont signalé que des services CSW issus d'autres plateformes (Isogeo) ou de certains profils (APISO) n'étaient plus moissonnés correctement alors que c'était le cas auparavant.

Serait-il possible d'inclure le service CSW de démonstration d'Isogeo dans les tests afin de s'assurer de la bonne intéropérabilité ? Évidemment, si les problèmes viennent de notre côté, ce sera aussi l'occasion de faire les corrections nécessaires.
##### Ressources

Service CSW pour tests : http://services.api.isogeo.com/ows/s/77c4ab4d358d47e9aff30b550df007f9/c/27fb10c606ed40d89673130bb12b44ed/_O0ZrGFaAOC2XImyQb5UneFcyXLD0?service=CSW&version=2.0.2&request=GetCapabilities avec : 
- une donnée sur les stades avec de multiples ressources associées :
  - un WFS,
  - un Esri Feature,
  - un Esri Tile,
  - un lien de téléchargement des données brutes zippées (avec un shp dedans)
  -  un WMTS qui n'a rien à voir,
  - des liens d'infos supplémentaires,
  - voir sur un [OpenCatalog](http://open.isogeo.com/s/c502e8f7c9da4c3aacdf3d905672d54c/Q4SvPfiIIslbdwkbWRFJLk7XWo4G0/m/56ed291af72f46dc9835fc9ae29fe938),
- une donnée sur les polygones des cantons de France métropolitaine, Géofla 2013 :
  une thématique INSPIRE,
  - un WFS,
  - un WMS,
  - une donnée brute téléversée (shp zippé),
  - un lien d’info supplémentaire
  - voir sur un [OpenCatalog](http://open.isogeo.com/s/c502e8f7c9da4c3aacdf3d905672d54c/Q4SvPfiIIslbdwkbWRFJLk7XWo4G0/m/9dc817d4ed0b402697cfe1007a410f0c),
  - avec un mot-clé "données ouvertes",
  - avec une licence Etalab ou IGN service public,

**Comment by fxprunayre** [comment]
### Serveurs CSW testés:
- http://api.isogeo.com/services/ows/s/8f0d8215ef954b9bb1bfe095ea3b3087/c/4e26282808214c7484ad035d3a72e85c/cj4iFol3QCp3vDI8vIHqxd-zUoVp0?request=GetCapabilities&service=CSW&version=2.0.2
- http://www.rolnp.fr/geoportal/csw/discovery?request=GetCapabilities&service=CSW&version=2.0.2

### Test 1: GéoSource 3.0.2 (dev)

Configuration du moissonnage : 
- remarque: Pas de Queryable (pas de filtrage possible)
- Problème pour récupérer le GetCapabilities en fonction de ce que l'utilisateur utilise comme URL

eg. http://services.api.isogeo.com/ows/s/77c4ab4d358d47e9aff30b550df007f9/c/27fb10c606ed40d89673130bb12b44ed/_O0ZrGFaAOC2XImyQb5UneFcyXLD0?&service=CSW&version=2.0.2&request=GetCapabilities

retourne une exception :

```
<ExceptionReport xmlns="http://www.opengis.net/ows" version="1.2.0">
<Exception exceptionCode="NoApplicableCode">
<ExceptionText>Internal server error</ExceptionText>
<ExceptionText>
Object reference not set to an instance of an object.
</ExceptionText>
</Exception>
</ExceptionReport>
```

A priori, pas dramatique, mais pas de raison non plus de lever une exception dans ce cas là ? (Action ISOGEO ?)

Moissonnage ok sans filtre.
- isogeo http://apps.titellus.net/geonetwork/srv/eng/catalog.search#/search?facet.q=sourceCatalog%2Fb9f5d8a6-6de5-412a-8320-85714a136fad&resultType=details&from=1&to=20&sortBy=relevance&fast=index&_content_type=json
- rolnp http://apps.titellus.net/geonetwork/srv/eng/catalog.search#/search?facet.q=sourceCatalog%2Fb06d9371-aaf2-4def-bbe0-685aaffbc0f1&resultType=details&from=1&to=20&sortBy=relevance&fast=index&_content_type=json

### Test 2 : GéoSource 2.11.2 (version embarquée dans Prodige 3.4)

#### ESRI Geoportal

Test CSW ROLNP (ESRI): Erreur lors de la sauvegarde de la configuration

```
400 (Cannot build ServiceRequest Cause : Error on line 1: The prefix "apiso" for element "apiso:Subject" is not bound. Error : org.jdom.input.JDOMParseException)
```

Corrigé en GN 3.0.0RC0 cf. https://github.com/geonetwork/core-geonetwork/issues/548 (Action PRODIGE ? reporter le correctif et/ou Action GéoSource : faire un GS2.11.3 avec le correctif ?)

#### ISOGEO

Test CSW Isogeo: erreur lors du moissonnage:

```
2015-08-30 13:22:52,547 WARN  [isobob] - Raised exception when searching : java.lang.NullPointerException
2015-08-30 13:22:52,888 WARN  [isobob] - Raised exception when searching : org.fao.geonet.csw.common.exceptions.InvalidParameterValueEx: code=InvalidParameterValue, locator=typenames, message=Invalid parameter value
2015-08-30 13:22:52,888 ERROR [isobob] - Unknown error trying to harvest
2015-08-30 13:22:52,888 ERROR [isobob] - Raised exception when searching: Invalid parameter value
2015-08-30 13:22:52,888 ERROR [isobob] - Raised exception when searching: Invalid parameter value
OperationAbortedEx : Raised exception when searching: Invalid parameter value
    at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.doSearch(Harvester.java:548)
    at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.search(Harvester.java:257)
    at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.harvest(Harvester.java:100)
    at org.fao.geonet.kernel.harvest.harvester.csw.CswHarvester.doHarvest(CswHarvester.java:173)

```

##### Ce qui se passe en détail:
1. Le moissonneur tente en HTTP/GET : erreur car aucun critère ne peut être définit côté ISOGEO (no Queryables - cf. test1) ce qui entraîne une NullPointerException. (Action GN/GS : https://github.com/geonetwork/core-geonetwork/issues/1162)
2. Le moissonneur tente en HTTP/POST (car certaines implémentations disent supporter GET et ne le supportent pas dans la pratique en fonction du type de ConstraintLanguage) 
3. La requête envoyée

```
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:dc="http://purl.org/dc/elements/1.1/" service="CSW" version="2.0.2" resultType="results" outputFormat="application/xml" outputSchema="http://www.isotc211.org/2005/gmd" startPosition="1" maxRecords="20">
  <csw:Query typeNames="gmd:MD_Metadata,csw:Record">
    <csw:ElementSetName>summary</csw:ElementSetName>
  </csw:Query>
</csw:GetRecords>
```
- La réponse d'ISOGEO

```
<ExceptionReport xmlns="http://www.opengis.net/ows" version="1.2.0">
  <Exception exceptionCode="InvalidParameterValue" locator="typenames">
    <ExceptionText>Invalid parameter value</ExceptionText>
  </Exception>
</ExceptionReport>
```

= Le moissonnage s'arrête.

##### Analyse:

Dans le GetCapabilities, les typename csw:Record & gmd:MD_Metadata sont supportés. Cf.

![image](https://cloud.githubusercontent.com/assets/1701393/9567086/723930e8-4f1e-11e5-9065-6280c081b153.png)

Dans la spec OGC 07-045

![image](https://cloud.githubusercontent.com/assets/1701393/9567088/8cdcb708-4f1e-11e5-90a4-28e507415a64.png)

La requête avec typeNames="gmd:MD_Metadata,csw:Record" retourne l'erreur:

![image](https://cloud.githubusercontent.com/assets/1701393/9567091/95ee38bc-4f1e-11e5-9a9d-775b68196fa1.png)

La requête avec typeNames="gmd:MD_Metadata" retourne l'erreur:

![image](https://cloud.githubusercontent.com/assets/1701393/9567098/b6a1c8f8-4f1e-11e5-845c-e12c84878727.png)

La requête avec typeNames="csw:Record" retourne une réponse:

![image](https://cloud.githubusercontent.com/assets/1701393/9567099/b9808988-4f1e-11e5-97cf-1a8e5992e802.png)

Par contre, en HTTP/GET
http://services.api.isogeo.com:80/ows/s/77c4ab4d358d47e9aff30b550df007f9/c/27fb10c606ed40d89673130bb12b44ed/_O0ZrGFaAOC2XImyQb5UneFcyXLD0?request=GetRecords&service=CSW&version=2.0.2&resultType=results&namespace=xmlns(csw=http://www.opengis.net/cat/csw/2.0.2),xmlns(gmd=http://www.isotc211.org/2005/gmd)&outputFormat=application/xml&outputSchema=http://www.isotc211.org/2005/gmd&startPosition=1&maxRecords=20&elementSetName=summary&typeNames=gmd:MD_Metadata,csw:Record
ou typeNames=gmd:MD_Metadata ou typeNames=csw:Record retourne toujours la même réponse (et pas d'erreur). Alors que les requêtes sont a priori équivalentes ?

A priori, les 3 requêtes devraient retourner la même chose (si pour ISOGEO un enregistrement ISO19139 peut être mappé en csw:Record dans ce cas gmd:MD_Metadata,csw:Record = gmd:MD_Metadata = csw:Record) en HTTP/POST et HTTP/GET ? Action ISOGEO ?

#### En complément

En v3, ce paramètre peut être personnalisé dans la configuration du moissonneur par l'utilisateur et pourrait également permettre de contourner le problème des réponses différentes en POST/GET côté ISOGEO :
![image](https://cloud.githubusercontent.com/assets/1701393/9567105/e5a22260-4f1e-11e5-92b3-eaddab226a39.png)

**Comment by mcartoixa** [comment]
@fxprunayre Pour ce qui concerne Isogeo :
- Test 1 : lors de l'analyse des paramètres de l'URL, le token _?&_ (est-ce du HTTP valide ?) se résoud en un paramètre vide. Un problème de tests de valeurs limites du côté d'Isogeo déclenche une exception serveur, non gérée. Pour l'instant.
- Test 2 : la requête POST est invalide. Selon le standard XML, il faut déclarer le préfixe _gmd_ avant de pouvoir s'en servir. La requête GET fonctionne parce que le namespace est déclaré...

**Comment by fxprunayre** [comment]
en effet pour gmd:MD_Metadata

```
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:dc="http://purl.org/dc/elements/1.1/" service="CSW" version="2.0.2" resultType="results" outputFormat="application/xml" 
 outputSchema="http://www.isotc211.org/2005/gmd" startPosition="1" maxRecords="20">
  <csw:Query typeNames="gmd:MD_Metadata">
    <csw:ElementSetName>summary</csw:ElementSetName>
  </csw:Query>
</csw:GetRecords>
```

retourne 

```
<GetRecordsResponse>
<SearchStatus timestamp="2015-08-31T07:52:02.8621887Z" />
 <SearchResults numberOfRecordsMatched="6" numberOfRecordsReturned="6" nextRecord="0">
 <gmd:MD_Metadata>
```

par contre (fait par geosource sur la base du getcapabilities - sans le xmlns:gmd Action GeoSource à ajouter)

```
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:dc="http://purl.org/dc/elements/1.1/" service="CSW" version="2.0.2" resultType="results" outputFormat="application/xml" 
 outputSchema="http://www.isotc211.org/2005/gmd" startPosition="1" maxRecords="20">
  <csw:Query typeNames="gmd:MD_Metadata,csw:Record">
    <csw:ElementSetName>summary</csw:ElementSetName>
  </csw:Query>
</csw:GetRecords>
```

retourne

```
<ExceptionReport version="1.2.0">
<Exception exceptionCode="InvalidParameterValue" locator="typenames">
<ExceptionText>Invalid parameter value</ExceptionText>
</Exception>
</ExceptionReport>
```

Action GN/GS https://github.com/geonetwork/core-geonetwork/issues/1163

**Comment by mcartoixa** [comment]
Je dois retrouver les références exactes, mais de tête : ce champ est déclaré comme une liste dans le schéma XML. Or en XML le séparateur de listes est un espace, pas une virgule.

**Comment by fxprunayre** [comment]
En effet cf. http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd:

```
  <xsd:simpleType name="TypeNameListType" id="TypeNameListType">
      <xsd:annotation>
         <xsd:documentation xml:lang="en">The exact syntax is defined in an application profile. If querying 
       against the common record properties, only a single type may be 
       specified (Record).</xsd:documentation>
      </xsd:annotation>
      <xsd:list itemType="xsd:QName"/>
   </xsd:simpleType>
```

Requête modifiée:

```
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:dc="http://purl.org/dc/elements/1.1/" service="CSW" version="2.0.2" resultType="results" outputFormat="application/xml" 
 outputSchema="http://www.isotc211.org/2005/gmd" startPosition="1" maxRecords="20">
  <csw:Query typeNames="gmd:MD_Metadata csw:Record">
    <csw:ElementSetName>summary</csw:ElementSetName>
  </csw:Query>
</csw:GetRecords>
```

**Comment by fxprunayre** [comment]
Donc récap:
- GN3 > GS3 (nice to have - ca marche sans)
  - https://github.com/geonetwork/core-geonetwork/issues/1162
  - https://github.com/geonetwork/core-geonetwork/issues/1163
- Prodige : 
  - GS2.11.3 (car a priori pas prévu de passer à GS3) avec:
  - backport fix Geoportal (https://github.com/geonetwork/core-geonetwork/issues/548) 
  - \+ https://github.com/geonetwork/core-geonetwork/issues/1162
  - \+ (nice to have) https://github.com/geonetwork/core-geonetwork/issues/1163
  - \+ mettre à jour GéoSource côté Prodige

**Comment by fxprunayre** [comment]
En 2.11.x, également problème avec http://www.geocatalogue.fr/api-public/inspire/servicesRest? sans critère (en lien avec https://github.com/geonetwork/core-geonetwork/issues/1162).

**Comment by taffoureau** [comment]
Tests sur Géosource 2.11.3 (ie 2.11.2 + correctifs moissonnage):

http://api.isogeo.com/services/ows/s/8f0d8215ef954b9bb1bfe095ea3b3087/c/4e26282808214c7484ad035d3a72e85c/cj4iFol3QCp3vDI8vIHqxd-zUoVp0?request=GetCapabilities&service=CSW&version=2.0.2
=> Moissonnage OK

http://www.rolnp.fr/geoportal/csw/discovery?request=GetCapabilities&service=CSW&version=2.0.2
=> Moissonnage OK

**Comment by fxprunayre** [comment]
Pour GéoSource 2.11 de Prodige reporter les commits:
- https://github.com/geosource-catalogue/core-geonetwork/commit/dad5f6da116b5256b07a537b4a6b9372798cb74d (nouvelle demande en lien avec les xlinks, non lié au CSW)
- https://github.com/geosource-catalogue/core-geonetwork/commit/6fa70af28393893ad9d715d09a55abc754090718
- https://github.com/geosource-catalogue/core-geonetwork/commit/a29501381b50399bb241e9495c58dc083267d6ee

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/1279

PR améliorant également l'interface de configuration du moissonneur CSW avec des messages pour les cas:
- pas de Queryable
- URL inaccessible

PR appliquée à GN3.0.x

**Comment by fxprunayre** [comment]
Amélioration du support des typeNames et outputSchema en fonction des plugins chargés dans le catalogue https://github.com/geonetwork/core-geonetwork/pull/1280

**Comment by fxprunayre** [comment]
A tester et fermer si ok.
