### ISSUE TITLE
[2.9.2] Mise à jour des contacts liés suite à modfiication dans l'annuaire

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#26]
Scénario :
Ajout d'un contact lié dans une fiche depuis un annuaire, puis modification du contact dans la gestion des annuaires (nom de l'organisation) --> la modification n'est pas reportée dans la fiche.

**Comment by fxprunayre** [comment]
Aller dans admin > vider le cache de XLinks (comme d'habitude)

![image](https://f.cloud.github.com/assets/1701393/1966396/dddf2890-82c7-11e3-9257-8b32564a1ef7.png)

**Comment by fxprunayre** [comment]
Evolutions : Vider le cache pour les éléments modifiés dans l'édition.

**Comment by fxprunayre** [comment]
Fait pour les mots clés https://github.com/geonetwork/core-geonetwork/pull/477
