### ISSUE TITLE
[2.9.2] Message d'avertissement lors d'une réindexation

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#27]
Lors d'une action de réindexation, aucun message n'apparaît dans l'interface ni en réponse à une requête CSW.

**Comment by fxprunayre** [comment]
Le développement fait pas akka n'était pas fait pour toutes les langues dans l'interface (et n'a donc pas été porté dans GN). Un message n'est retourné que pour les requêtes CSW et a priori c'est ok :

![image](https://f.cloud.github.com/assets/1701393/1966414/28ac7d8c-82c8-11e3-8e02-59bf49a22970.png)

**Comment by taffoureau** [comment]
Et dans l'interface de recherche?
