### ISSUE TITLE
[2.9.2] Lien vers une recherche pré-définie

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#29]
Les critères sont bien définis dans l'URL mais la recherche n'est pas automatiquement exécutée.

Exemple : http://geosourcetest.brgm-rec.fr/geosource/apps/search/?east_collapsed=true&s_search=&s_E_any=carte&s_timeType=true&s_scaleOn=false&s_O_inspirerelated=false&s_E_hitsperpage=20&hl=fre&extent=-550000,5000000,1200000,7000000

**Comment by fxprunayre** [comment]
Des erreurs JS dans la console ?

**Comment by fxprunayre** [comment]
Non reproductible. A fermer ?
