### ISSUE TITLE
Id de ressource unique / Accès aux métadonnées par identifiant de la resource

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#3]
Permettre l'accès à une fiche en consultation par l'identifiant de la ressource unique

**Comment by taffoureau** [comment]
en XML --> à faire dans une version 2.11.1

**Comment by fxprunayre** [comment]
Mise en place d'une réécriture d'URL sur
http://localhost:8080/geonetwork/srv/61d82845-9ee0-4531-936b-f30667582e2f
devient 
http://localhost:8080/geonetwork/srv/fre/xml.metadata.get?uuid=61d82845-9ee0-4531-936b-f30667582e2f

Non appliqué à GN (car il faudrait gérer la problèmatique de la langue).

@taffoureau Tu confirmes qu'on retourne la version XML de la fiche ?

**Comment by taffoureau** [comment]
Oui, je confirme. Par contre, le lien généré (eg http://moncataloguegeosource.fr/geosource/ee3ee015-6a97-438f-8a56-7d2007487566) n'aboutit pas (la fiche est bien publiée dans le catalogue).

**Comment by fxprunayre** [comment]
Il faut que tu configures le préfixe avec l'identifiant du noeud ?
(eg http://moncataloguegeosource.fr/geosource/srv/ee3ee015-6a97-438f-8a56-7d2007487566)

**Comment by taffoureau** [comment]
Oups, en effet ça marche beaucoup mieux! J'avais testé la bonne url mais à un moment où la fiche n'était pas publiée...

**Comment by fxprunayre** [comment]
Oui, il faut que la fiche soit publique sinon tu dois avoir une erreur de type service not allowed ou quelquechose de ce genre.
