### ISSUE TITLE
[2.9.2] Ajout d'un mot-clé lié à partir d'un thésaurus

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#30]
l'URL stockée dans l'attribut xlinkhref (paramètre id) est étrange : http://geosourcetest.brgm-rec.fr:80/geosource/srv/fre/xml.keyword.get?thesaurus=external.theme.PnrMCB&amp;amp;id=file:///applications/geosource/web/geonetwork/xml/codelist/local/thesauri/theme/PnrMCB.rdf%23EAU_conchy&amp;amp;multiple=false

Par ailleurs, l'URL est incorrecte (cf anomalie remontée précédemment).

**Comment by fxprunayre** [comment]
Les identifiants des concepts devraient plutôt être du genre "http://www.mysite.org/thesaurus#1390333117053" ou  "http://www.mysite.org/thesaurus/1390333117053". Le thésaurus ne semble pas être "local" puisque sont identifiants est external.theme.PnrMCB. Pouvez vous corriger le thésaurus ?

**Comment by fxprunayre** [comment]
Après test du thésaurus même avec des identifiants file:// ca joue.

![image](https://f.cloud.github.com/assets/1701393/2038068/d7f6f144-8982-11e3-8ef4-bd250ecc9d33.png)

Quoiqu'il en soit, ça pourrait être bien de revoir les id des concepts.
