### ISSUE TITLE
[2.9.2] Alerte mot de passe incorrect

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#31]
Aucun message d'erreur n'apparaît lorsque le mot de passe saisi est incorrect

**Comment by fxprunayre** [comment]
![image](https://f.cloud.github.com/assets/1701393/1966971/73ff3d9a-82cf-11e3-9da0-5c65745ac58a.png)

Je ne reproduis pas. Tu peux préciser le cas - navigateur ?

**Comment by fxprunayre** [comment]
Reproductible. Pas de solution simple à première vue. Est ce que ca vous va si corrigé en 2.11 uniquement ?
