### ISSUE TITLE
[2.9.2] Pb gestion des logos

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#32]
Comportements étrange dans la configuration des logos :

Il est impossible de supprimer les logos pré-existants
Chemin vers les images logos :
Infos système : /applications/tomcat-6.0-instance10/data/data/resources
emplacement logos : /applications/tomcat-6.0-instance10/data/data/resources/images/logos
Aucune erreur n'apparaît dans les logs.

La fonction "Utiliser comme icône du site" n'a pas l'air de fonctionner, même en supprimant le cache du navigateur.

Le bouton "téléchargement" pour l'ajout de nouveaux logos n'apparaît pas dans Firefox (version 26.0).

**Comment by fxprunayre** [comment]
Non reproductible sous Jetty, à tester sous tomcat

**Comment by fxprunayre** [comment]
Problème de suppression des logos initiaux : https://github.com/geonetwork/core-geonetwork/issues/363

**Comment by fxprunayre** [comment]
> Le bouton "téléchargement" pour l'ajout de nouveaux logos n'apparaît pas dans Firefox (version 26.0).

Ce sera corrigé dans la 2.11. Contournement réduire fortement la taille de la police / utiliser chrome ou IE

**Comment by taffoureau** [comment]
Corrigé.
