### ISSUE TITLE
CSW virtuels - Critère échelle - Préciser "Dénominateur"

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#34]

**Comment by fxprunayre** [comment]
C'est à dire ?

**Comment by fxprunayre** [comment]
Fait dans la nouvelle interface d'admin https://github.com/geonetwork/core-geonetwork/commit/7d6bb256792dbb75eefcbd4a215d62f6d29f73d1#diff-efd7cfbb87140f296d1b01ac307f74edR516

**Comment by taffoureau** [comment]
Fait.
