### ISSUE TITLE
[2.9.2] Réponse csw-GetRecords | no filter | outputschema:fra:isoRecords

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#36]
```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="InvalidParameterValue" locator="outputSchema">
    <ows:ExceptionText>fra:IsoRecord</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

**Comment by fxprunayre** [comment]
Est-il nécessaire de supporter le profil France en sortie de CSW ? L'exemple est un peu vieux - on le supprime ? Si vous souhaitez avoir les fiches dans leur forme d'origine, utiliser outputSchema="own"

**Comment by taffoureau** [comment]
On supprime.

**Comment by fxprunayre** [comment]
Fixed in GN 2.10 (https://github.com/geonetwork/core-geonetwork/commit/3f8588f81feafc08175ff38b7ba98cfaba9243cc) & develop (https://github.com/geonetwork/core-geonetwork/commit/fb32bb874e71247d3aea769b1f5022b66efea083)
