### ISSUE TITLE
[2.9.2] Réponse csw-GetRecords | filter | ogc:Equals+bbox-90,-180 90,180

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#38]
Aucun résultat alors qu'une fiche publiée contient l'emprise mondiale (cf capture)
![nouvelle image](https://f.cloud.github.com/assets/2026724/1964970/918c780c-82b4-11e3-9482-53a7d5932ef2.png)

**Comment by fxprunayre** [comment]
Sans doute en lien avec https://github.com/geonetwork/core-geonetwork/issues/230
