### ISSUE TITLE
[2.9.2] csw-Transaction | update full records

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#41]
Le fichier XML en exemple ne contient pas de namespace (eg le titre).

**Comment by fxprunayre** [comment]
Beh si : 

```
<MD_Metadata xmlns="http://www.isotc211.org/2005/gmd"
=
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd"
```

namespace par défaut. Quel est le pb ?

**Comment by fxprunayre** [comment]
On ajoute les préfixes à l'exemple.

**Comment by taffoureau** [comment]
Action FXP ?

**Comment by fxprunayre** [comment]
GN issue : https://github.com/geonetwork/core-geonetwork/issues/372

Corrigé dans GN trunk, 2.10.x & GS 2.9.2. Disponible dans le nouveau WAR.
