### ISSUE TITLE
[2.9.2] Agrégation / navigation bidirectionnelle

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#45]
affichage des relations d'agrégation (jeu de données <-> lot de données) dans les résultats de recherche

**Comment by fxprunayre** [comment]
https://github.com/geonetwork/core-geonetwork/issues/335

**Comment by taffoureau** [comment]
Fonctionne lorsque le lien est réalisé en édition, mais pas à l'import de deux métadonnées aggrégées.

**Comment by fxprunayre** [comment]
En effet, le pb vient du fait qu'il n'y a pas de section distribution dans la fiche.

2 options :
- suppression de cette limitation
- avoir comme hypothèse qu'il y a toujours une section distribution (cf. INSPIRE)

@taffoureau tu en penses quoi ? J'opte pour la première.

**Comment by fxprunayre** [comment]
See https://github.com/geonetwork/core-geonetwork/issues/368

**Comment by fxprunayre** [comment]
Appliqué à GN 2.10, trunk et GS 2.9.2

**Comment by taffoureau** [comment]
On supprime la limitation.

De : François Prunayre [mailto:notifications@github.com]
Envoyé : lundi 27 janvier 2014 19:03
À : geosource-catalogue/core-geonetwork
Cc : Taffoureau Etienne
Objet : Re: [core-geonetwork] [2.9.2] Agrégation / navigation bidirectionnelle (#45)

En effet, le pb vient du fait qu'il n'y a pas de section distribution dans la fiche.

2 options :
-   suppression de cette limitation
-   avoir comme hypothèse qu'il y a toujours une section distribution (cf. INSPIRE)

@taffoureauhttps://github.com/taffoureau tu en penses quoi ? J'opte pour la première.

—
Reply to this email directly or view it on GitHubhttps://github.com/geosource-catalogue/core-geonetwork/issues/45#issuecomment-33402180.
P Pensez à l'environnement avant d'imprimer ce message
       Think Environment before printing

Le contenu de ce mél et de ses pièces jointes est destiné à l'usage exclusif du (des) destinataire(s) désigné(s) comme tel(s).
En cas de réception par erreur, le signaler à son expéditeur et ne pas en divulguer le contenu.
L'absence de virus a été vérifiée à l'émission, il convient néanmoins de s'assurer de l'absence de contamination à sa réception.

The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only.
If you have received this email in error please notify the system manager or  the sender immediately and do not disclose the contents to
anyone or make copies.
This email was scanned for viruses, vandals and malicious content.

**Comment by taffoureau** [comment]
Non corrigé dans la version livrée le 29/01. Les relations n'apparaissent toujours pas dans le cas des fichiers jdd.xml et ldd.xml

**Comment by fxprunayre** [comment]
Ici ca marche bien. Tu peux vérifier le fichier WEB-INF/data/config/schema_plugins/iso19139/present/metadata-view.xsl qu'il contienne bien les changements https://github.com/geonetwork/core-geonetwork/commit/c61ac3107f1bfb01073dd3ac5004419df7ee6c4d

**Comment by taffoureau** [comment]
Corrigé. Les fichiers dans schema_plugins n'avaient pas été mis à jour dans mon data.directory.
