### ISSUE TITLE
Associer un jeux de données

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#47]
En édition, dans ressources associées, il est proposé d' "associer un jeux de données"

Supprimer le "x"

Est-ce nécessaire de le proposer dans les métadonnées de données? Cela ne concerne-t-il pas uniquement les services ?

Idem pour "Associer un service" en édition d'un service...

**Comment by fxprunayre** [comment]
> En édition, dans ressources associées, il est proposé d' "associer un jeux de données"

See https://github.com/geosource-catalogue/core-geonetwork/commit/efdfdc03e4b4df82a1f94aa0ad505b9669ca3940

> Est-ce nécessaire de le proposer dans les métadonnées de données? Cela ne concerne-t-il pas uniquement les services ?

@taffoureau En 2.11 uniquement, ca te convient ?

**Comment by taffoureau** [comment]
Ca me convient.

De : François Prunayre [mailto:notifications@github.com]
Envoyé : lundi 27 janvier 2014 19:24
À : geosource-catalogue/core-geonetwork
Cc : Taffoureau Etienne
Objet : Re: [core-geonetwork] Associer un jeux de données (#47)

En édition, dans ressources associées, il est proposé d' "associer un jeux de données"

See efdfdc0https://github.com/geosource-catalogue/core-geonetwork/commit/efdfdc03e4b4df82a1f94aa0ad505b9669ca3940

Est-ce nécessaire de le proposer dans les métadonnées de données? Cela ne concerne-t-il pas uniquement les services ?

@taffoureauhttps://github.com/taffoureau En 2.11 uniquement, ca te convient ?

—
Reply to this email directly or view it on GitHubhttps://github.com/geosource-catalogue/core-geonetwork/issues/47#issuecomment-33404222.
P Pensez à l'environnement avant d'imprimer ce message
       Think Environment before printing

Le contenu de ce mél et de ses pièces jointes est destiné à l'usage exclusif du (des) destinataire(s) désigné(s) comme tel(s).
En cas de réception par erreur, le signaler à son expéditeur et ne pas en divulguer le contenu.
L'absence de virus a été vérifiée à l'émission, il convient néanmoins de s'assurer de l'absence de contamination à sa réception.

The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only.
If you have received this email in error please notify the system manager or  the sender immediately and do not disclose the contents to
anyone or make copies.
This email was scanned for viruses, vandals and malicious content.

**Comment by taffoureau** [comment]
Corrigé.
