### ISSUE TITLE
Liste des types de ressource dans la recherche

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#48]
Depuis la version 2.10 de Geonetwork, la liste se met à jour automatiquement en fonction de ce qu'il y a dans les métadonnées.

Toutefois, les valeurs ne sont pas traduites (featureCatalog, feature, ...).

J'ai également une valeur étrange : service-view pour un service WMS. Or, j'ai également d'autres services WMS qui apparaissent en "service" alors qu'il contiennent la même valeur de serviceType (=view).

**Comment by fxprunayre** [comment]
Les valeurs sont indexées par https://github.com/geosource-catalogue/core-geonetwork/blob/2.9.2/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl#L553

Que contient la fiche dans gmd:hierarchyLevel/gmd:MD_ScopeCode/@codeListValue pour service-view ?
