### ISSUE TITLE
Edition de métadonnées depuis le menu Administration

### ISSUE THREAD

**Issue by delobelle** [geosource-catalogue/core-geonetwork#49]
1/ Création d'une nouvelle métadonnée
2/ Administration/Métadonnées : on retrouve la nouvelle métadonnée que l'on vient de créer : on l'édite pour la modifier. On sort de Geosource et on tombe sur l'interface GN

**Comment by fxprunayre** [comment]
Good catch! Fixed.

Sans objet en 2.11 car l'admin est différente.

**Comment by taffoureau** [comment]
Corrigé.
