### ISSUE TITLE
Import des templates

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#51]
Après import de templates, le message de confirmation est hors-champ sur mon écran, du coup on a tendance à recliquer et à réimporter plusieurs fois les mêmes templates.

L'idéal serait de ne pas importer un template qui l'est déjà.

**Comment by fxprunayre** [comment]
2 colonnes

**Comment by fxprunayre** [comment]
https://github.com/geonetwork/core-geonetwork/commit/462a9e113b42a733b0db3331c8855d2293674433

**Comment by taffoureau** [comment]
Corrigé.
