### ISSUE TITLE
Boutons de suppression de certains champs non disponibles

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#55]
Par exemple, le template "Modèle pour la saisie d'une série de données INSPIRE" contient plusieurs mots-clés non supprimables (les boutons de suppression ne sont pas affichés).

**Comment by taffoureau** [comment]
Champs concernés:
Encodage
Mot-clé
référentiel de coordonnées
Dates de référence

**Comment by fxprunayre** [comment]
> Encodage

Ajouté.

> Mot-clé

A voir comment faire.

> référentiel de coordonnées

a priori ok :
![image](https://cloud.githubusercontent.com/assets/1701393/2593599/1d2afcde-ba83-11e3-854d-edfb6bf7fe07.png)

> Dates de référence

Si les dates ne sont pas remplies, elles ne sont pas sauvegardées dans la fiche.

**Comment by taffoureau** [comment]
Corrigé.
