### ISSUE TITLE
Champ conformité dans la vue INSPIRE

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#56]
Les champs title et pass ne sont pas traduits.

Le champ explanation ne doit pas être présent.

Le calendrier n'est pas accessible pour la saisie de la date.

Le champ pass doit être sous la forme d'une liste déroulante avec les trois valeurs : 
Conforme
Non conforme
Non évalué
Or, dans le template "Modèle pour la saisie d'une série de données INSPIRE" la valeur "1" est contenue dans un champ texte.

La valeur "other" en fin de liste des spécifications doit être traduite.

**Comment by fxprunayre** [comment]
> Le champ explanation ne doit pas être présent.
> Les champs title et pass ne sont pas traduits.

99758591c09301e64017e8187cb5a40a4d1cceba

> La valeur "other" en fin de liste des spécifications doit être traduite.

7996b3a5d62de1571da96d30802aa83a7a6f3341

**Comment by fxprunayre** [comment]
> Le champ pass doit être sous la forme d'une liste déroulante avec les trois valeurs : 

Je propose cette approche :
- Non évalué 

![image](https://f.cloud.github.com/assets/1701393/2228027/b7f21a34-9ad2-11e3-98bb-24d8d9196782.png)
- Évalué

![image](https://f.cloud.github.com/assets/1701393/2227993/2e592c72-9ad2-11e3-8d68-96a43ed736a9.png)

Cela permet d'avoir un mécanisme générique pour n'importe quel champ de l'éditeur. Si le champ demandé n'est pas dans la fiche en cours d'édition alors le "missing label" est affiché avec une checkbox pour afficher le/les champs à saisir.

La config se fait de la manière suivante : https://github.com/geonetwork/core-geonetwork/blob/6d91ca0e2d61296a421b881aaccc16d18b185bb2/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/layout/config-editor.xml#L707

**Comment by taffoureau** [comment]
OK, dans ce cas je propose quelque modification :
1) Une fois "non évalué" décoché, modifier le label en "Evalué" et le cocher.
2) Degré : le remplacer par "Conforme/Non conforme?" situé à droite du bouton-radio, en non gras et laisser de l'espace entre les deux (cf. point 1)
3) Supprimer le champ explanation

**Comment by taffoureau** [comment]
Je n'arrive pas à voir l'option "non évalué", par défaut j'ai uniquement le libellé "conformité" avec le bouton +

Lorsque je clique dessus j'ai les champ "specification" avec les boutons radios qui apparaissent et si je clique sur "supprimer" je reviens à l'étape précédente sans l'option "non évalué"

**Comment by fxprunayre** [comment]
Elle devrait si aucune conformité dispo dans la fiche :
![image](https://cloud.githubusercontent.com/assets/1701393/3272949/823a4a3e-f31e-11e3-99ef-4b99af8307e6.png)

et s'il y a une conformité, cliquer sur la croix pour supprimer la section
![image](https://cloud.githubusercontent.com/assets/1701393/3272983/e5d13396-f31e-11e3-9e8a-f0a741be496e.png)

**Comment by taffoureau** [comment]
OK. En fait il faut cliquer sur "enregistrer" puis rafraichir la page pour voir apparaître cet élément.

A l'inverse, cette action est également nécessaire pour voir apparaître les listes à puce après avoir décoché "non évalué"

**Comment by fxprunayre** [comment]
Sur la sauvegarde > rafraîchir la vue en cours. https://github.com/geonetwork/core-geonetwork/commit/65c6f81236b354b45a1b7420ecfe47bc45f8e3c9

**Comment by taffoureau** [comment]
Non corrigé a priori?
