### ISSUE TITLE
Emprise géographique

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#59]
Dans la liste des systèmes de coordonnées, proposer les valeurs avec les intitulés suivants :
WGS84 (EPSG:4326) --> par défaut
Lambert 93 (EPSG:2154)
Google mercator (EPSG:3857)

Pour resaisir une emprise après une 1ère saisie, il est nécessaire de cliquer deux fois sur le bouton "dessiner une emprise". De plus, l'état du bouton actif/non actif n'est pas suffisamment visible.

Pour le choix du thésaurus, comment cela se configure ? N'est-il pas plus simple de rechercher dans l'ensemble des thésaurus de type "place" ? Cela poserait-il un problème de performance pour les communes ?

Modifier le texte dans la zone de saisie de "Choisir une région" en "Choisir un territoire"

**Comment by fxprunayre** [comment]
Suite à la suppression d'une emprise, le libellé n'est pas visible en face du bouton "+"

**Comment by fxprunayre** [comment]
> Modifier le texte dans la zone de saisie de "Choisir une région" en "Choisir un territoire"

8cad43fc86b8ba9a045266a129d6f5eea3d40633

**Comment by fgravin** [comment]
> Pour resaisir une emprise après une 1ère saisie, il est nécessaire de cliquer deux fois sur le bouton "dessiner une emprise". De plus, l'état du bouton actif/non actif n'est pas suffisamment visible.

En fait c'est un toggle, si on clique une fois on peut redessiner tant qu'on veut, si on reclique une seconde fois on repasse en mode 'pan'.
J'ai modifié le style du bouton lorsqu'il est actif.

> WGS84 (EPSG:4326) --> par défaut
> Google mercator (EPSG:3857)

J'ai aussi rajouté des labels pour les projections

https://github.com/geonetwork/core-geonetwork/commit/76a194d13a10dc804a307cc66484f03ffc3c26be

**Comment by fxprunayre** [comment]
Merci @fgravin . Le toggle ca me va ( @taffoureau ok pour toi ?). 

Par contre si on bascule dans une autre projection, les coordonnées ne sont plus sauvés en WGS84 mais dans la projection choisie.

**Comment by fgravin** [comment]
Ok j'ai corrigé l'histoire de proj4js, le projection dans la métadonnée, et j'ai amélioré le layout

https://github.com/geonetwork/core-geonetwork/commit/f9c3e262474b73597f0a9e05b4051a2ba2d07b1d

**Comment by taffoureau** [comment]
OK
