### ISSUE TITLE
Administration / Mise à jour du site propose de mettre à jour les fiches

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#6]
Lors de la modification de l’adresse du catalogue dans la configuration du système, il est
proposé à l’administrateur de mettre à jour les informations des fiches liées à cette
adresse. C’est le cas :
- de l’identifiant de la ressource
- des URL des fichiers uploadés
- des imagettes
- des XLinks

Un processus s’occupe de mettre à jour l’ensemble de ces URL pour les fiches (modèles et métadonnées) du catalogue (ie. n’inclu pas les fiches moissonnées). Ce processus pourra être exécuté depuis l’interface d’administration

**Comment by fxprunayre** [comment]
![image](https://f.cloud.github.com/assets/1701393/1975142/97ffd024-8379-11e3-9c3b-8be98f0fc6b1.png)

**Comment by fxprunayre** [comment]
Appliqué à GN https://github.com/geonetwork/core-geonetwork/commit/789e37e918d02a9f1289a9ddfc597055cc47c038

**Comment by taffoureau** [comment]
OK.
