### ISSUE TITLE
Valeurs du rôle du contact

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#61]
Les rôles doivent être limités aux valeurs suivantes :

Point de contact (pointOfContact) (valeur par défaut)
Propriétaire (owner)
Gestionnaire (custodian)
Auteur (author)
Fournisseur (resourceProvider)

**Comment by taffoureau** [comment]
OK pour la saisie manuelle d'un contact. A repréciser dans le cas de l'ajout depuis un annuaire (cf. https://github.com/geosource-catalogue/core-geonetwork/issues/149)
