### ISSUE TITLE
Point de contact des métadonnées

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#63]
Supprimer le libellé principal "Point de contact des métadonnées" sous "Métadonnées".

Remplacer "organisation" par "point de contact".

Supprimer le rôle.

**Comment by fxprunayre** [comment]
ae76af9784e20c7bc5ce0cfc0786acb79eff0c5b

**Comment by taffoureau** [comment]
OK pour les deux premiers points.

Le 3ème ne peut être testé car aucun contact n'est affiché après action "Ajouter" (y compris depuis l'annuaire). Fonctionne dans le cas du contact sur la ressource.

**Comment by fxprunayre** [comment]
Ca me semble ok ?

**Comment by taffoureau** [comment]
changer:
nom du point de contact en nom de l'organisation
email du poinr de contact en email de l'organisation

Supprimer la liste des rôles pour l'ajout depuis l'annuaire (uniquement pou rles métadonnées)

**Comment by fxprunayre** [comment]
> Supprimer la liste des rôles pour l'ajout depuis l'annuaire.

uniquement pour le contact de la métadonnée

**Comment by taffoureau** [comment]
Non corrigé, la liste restreinte est toujours proposée. De plus, lorsqu'une valeur autre que "point de contact" est saisie le contact ajouté n'apparaît pas dans la vue INSPIRE (je la retrouve bien dans la vue complète).

**Comment by fxprunayre** [comment]
Afficher tous les contacts.

**Comment by fxprunayre** [comment]
Fait dans https://github.com/geosource-catalogue/core-geonetwork/commit/98e81bdacaf42d2c15662546f7915566263c3f41

**Comment by taffoureau** [comment]
corrigé.
