### ISSUE TITLE
Date des métadonnées

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#64]
Afficher la "Dernière mise à jour" en bas à droite conformément au cahier des charges.

**Comment by fxprunayre** [comment]
Date en lecture seule https://github.com/geonetwork/core-geonetwork/commit/3b7265b2ea8f9f88e03f3460d148f9fc5148337c

**Comment by taffoureau** [comment]
OK pour laisser la date de mise à jour au même niveau que les autres champs.
