### ISSUE TITLE
Validation - Afficher uniquement les erreurs

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#65]
Le bouton "Afficher uniquement les erreurs" n'est pas suffisamment clair. Il faudrait soit faire ressortir davantage les états activé/désactivé soit changer le bouton en "Afficher tout" lorsqu'il est activé.

**Comment by fxprunayre** [comment]
6f00100543cbada22f333a0f2fb7f6de9f2a2b4f Ombre rendue moin transparente. A plus long terme, il pourrait être bien de créer un thème bootstrap (http://expo.getbootstrap.com/) pour GéoSource.

**Comment by taffoureau** [comment]
Corrigé.
