### ISSUE TITLE
Bouton "générer un identifiant"

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#66]
Le bouton "générer un identifiant pour la ressource" est trop décalé vers la droite. Il doit être plus proche du champ de saisie.

Le renommer en "Générer un identifiant"

**Comment by fxprunayre** [comment]
> Le renommer en "Générer un identifiant"

d22b764b888dab903c8c3c1970a945b032bc9ae4

**Comment by fxprunayre** [comment]
![image](https://f.cloud.github.com/assets/1701393/2208972/bbc1bb9a-9985-11e3-8d5b-bbc1d2ee4409.png)

Aligner sur le bord droit.

**Comment by taffoureau** [comment]
Dans mon catalogue, le bouton est situé à gauche (ce qui me va) mais n'est pas suffisamment rapproché du champ "identificateur de ressource unique" (cf copie d'écran).
![bouton_generer_identifiant](https://f.cloud.github.com/assets/2026724/2449080/9a71d6f4-aead-11e3-825d-29efa7c35a9b.png)

**Comment by fxprunayre** [comment]
![image](https://cloud.githubusercontent.com/assets/1701393/2580841/e4fc4d80-b9b1-11e3-9f03-7a21db25b1f3.png)
?
