### ISSUE TITLE
Thème INSPIRE

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#67]
Le section "GEMET - INSPIRE themes, version 1.0" et "nom du thésaurus" doit être remplacé par une simple liste déroulante contenant les 34 thèmes.

**Comment by fxprunayre** [comment]
A corriger dans la vue INSPIRE

**Comment by fxprunayre** [comment]
ce3c6cdf8bd84fc3d6f6c84eee1767392e32fd3f

**Comment by taffoureau** [comment]
Non corrigé.
Plusieurs problèmes :
- Dans les templates, l'affichage des thèmes INSPIRE est inchangé (mot-clé issu du thésaurus... avec des champs texte
- Une fois supprimé, le champ disparaît. Il faut le rajouter dans la vue complète
- Une fois ajouté, le mot-clé INSPIRE est bien ajouté dans la vue complète mais lorsqu'on retourne dans la vue INSPIRE le message d'erreur suivant apparaît :
  Attention ! Les mots clés ["Bâtiments"] n'ont pas été trouvés dans le thésaurus. Cela peut se produire lorsque les mots clés sont dans une langue qui n'est pas celle de l'interface. L'édition de mots clés multilingues n'est pas encore supportée. Ces mots clés sont cependant conservés dans la fiche sauf si vous supprimez cette section.

**Comment by fxprunayre** [comment]
> Dans les templates, l'affichage des thèmes INSPIRE est inchangé (mot-clé issu du thésaurus... avec des champs texte

Pb dans les modèles de saisie et dans le titre du thésaurus. cf #67 

> Une fois ajouté, le mot-clé INSPIRE est bien ajouté dans la vue complète mais lorsqu'on retourne dans la vue INSPIRE le message d'erreur suivant apparaît : Attention ! Les mots clés ["Bâtiments"

Je ne reproduis pas. Le message d'alerte est affiché si un mot clé dans la fiche n'est pas trouvé dans le thésaurus référencé. Le but étant de ne pas perdre l'information dans la fiche (car le champ est sinon contraint au valeur du thésaurus).

**Comment by fxprunayre** [comment]
Nouvelles modifs:
- Modifier la cardinalité : 1 seul thème INSPIRE.
- Une liste simple avec "thème INSPIRE" comme libellé

**Comment by fxprunayre** [comment]
> Modifier la cardinalité : 1 seul thème INSPIRE.

Fait.

> Une liste simple avec "thème INSPIRE" comme libellé

Le mieux serait d'avoir un titre de thésaurus multilingues et afficher le titre en français. Sinon, ce sera un hack.

**Comment by fxprunayre** [comment]
Ajouter un bouton pour ajouter si non présent.

**Comment by fxprunayre** [comment]
Fixed https://github.com/geosource-catalogue/core-geonetwork/commit/968a5aa0b994cecc1330b7c878d9dcffc951e684
