### ISSUE TITLE
Référentiel de coordonnées

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#68]
Ne pas proposer la liste complète des systèmes de projections (cf. cahier des charges) dans la liste déroulante.

**Comment by fxprunayre** [comment]
Suppression autocompletion CRS dans la vue INSPIRE.

**Comment by taffoureau** [comment]
Voir à l'usage si on fait quelque chose de plus simple avec la liste restreinte.
