### ISSUE TITLE
Organisation responsable de la ressource

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#69]
Supprimer le libellé principal "Organisation responsable de la ressource"

A quoi sert le bouton "+" situé entre le libellé et le champ texte ?

Dans la liste d'autocomplétion des contacts, les boutons ajouter (default mode et ajout xlink) sont trop proches des valeurs de contacts. De plus traduire le contenu des infobulles (add a link...).

La liste déroulante ne peut pas être refermée tant qu'une valeur n'a pas été sélectionnée.

**Comment by fxprunayre** [comment]
> Supprimer le libellé principal "Organisation responsable de la ressource"

https://github.com/geonetwork/core-geonetwork/commit/9732d5c8fffc826cadc3d873ac4488f72e07f8c4

> A quoi sert le bouton "+" situé entre le libellé et le champ texte ?

A ajouter un contact vide (correction erreur JS dans certains cas).

> De plus traduire le contenu des infobulles (add a link...).

https://github.com/geonetwork/core-geonetwork/commit/7884072b6e122edc31e946b0c14a81e5ef72f69e

> La liste déroulante ne peut pas être refermée tant qu'une valeur n'a pas été sélectionnée.

https://github.com/geonetwork/core-geonetwork/commit/161eae590848b891d898c88b2c7c73ed9354204e

**Comment by taffoureau** [comment]
Corrigé.
