### ISSUE TITLE
Id de ressource unique / calcul / relation MDD & MDS

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#7]
Règles de création dans la MDS:

```
<srv:operatesOn
uuidref="<identifiant_de_la_metadonnee>"
xlink:href="<identifiant_de_la_ressource>"/>
```

Si n identifiants de la ressource, utiliser le premier qui ne commence pas par l'host

Examples:
- mapbender:
  http://lists.osgeo.org/pipermail/mapbender_commits/2012-January/008097.html

```
$operatesOn->setAttribute("xlink:href", "http://".$_SERVER['HTTP_HOST']."/mapbender/php/mod_dataISOMetadata.php?outputFormat=iso19139&id=".$row_metadata['uuid']);
$operatesOn->setAttribute("uuidref", $row_metadata['datasetid']);
```
- INSPIRE IR :

```
<srv:operatesOn xlink:href="http://image2000.jrc.it#image2000_1_nl2_multi"/>
```
- ArcGIS portal http://resources.arcgis.com/en/help/arcgis-for-inspire/10.1/index.html#//014m000000nm000000

**Comment by taffoureau** [comment]
A améliorer dans une version 2.11.1

**Comment by fxprunayre** [comment]
Nous avions finalisé avant la sortie de la 2.11.1 non ? @taffoureau faut-il compléter quelquechose ?

**Comment by taffoureau** [comment]
cf. cahier des charges de la 2.11.1:

Dans la console d’administration, dans « Paramètres », ajouter un champ texte « Préfixe de l’identifiant INSPIRE » dans la section « Directive INSPIRE ». Dessous, ajouter une description :

« Cette information pourra être utilisée dans le formulaire de saisie pour construire l’identificateur de ressource unique INSPIRE. Le préfixe sera alors automatiquement complété avec l’identifiant de la fiche de métadonnées. Si le préfixe n’est pas défini, alors l’adresse du catalogue sera utilisée ».
=> à ajouter

Ajouter un contrôle sur la chaîne de caractère saisie (doit commencer par http).
=> ne fonctionne pas

Si ce champ est modifié, un bouton « Mettre à jour les fiches » est proposé, comme pour l’adresse du catalogue.
=> à ajouter

En édition (en vue INSPIRE), lorsque l’utilisateur clique sur le bouton « Générer un identifiant », les règles suivantes sont appliquées :
1)  Si un préfixe a été défini dans la configuration (cf. ci-dessus), alors l’identifiant est construit de cette manière : [préfixe][fileIdentifier]
=> OK
2)  Sinon, l’identifiant est construit à partir de l’adresse du catalogue (comportement actuel).
=> OK

Modifier la description du bouton « Générer un identifiant » en conséquence.
=> compléter la desription de la popup comme suit:
« Si un préfixe a été défini dans les paramètres, celui-ci sera utilisé à la place de l'URL du catalogue. »

Lorsque l’identificateur de ressource unique est construit à partir de l’adresse du catalogue, il doit permettre d’accéder à la fiche de métadonnées (cf. https://github.com/geosource-catalogue/core-geonetwork/issues/3).
=> j'obtiens une erreur 404. Cela devrait renvoyer vers la fiche XML.

**Comment by fxprunayre** [comment]
> Dans la console d’administration, dans « Paramètres », ajouter un champ texte « Préfixe de l’identifiant INSPIRE » dans la section « Directive INSPIRE ». Dessous, ajouter une description :
> => à ajouter

Nous avions mis cette option dans la section métadonnée (car a priori, ce n'est pas uniquement en lien avec INSPIRE) avec la description suivante :

![image](https://cloud.githubusercontent.com/assets/1701393/7231895/a45291cc-e778-11e4-9362-674cf894077b.png)

Ca convient ?

> Ajouter un contrôle sur la chaîne de caractère saisie (doit commencer par http).

Pourquoi pas, ce sera spécifique GéoSource.

> Si ce champ est modifié, un bouton « Mettre à jour les fiches » est proposé, comme pour l’adresse du catalogue.

Fait.

> Modifier la description du bouton « Générer un identifiant » en conséquence.

Fait.

> Lorsque l’identificateur de ressource unique est construit à partir de l’adresse du catalogue, il doit permettre d’accéder à la fiche de métadonnées (cf. #3).
> => j'obtiens une erreur 404. Cela devrait renvoyer vers la fiche XML.

Tu peux préciser le préfixe que tu as mis ?

**Comment by taffoureau** [comment]
Ajouter un contrôle sur la chaîne de caractère saisie (doit commencer par http) ==> pas nécessaire

**Comment by fxprunayre** [comment]
> Lorsque l’identificateur de ressource unique est construit à partir de l’adresse du catalogue, il doit > permettre d’accéder à la fiche de métadonnées (cf. #3).
> => j'obtiens une erreur 404. Cela devrait renvoyer vers la fiche XML.

J'ai apporté une correction en multinode. Ca corrige peut être le pb. A tester.

**Comment by taffoureau** [comment]
1)
l'erreur 404 est persistante, je pense effectivement que c'est lié à la gestion des noeuds (mais je teste sur une instal srv classique) car l'adresse http://geosourcetest.brgm-rec.fr/geosource/5a4c6333-2751-425e-a003-59517d56c2 redirige vers http://geosourcetest.brgm-rec.fr/geosource/5a4c6333-2751-425e-a003-59517d56c2/fre/catalog.search?node=5a4c6333-2751-425e-a003-59517d56c2

2)
le bouton "mettre à jour les fiches" n'est pas traduit:
![fireshot screen capture 102 - mon geosource - mon organisation - geosourcetest_brgm-rec_fr_geosource_srv_fre_admin_console _settings](https://cloud.githubusercontent.com/assets/2026724/7353770/76a500c2-ed16-11e4-9bae-43699caebfb1.png)

**Comment by fxprunayre** [comment]
>  http://geosourcetest.brgm-rec.fr/geosource/5a4c6333-2751-425e-a003-59517d56c2 redirige vers http://geosourcetest.brgm-rec.fr/geosource/5a4c6333-2751-425e-a003-59517d56c2/fre/catalog.search?node=5a4c6333-2751-425e-a003-59517d56c2

C'est normal, on ne peut pas deviner à priori si c'est un noeud ou autre chose. Il faut que le noeud fasse parti de l'identifiant (cf. discussion précédente). 

Le préfix devrait être http://geosourcetest.brgm-rec.fr/geosource/srv/metadata pour être résolvable par géosource. Donc les identifiants du type http://geosourcetest.brgm-rec.fr/geosource/srv/metadata/5a4c6333-2751-425e-a003-59517d56c2  sont alors redirigés vers http://localhost:8080/geonetwork/srv/fre/catalog.search#/metadata/5a4c6333-2751-425e-a003-59517d56c2

Si vous voulez une redirection plus évolué, ca peut se mettre dans apache qui est devant aussi ?

**Comment by taffoureau** [comment]
Je suis favorable, lorsqu'aucun préfixe n'est défini, à contruire l'identifiant de cette manière:
http://[host]/geosource/srv/fre/xml.metadata.get?uuid=BR_BSS_BAA
En effet, il faut que l'URL renvoie vers la fiche XML...

**Comment by fxprunayre** [comment]
Libellé ajouté pour le bouton.

**Comment by fxprunayre** [comment]
Je propose quelque chose d'un peu différent :
- le "préfixe" par défaut serait http://localhost:8080/geonetwork/metadata/srv/{{uuid}}
- {{uuid}} sera remplacé par l'identifiant de la fiche
- ca permet de construire un peu n'importe quelle URL (pas uniquement avec un préfix)
- si pas de {{uuid}} alors le UUID est ajouté après le préfixe

L'URL devient http://localhost:8080/geonetwork/metadata/srv/c5f27065-9c32-4d71-bd70-bb96891efefe.xml (mieux qu'un xml.metadata.get ?)

@taffoureau ca convient ?

**Comment by fxprunayre** [comment]
Au GrandLyon, il y aurait le besoin d'ajouter une option pour supprimer le code existant et le remplacer par le nouveau.

**Comment by taffoureau** [comment]
OK pour moi pour cette proposition.

**Comment by fxprunayre** [comment]
A tester.

**Comment by taffoureau** [comment]
OK, mais il manque le [...].xml dans la valeur par défaut... Du coup, l'identifiant n'est résolvable vers rien...

**Comment by fxprunayre** [comment]
> OK, mais il manque le [...].xml dans la valeur par défaut... Du coup, l'identifiant n'est résolvable vers rien...

Fait https://github.com/geosource-catalogue/core-geonetwork/commit/699e3cb8a9a391c96145e0bca2070e93c062420d même si je suis pas favorable (ni Isabelle). Dans l'absolu, on devrait utiliser les Header des requêtes pour retourner le format supporté par celui qui fait la demande. Du coup une même URL pourrait retourner le HTML si le client ne supporte que le HTML, idem pour XML, JSON, RDF, ...
