### ISSUE TITLE
Menu de navigation dans le formulaire

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#70]
Ne pas proposer cette fonction dans la vue INSPIRE car les champs n'y sont pas organisés par rubrique.

De plus, ne fonctionne pas sous Firefox.

**Comment by fxprunayre** [comment]
Plier par défaut

**Comment by fxprunayre** [comment]
![image](https://f.cloud.github.com/assets/1701393/2204300/62e209e0-9939-11e3-9124-5ebf2105cef6.png)

Ajout d'une tooltip

**Comment by fxprunayre** [comment]
> De plus, ne fonctionne pas sous Firefox.

7604969dd5d17c644a317d43d0a2ca404a2728f1

**Comment by taffoureau** [comment]
Corrigé.
