### ISSUE TITLE
[Recherche] désactivation interface carto

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#72]
L'interface carto n'est pas désactivée.

**Comment by fxprunayre** [comment]
![image](https://f.cloud.github.com/assets/1701393/2216096/685ea30a-9a02-11e3-964d-33e05c3b1d39.png)

Peux tu préciser car je ne reproduis pas ? Cache du navigateur ?

Il n'y a :
- ni le switcher découverte/visualisation en haut
- pas de bouton dans les résultats (ajouter à la carte)
- pas de bouton ajouter la sélection à la carte dans la barre d'outil des résultats
- et pas de bouton ajouter à la carte dans la consultation de la fiche - uniquement le lien vers le service WMS

**Comment by taffoureau** [comment]
Corrigé.
