### ISSUE TITLE
Fonction sélectionner une vue

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#74]
Le déplacer dans la barre de menu horizontale.

Par défaut, proposer dans l'ordre les vues INSPIRE, complète, puis XML.

Renommer "Infobulles" par "Aide" (cela concerne uniquement l'aide?) et l'activer par défaut.

**Comment by fxprunayre** [comment]
> Renommer "Infobulles" par "Aide" 

https://github.com/geonetwork/core-geonetwork/commit/0b654b2094d1b5890c9ad109aedc57e14e43a219

> Par défaut, proposer dans l'ordre les vues INSPIRE, complète, puis XML.

https://github.com/geonetwork/core-geonetwork/commit/285633804ec7abe08503be6f65ab76651016271b

>  l'activer par défaut.

Ok peut être fait a posteriori dans admin > configuration du système

**Comment by fxprunayre** [comment]
> Le déplacer dans la barre de menu horizontale. 

a6b648f399174386cedc1f934b24210c12ad8819

**Comment by taffoureau** [comment]
Fait.
