### ISSUE TITLE
Boutons d'actions dans la barre de menu

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#77]
Cela concerne les boutons Enregistrer, Valider, Annuler et Sauver et fermer.

Les faire apparaître en gris, appliquer le changement de couleur au survol de la souris.

Indiquer en toutes lettres Sauver et fermer.

**Comment by fxprunayre** [comment]
> Indiquer en toutes lettres Sauver et fermer.

https://github.com/geonetwork/core-geonetwork/commit/c228da016f23d7980e7f54058385f051710e0eb8

**Comment by fxprunayre** [comment]
Code couleur bootstrap http://getbootstrap.com/css/#less-variables
