### ISSUE TITLE
Fonctionnement des infobulles pour l'aide

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#78]
Nous souhaiterions revenir à quelque chose de plus proche de ce qui était proposé dans le cahier des charges, à savoir :
- Apparition uniquement au clic sur une icône prévue à cet effet (l'apparition au survol risque d'être gênant à l'usage).
- Apparition de l'infobulle sous le champ concerné, avec possibilité de le déplacer avec la souris. En effet, avec l'affichage à droite tout le contenu n'est pas visible lorsque la fenêtre est réduite

**Comment by fxprunayre** [comment]
Tooltip sur clic pour les éléments non existant et les sections, focus pour les champs du formulaire.

**Comment by taffoureau** [comment]
![nouvelle image](https://f.cloud.github.com/assets/2026724/2196631/2df3f0ae-98b2-11e3-88e5-04b8dfc45184.png)

**Comment by fxprunayre** [comment]
a2a23dfa92a99870a2806ada35750ec2d736aef9
