### ISSUE TITLE
Id de ressource unique / création de fiche INSPIRE

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#8]
A la création à partir du modèle de données INSPIRE, l’identifiant est
automatiquement créé à partir du nouvel identifiant de la fiche (ne s’applique pas
lors du moissonnage ou d’une insertion via CSW-T)

Comment définir un modèle INSPIRE ?
- dataset (pas les services, pas les cartes)

Le mécanisme est ajouté à UFO (update-fixed-info.xsl).

**Comment by taffoureau** [comment]
OK pour le faire dans une version 2.11.1

**Comment by fxprunayre** [comment]
Après discussion, nous mettons en place une mise à jour en batch d'une sélection de fiche. Cf. #11 
Il est toujours possible d'utiliser le bouton de génération d'identifiant dans l'éditeur.
