### ISSUE TITLE
Configuration des CSW virtuels

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#80]
Les critères ne correspondent pas à ceux dans la version 2.9.x, par exemple :_source, _groupPublished

Par ailleurs, les critères contenant des listes de valeurs (par exemple, catégorie) sont vides.

**Comment by fxprunayre** [comment]
Ce sont les mêmes:
- _source = Catalogue d'origine
- _groupPublished = Groupe dans lequel une fiche est publiée.

Ajout de traduction + liste des catégories : 7d6bb256792dbb75eefcbd4a215d62f6d29f73d1

**Comment by taffoureau** [comment]
Corrigé.
