### ISSUE TITLE
Amélioration conversion profil France > ISO19139

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#81]
2)      Par ailleurs, sur l'export XML via le CSW, par exemple :

http://catalogue.sigloire.fr/geonetwork/srv/fre/csw?REQUEST=GetRecordById&version=2.0.2&service=CSW&ID=de13c460-54c9-11dd-99f1-00004f6210c3&OutputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full

Des éléments du profil fra apparaissent :

schéma : xsi:schemaLocation="http://www.isotc211.org/2005/fra ../../../../web/geonetwork/xml/schemas/iso19139fra/schema.xsd".

In content of element <MD_DataIdentification>: The content model does not allow element fra:relatedCitation to appear here. No further elements are allowed at this position at column 34, line 313 (see documentation)

Il y a aussi cela qui est ajouté : Attribute @namespace is not allowed on element <MD_DataIdentification> at column 82, line 110 (see documentation)

3)      Dans l'export ZIP, dans le fichier metadata_iso19139.xml :

Attribute @gco:isoType is not allowed on element <MD_DataIdentification> at column 74, line 123

**Comment by fxprunayre** [comment]
https://github.com/geosource-catalogue/core-geonetwork/commit/95fdb0eccf26adf279739a295e8311acd9bd0b5a

**Comment by taffoureau** [comment]
Non corrigé : http://metadatacarmen.brgm-rec.fr/geosource/1000/fre/csw?REQUEST=GetRecordById&version=2.0.2&service=CSW&ID=de13c460-54c9-11dd-99f1-00004f6210c3&OutputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full

**Comment by fxprunayre** [comment]
Pour se débarrasser du profil France :
- Sauvegarder la base !
- Se connecter en Admin
- Rechercher toutes les fiches à traiter (eg. schema iso19139.fra) http://localhost:8080/geonetwork/srv/eng/q?_schema=iso19139.fra&_isTemplate=y or n&summaryOnly=true
- Selectionner tout http://localhost:8080/geonetwork/srv/eng/metadata.select?selected=add-all
- Exécuter http://localhost:8080/geonetwork/srv/eng/metadata.batch.processing?process=to19139
- Progress report http://localhost:8080/geonetwork/srv/eng/metadata.batch.processing.report
- Attendre la fin
- En base de donnée

```
UPDATE metadata SET schemaid = 'iso19139' WHERE schemaid = 'iso19139.fra';
```
- Vérifier la migration

```
select * from metadata where data like '%FRA_Dat%'
```
- Dans l'administration du catalogue, réindexer le contenu.
