### ISSUE TITLE
Page accueil > bouton action de fiche sélectionnée: outil AUTRES ACTIONS \DUPLIQUER fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#86]
IE10 : Renvoie sur adresse vide (page blanche) @ http://metadatacarmen.brgm-rec.fr/geosource/1007/fre/catalog.edit#/create?from=327

Firefox 26 : tourne à vide sur page « créer une copie de »  avec barre d’avancement. 

![2 11_action_dupliquer](https://f.cloud.github.com/assets/6794535/2296268/41ab966e-a09c-11e3-91c4-9982750ad853.png)

**Comment by taffoureau** [comment]
Non reproductible.
