### ISSUE TITLE
Page accueil > bouton action de fiche sélectionnée: outil AUTRES ACTIONS \CREER UN ENFANT  non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#87]
IE10 : Renvoie sur adresse vide (page blanche) @  http://metadatacarmen.brgm-rec.fr/geosource/1007/fre/catalog.edit#/create?childOf=327 

Firefox 26 : tourne à vide sur page « créer une fiche enfant de »   avec barre d’avancement. 

![2 11_action_enfant](https://f.cloud.github.com/assets/6794535/2296279/7355b690-a09c-11e3-8fab-5e8cce2bd5da.png)

**Comment by taffoureau** [comment]
Non reproduit.
