### ISSUE TITLE
Page accueil > bouton action de fiche sélectionnée: outil AUTRES ACTIONS \ACTIVER LA GESTION DE L’ETAT DE LA FICHE non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#88]
Message d'erreur retourné:

IE 10: IllegalMonitorStateException :  (aucune valeur ne suit)
Firefox 26 : NullPointerException :    (aucune valeur ne suit)

![2 11_action_etat](https://f.cloud.github.com/assets/6794535/2296306/f526bd40-a09c-11e3-9b95-41cd86e7ea21.png)

**Comment by taffoureau** [comment]
Non reproductible.
