### ISSUE TITLE
Page accueil > bouton action de fiche sélectionnée: outil AUTRES ACTIONS \CATEGORIES non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#89]
L'outil ne retourne que la boite d'erreur en pj

![2 11_action_categories](https://f.cloud.github.com/assets/6794535/2296345/6f5c3626-a09d-11e3-9b8f-54877ae504d2.png)

![2 11_action_retourcategories](https://f.cloud.github.com/assets/6794535/2296346/73c7f0ec-a09d-11e3-9265-4db69cc9303c.png)

**Comment by taffoureau** [comment]
Non reproduit.
