### ISSUE TITLE
Page accueil > bouton action de fiche sélectionnée: outil AUTRES ACTIONS \EDITER non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#90]
IE 10 & Firefox 26 retournent: 

"NoClassDefFoundError...." détails  en pj. 

![2 11_action_autres_editer](https://f.cloud.github.com/assets/6794535/2296357/b64e0e60-a09d-11e3-84a7-ce09d73101f9.png)

**Comment by taffoureau** [comment]
lié à une mauvaise installation a priori...
