### ISSUE TITLE
Consultation de Fiche: HYPERLIEN non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#91]
L’hyperlien donné (voir pj) est incomplet, et ne fonctionne pas si collé dans la barre d’adresse du navigateur : 
Valeur dans la boite :      « ?uuid=b07044b0-a851-43a3-a15c-80f2cd0dbe3f »
En revanche, le lien porté par le texte « Link » est complet et fonctionnel.

![2 11_consultation_hyperlien](https://f.cloud.github.com/assets/6794535/2296384/1ba780d4-a09e-11e3-86fa-177a020b7761.png)

**Comment by fxprunayre** [comment]
Ok sous Chrome, FF, IE en mode debug
Ko sous IE en mode prod
