### ISSUE TITLE
Recherche par mot clé:  accents 

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#92]
La recherche par mot clé fonctionne bien si l’utilisateur entre une expression sans accents (ex : pour chercher « forêts », je tape « fore »). 

La recherche ne retourne aucun résultat si la recherche est bien orthographiée, avec accents. => si je tape « forê », aucun résultat, alors que des fiches existent avec des mots clés accentués. 

une recherche sur les deux orthographes serait top…. Mais en attendant, il suffirait d’ajouter un tooltip à la boite de recherche (et/ou un message au-dessus ou au-dessous d’elle), pour indiquer d’orthographier le mot clé sans accents dans la boite de recherche.

**Comment by fxprunayre** [comment]
Cf. #24

**Comment by taffoureau** [comment]
Fonctionne en monosite. à tester en multisite...

**Comment by fxprunayre** [comment]
Ajouter URIEncoding dans conf/server.xml:

```
    <Connector port="8080" protocol="HTTP/1.1" 
               connectionTimeout="20000" 
               URIEncoding="UTF-8"
               redirectPort="8443" />
```

Peut corriger le #164 également
