### ISSUE TITLE
IHM d'édition non fonctionnelle dans IE 10

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#93]
L’adresse «http://metadatacarmen.brgm-rec.fr/geosource/1007/fre/catalog.edit »  retourne une page blanche.

![2 11_lancer_edition](https://f.cloud.github.com/assets/6794535/2296427/acae8ba4-a09e-11e3-9dc1-78e392b72927.png)

**Comment by fxprunayre** [comment]
Non reproductible sous IE10 et IE9.
