### ISSUE TITLE
Edition: Bouton « Créer »  non fonctionnel

### ISSUE THREAD

**Issue by htouyeras** [geosource-catalogue/core-geonetwork#95]
Deux problèmes: 
1- IE 10 n’ouvre pas cette page-ci

2- dans Firefox 26, le bouton n’exécute aucune action, ni son menu déroulant. 

![2 11_creer_edition](https://f.cloud.github.com/assets/6794535/2296487/5a197d94-a09f-11e3-8783-65c9124986ba.png)

**Comment by taffoureau** [comment]
Non reproduit dans une version plus récente.
