### ISSUE TITLE
Plantage du site http://metadatacarmen.brgm-rec.fr/geosource/1002/fre/find

### ISSUE THREAD

**Issue by TERMEPhilippe** [geosource-catalogue/core-geonetwork#96]
Le site en objet est planté : message d'erreur
![site_sigloire](https://f.cloud.github.com/assets/6795250/2307599/cd88af74-a2ad-11e3-89e9-f1915c91b1b5.jpeg)

**Comment by taffoureau** [comment]
Pb lié à l'installation a priori.
