### ISSUE TITLE
Import de fiches de métadonnées

### ISSUE THREAD

**Issue by TERMEPhilippe** [geosource-catalogue/core-geonetwork#97]
Aucune fiche de métadonnée ne s'importe. Le fichier xml est exporté d'un geosource V2.9 et est valide. Le message d'erruer est parfois celui-ci
Message d'erreur :
Résultat de l'import de métadonnées :

Erreur lors de l'insertion de la métadonnée :

org/fao/geonet/kernel/mef/Importer$1$1 NoClassDefFoundError ... ... ... ... ... ... ... ... fre xml.mef.import.ui

**Comment by taffoureau** [comment]
pb d'installation a priori.
